#define MT_USERDEFINE_DESCRIPTION "creates product catalog parameter table definitions\0" 
#define MT_USERDEFINE_INTERNALNAME "ParamTableHook\0" 
#define MT_USERDEFINEORIGFILENAME MT_USERDEFINE_INTERNALNAME 
#define MT_USERDEFINEPRODUCTNAME MT_USERDEFINE_DESCRIPTION 
#define MT_USERDEF_PROJECTNAME MT_USERDEFINE_DESCRIPTION 
#define IDS_PROJNAME 100 
