#############################################################
#Generated on Thu Jul  1 11:24:30 1999
#############################################################


RELATIVEDIR := Core\Configuration\RCD\test

SRC := RCDTest.cpp

INCLUDEDIRS := $(OUTPUTROOT)\Core\Configuration\RCD $(SRCROOT)\Core\Configuration\RCD

MIDL_INCLUDEDIRS := 

DEFINES := 

EXTRA_LIBS :=   

EXTRA_SYS_LIBS := 

EXENAME := RCDTest

OVERRIDE_UNICODE_CPP_FLAGS := 1
TEST_UTILITY = 1