//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.BillMessages
{
  using System;
  using System.Collections.Generic;
  using System.Runtime.Serialization;
  using MetraTech.Basic;
  using MetraTech.BusinessEntity.Core;
  using MetraTech.BusinessEntity.Core.Model;
  using MetraTech.BusinessEntity.DataAccess.Metadata;
  
  
  [System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
  [System.SerializableAttribute()]
  [MetraTech.BusinessEntity.Core.Model.ConfigDrivenAttribute()]
  public partial class BillMessageAccountHistory : MetraTech.BusinessEntity.DataAccess.Persistence.BaseHistory
  {
    
    private global::Core.BillMessages.BillMessageAccountBusinessKey _billMessageAccountHistoryBusinessKey;
    
    public const string Property_Id = "Id";
    
    private System.Guid _billMessageAccountId;
    
    public const string Property_BillMessageAccountId = "BillMessageAccountId";
    
    private System.DateTime _startDate;
    
    public const string Property_StartDate = "StartDate";
    
    private System.Nullable<System.DateTime> _endDate;
    
    public const string Property_EndDate = "EndDate";
    
    private string _messageCode;
    
    public const string Property_MessageCode = "MessageCode";
    
    private System.Nullable<System.Int32> _accountId;
    
    public const string Property_AccountId = "AccountId";
    
    private System.Nullable<System.Guid> _billMessageId;
    
    public const string Property_BillMessageId = "BillMessageId";
    
    private int @__Version;
    
    public const string Property__Version = "_Version";
    
    private System.Nullable<System.DateTime> _creationDate;
    
    public const string Property_CreationDate = "CreationDate";
    
    private System.Nullable<System.DateTime> _updateDate;
    
    public const string Property_UpdateDate = "UpdateDate";
    
    private System.Nullable<System.Int32> _uID;
    
    public const string Property_UID = "UID";
    
    [MetraTech.BusinessEntity.DataAccess.Metadata.BusinessKeyAttribute()]
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual global::Core.BillMessages.BillMessageAccountBusinessKey BillMessageAccountBusinessKey
    {
      get
      {
        return this._billMessageAccountHistoryBusinessKey;
      }
      set
      {
        this._billMessageAccountHistoryBusinessKey = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual System.Guid BillMessageAccountId
    {
      get
      {
        return this._billMessageAccountId;
      }
      set
      {
        this._billMessageAccountId = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual System.DateTime StartDate
    {
      get
      {
        return this._startDate;
      }
      set
      {
        this._startDate = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual System.Nullable<System.DateTime> EndDate
    {
      get
      {
        return this._endDate;
      }
      set
      {
        this._endDate = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual string MessageCode
    {
      get
      {
        return this._messageCode;
      }
      set
      {
        this._messageCode = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual System.Nullable<System.Int32> AccountId
    {
      get
      {
        return this._accountId;
      }
      set
      {
        this._accountId = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual System.Nullable<System.Guid> BillMessageId
    {
      get
      {
        return this._billMessageId;
      }
      set
      {
        this._billMessageId = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public override int _Version
    {
      get
      {
        return this.@__Version;
      }
      set
      {
        this.@__Version = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public override System.Nullable<System.DateTime> CreationDate
    {
      get
      {
        return this._creationDate;
      }
      set
      {
        this._creationDate = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public override System.Nullable<System.DateTime> UpdateDate
    {
      get
      {
        return this._updateDate;
      }
      set
      {
        this._updateDate = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual System.Nullable<System.Int32> UID
    {
      get
      {
        return this._uID;
      }
      set
      {
        this._uID = value;
      }
    }
    
    public override MetraTech.BusinessEntity.DataAccess.Metadata.DataObject GetDataObject()
    {
      var _billMessageAccount = new global::Core.BillMessages.BillMessageAccount();
      _billMessageAccount.Id = BillMessageAccountId;
      _billMessageAccount._Version = _Version;
      _billMessageAccount.BillMessageAccountBusinessKey = BillMessageAccountBusinessKey;
      _billMessageAccount.StartDate = StartDate;
      _billMessageAccount.EndDate = EndDate;
      _billMessageAccount.MessageCode = MessageCode;
      _billMessageAccount.AccountId = AccountId;
      _billMessageAccount.BillMessageId = BillMessageId;
      _billMessageAccount._Version = _Version;
      _billMessageAccount.CreationDate = CreationDate;
      _billMessageAccount.UpdateDate = UpdateDate;
      _billMessageAccount.UID = UID;
      return _billMessageAccount;
    }
  }
}
