//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.BillMessages
{
  using System;
  using System.Collections.Generic;
  using System.Runtime.Serialization;
  using MetraTech.Basic;
  using MetraTech.BusinessEntity.Core;
  using MetraTech.BusinessEntity.Core.Model;
  using MetraTech.BusinessEntity.DataAccess.Metadata;
  
  
  [System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
  [System.SerializableAttribute()]
  [MetraTech.BusinessEntity.Core.Model.ConfigDrivenAttribute()]
  public partial class BillMessageHistory : MetraTech.BusinessEntity.DataAccess.Persistence.BaseHistory
  {
    
    private global::Core.BillMessages.BillMessageBusinessKey _billMessageHistoryBusinessKey;
    
    public const string Property_Id = "Id";
    
    private System.Guid _billMessageId;
    
    public const string Property_BillMessageId = "BillMessageId";
    
    private MetraTech.DomainModel.Enums.Core.Metratech_com.BillMessageType _messageType;
    
    public const string Property_MessageType = "MessageType";
    
    private string _messageText;
    
    public const string Property_MessageText = "MessageText";
    
    private string _messageFormat;
    
    public const string Property_MessageFormat = "MessageFormat";
    
    private int @__Version;
    
    public const string Property__Version = "_Version";
    
    private System.Nullable<System.DateTime> _creationDate;
    
    public const string Property_CreationDate = "CreationDate";
    
    private System.Nullable<System.DateTime> _updateDate;
    
    public const string Property_UpdateDate = "UpdateDate";
    
    private System.Nullable<System.Int32> _uID;
    
    public const string Property_UID = "UID";
    
    [MetraTech.BusinessEntity.DataAccess.Metadata.BusinessKeyAttribute()]
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual global::Core.BillMessages.BillMessageBusinessKey BillMessageBusinessKey
    {
      get
      {
        return this._billMessageHistoryBusinessKey;
      }
      set
      {
        this._billMessageHistoryBusinessKey = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual System.Guid BillMessageId
    {
      get
      {
        return this._billMessageId;
      }
      set
      {
        this._billMessageId = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual MetraTech.DomainModel.Enums.Core.Metratech_com.BillMessageType MessageType
    {
      get
      {
        return this._messageType;
      }
      set
      {
        this._messageType = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual string MessageText
    {
      get
      {
        return this._messageText;
      }
      set
      {
        this._messageText = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual string MessageFormat
    {
      get
      {
        return this._messageFormat;
      }
      set
      {
        this._messageFormat = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public override int _Version
    {
      get
      {
        return this.@__Version;
      }
      set
      {
        this.@__Version = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public override System.Nullable<System.DateTime> CreationDate
    {
      get
      {
        return this._creationDate;
      }
      set
      {
        this._creationDate = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public override System.Nullable<System.DateTime> UpdateDate
    {
      get
      {
        return this._updateDate;
      }
      set
      {
        this._updateDate = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual System.Nullable<System.Int32> UID
    {
      get
      {
        return this._uID;
      }
      set
      {
        this._uID = value;
      }
    }
    
    public override MetraTech.BusinessEntity.DataAccess.Metadata.DataObject GetDataObject()
    {
      var _billMessage = new global::Core.BillMessages.BillMessage();
      _billMessage.Id = BillMessageId;
      _billMessage._Version = _Version;
      _billMessage.BillMessageBusinessKey = BillMessageBusinessKey;
      _billMessage.MessageType = MessageType;
      _billMessage.MessageText = MessageText;
      _billMessage.MessageFormat = MessageFormat;
      _billMessage._Version = _Version;
      _billMessage.CreationDate = CreationDate;
      _billMessage.UpdateDate = UpdateDate;
      _billMessage.UID = UID;
      return _billMessage;
    }
  }
}
