//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Core
{
  using System;
  using System.Collections.Generic;
  using System.Collections.ObjectModel;
  using System.Runtime.Serialization;
  using System.Linq;
  using MetraTech.Basic;
  using MetraTech.BusinessEntity.Core;
  using MetraTech.BusinessEntity.Core.Model;
  using MetraTech.BusinessEntity.DataAccess.Metadata;
  using MetraTech.BusinessEntity.DataAccess.Persistence;
  
  
  [System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
  [System.SerializableAttribute()]
  [System.Runtime.Serialization.KnownTypeAttribute("GetKnownTypes")]
  [MetraTech.BusinessEntity.Core.Model.ConfigDrivenAttribute()]
  public partial class ChargeAdjustment : global::MetraTech.BusinessEntity.DataAccess.AdjustmentBase, global::Core.Core.Interface.IChargeAdjustment
  {
    
    public const string FullName = "Core.Core.ChargeAdjustment";
    
    private int @__Version;
    
    public const string Property__Version = "_Version";
    
    private System.Nullable<System.DateTime> _creationDate;
    
    public const string Property_CreationDate = "CreationDate";
    
    private System.Nullable<System.DateTime> _updateDate;
    
    public const string Property_UpdateDate = "UpdateDate";
    
    private System.Nullable<System.Int32> _uID;
    
    public const string Property_UID = "UID";
    
    public const string Property_Id = "Id";
    
    private global::Core.Core.ChargeAdjustmentBusinessKey _chargeAdjustmentBusinessKey = new ChargeAdjustmentBusinessKey();
    
    private int _adjustmentType = 0;
    
    public const string Property_AdjustmentType = "AdjustmentType";
    
    private string _description;
    
    public const string Property_Description = "Description";
    
    private System.Nullable<System.Int32> _reasonCode = 0;
    
    public const string Property_ReasonCode = "ReasonCode";
    
    private System.Nullable<System.Int32> _internalId = 0;
    
    public const string Property_InternalId = "InternalId";
    
    private IList<global::Core.Core.Interface.IChargeAdjustmentSession> _chargeAdjustmentSessions = new List<global::Core.Core.Interface.IChargeAdjustmentSession>();
    
    private global::Core.Core.Interface.IDispute _dispute;
    
    private global::MetraTech.BusinessEntity.DataAccess.Metadata.BusinessKey _disputeBusinessKey;
    
    private System.Nullable<System.Guid> _disputeId;
    
    public const string Property_InternalKey = "InternalKey";
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public override int _Version
    {
      get
      {
        return this.@__Version;
      }
      set
      {
        this.@__Version = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public override System.Nullable<System.DateTime> CreationDate
    {
      get
      {
        return this._creationDate;
      }
      set
      {
        this._creationDate = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public override System.Nullable<System.DateTime> UpdateDate
    {
      get
      {
        return this._updateDate;
      }
      set
      {
        this._updateDate = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual System.Nullable<System.Int32> UID
    {
      get
      {
        return this._uID;
      }
      set
      {
        this._uID = value;
      }
    }
    
    [MetraTech.BusinessEntity.DataAccess.Metadata.BusinessKeyAttribute()]
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual global::Core.Core.ChargeAdjustmentBusinessKey ChargeAdjustmentBusinessKey
    {
      get
      {
        return this._chargeAdjustmentBusinessKey;
      }
      set
      {
        this._chargeAdjustmentBusinessKey = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual int AdjustmentType
    {
      get
      {
        return this._adjustmentType;
      }
      set
      {
        this._adjustmentType = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public override string Description
    {
      get
      {
        return this._description;
      }
      set
      {
        this._description = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public override System.Nullable<System.Int32> ReasonCode
    {
      get
      {
        return this._reasonCode;
      }
      set
      {
        this._reasonCode = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public override System.Nullable<System.Int32> InternalId
    {
      get
      {
        return this._internalId;
      }
      set
      {
        this._internalId = value;
      }
    }
    
    public virtual List<global::Core.Core.Interface.IChargeAdjustmentSession> ChargeAdjustmentSessions
    {
      get
      {
        return _chargeAdjustmentSessions as List<global::Core.Core.Interface.IChargeAdjustmentSession>;
      }
      set
      {
        this._chargeAdjustmentSessions = value;
      }
    }
    
    public virtual global::Core.Core.Interface.IDispute Dispute
    {
      get
      {
        return this._dispute;
      }
      set
      {
        this._dispute = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual global::MetraTech.BusinessEntity.DataAccess.Metadata.BusinessKey DisputeBusinessKey
    {
      get
      {
        return this._disputeBusinessKey;
      }
      set
      {
        this._disputeBusinessKey = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual System.Nullable<System.Guid> DisputeId
    {
      get
      {
        return this._disputeId;
      }
      set
      {
        this._disputeId = value;
      }
    }
    
    public virtual void ClearDispute()
    {
      _dispute = null;
      _disputeBusinessKey = null;
      _disputeId = null;
    }
    
    public virtual global::Core.Core.Interface.IDispute LoadDispute()
    {
      object item = global::MetraTech.BusinessEntity.DataAccess.Persistence.StandardRepository.Instance.LoadInstanceFor("Core.Core.Dispute", "Core.Core.ChargeAdjustment", Id, "");
      return item == null ? null : (global::Core.Core.Interface.IDispute)item;
    }
    
    public override void SetupRelationships()
    {
      if (Dispute != null)
      {
DisputeBusinessKey = ((global::MetraTech.BusinessEntity.DataAccess.Metadata.DataObject)Dispute).GetBusinessKey();
DisputeId = Dispute.Id;
_dispute = null;
      }
      ChargeAdjustmentSessions = new List<global::Core.Core.Interface.IChargeAdjustmentSession>();
    }
    
    public virtual object Clone()
    {
      var _chargeAdjustment = new global::Core.Core.ChargeAdjustment();
      _chargeAdjustment.ChargeAdjustmentBusinessKey = (global::Core.Core.ChargeAdjustmentBusinessKey)ChargeAdjustmentBusinessKey.Clone();
      _chargeAdjustment.AdjustmentType = AdjustmentType;
      _chargeAdjustment.Description = Description;
      _chargeAdjustment.ReasonCode = ReasonCode;
      _chargeAdjustment.InternalId = InternalId;
      if (DisputeBusinessKey != null)
      {
        _chargeAdjustment.DisputeBusinessKey = (MetraTech.BusinessEntity.DataAccess.Metadata.BusinessKey)DisputeBusinessKey.Clone();
      }
      _chargeAdjustment.DisputeId = DisputeId;
      return _chargeAdjustment;
    }
    
    public virtual void Save()
    {
      var item = this;
      global::MetraTech.BusinessEntity.DataAccess.Persistence.StandardRepository.Instance.SaveInstance(ref item);
    }
    
    public override void CopyPropertiesFrom(global::MetraTech.BusinessEntity.DataAccess.Metadata.DataObject dataObject)
    {
      var item = dataObject as global::Core.Core.ChargeAdjustment;
      if (item.Dispute != null)
      {
        Dispute = item.Dispute;
      }
      else
      {
        if (item.Dispute == null && item.DisputeId == null)
        {
          Dispute = null;
        }
      }
      AdjustmentType = item.AdjustmentType;
      Description = item.Description;
      ReasonCode = item.ReasonCode;
      InternalId = item.InternalId;
      ChargeAdjustmentBusinessKey = item.ChargeAdjustmentBusinessKey;
    }
    
    public static new System.Type[] GetKnownTypes()
    {
      var knownTypes = new List<System.Type>();
      knownTypes.Add(typeof(global::Core.Core.ChargeAdjustmentBusinessKey));
      return knownTypes.ToArray();
    }
  }
  
  [System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
  [System.SerializableAttribute()]
  public partial class ChargeAdjustmentBusinessKey : MetraTech.BusinessEntity.DataAccess.Metadata.BusinessKey, global::Core.Core.Interface.IChargeAdjustmentBusinessKey
  {
    
    private string _entityFullName = "Core.Core.ChargeAdjustment";
    
    private System.Guid _internalKey;
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public override string EntityFullName
    {
      get
      {
        return this._entityFullName;
      }
      set
      {
        this._entityFullName = "Core.Core.ChargeAdjustment";
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual System.Guid InternalKey
    {
      get
      {
        return this._internalKey;
      }
      set
      {
        this._internalKey = value;
      }
    }
    
    public override object Clone()
    {
      var _businessKey = new ChargeAdjustmentBusinessKey();
      _businessKey.InternalKey = InternalKey;
      return _businessKey;
    }
  }
}
