//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MTAuthExec.rc
//
#define IDS_PROJNAME                    100
#define IDR_MTPRINCIPALPOLICYREADER     101
#define IDR_MTSECURITYCONTEXTREADER     102
#define IDR_MTCOMPOSITECAPABILITYTYPEREADER 103
#define IDR_MTATOMICCAPABILITYTYPEREADER 104
#define IDR_MTCOMPOSITECAPABILITYTYPEWRITER 105
#define IDR_MTCOMPOSITECAPABILITYTYPEWRITER1 106
#define IDR_MTATOMICCAPABILITYTYPEWRITER 107
#define IDR_MTSECURITYREADER            108
#define IDR_MTPRINCIPALPOLICYWRITER     109
#define IDR_MTACCESSTYPECAPABILITYWRITER 110
#define IDR_MTPATHCAPABILITYWRITER      111
#define IDR_MTROLEREADER                112
#define IDR_MTROLEWRITER                113
#define IDR_MTCOMPOSITECAPABILITYWRITER 114
#define IDR_MTENUMTYPECAPABILITYWRITER  115
#define IDR_MTDECIMALCAPABILITYWRITER   116
#define IDR_MTBATCHAUTHCHECKREADER      117

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        201
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         201
#define _APS_NEXT_SYMED_VALUE           118
#endif
#endif
