METRATECH_MESSAGE_MAP metra_message_mapping[] = {
{ MT_ERR_COMMENT, "/**********************************************************************//** Event Definitions...                                             **//**    Defines common Event Ids and their message text...            **//**********************************************************************/" },
{ MT_ERR_ERROR_MSG, "This is a really bad error." },
{ MT_ERR_PARENT_COMMITTED, "Parent session already committed." },
{ MT_ERR_NO_PROPERTY, "Property does not exist." },
{ MT_ERR_DUPLICATE_PROPERTY, "Property already exists." },
{ MT_ERR_MESSAGE_MODULE_NOT_FOUND, "Error message module not found." },
{ MT_ERR_BAD_HTTP_RESPONSE, "Bad HTTP response." },
{ MT_ERR_PARSE_ERROR, "Unable to parse message." },
{ MT_ERR_NOT_INITIALIZED, "Not initialized." },
{ MT_ERR_SERVER_ERROR, "Unknown server error." },
{ MT_ERR_UNKNOWN_SERVICE, "Server has no knowledge of this service." },
{ MT_ERR_BAD_PROPERTY, "A property is invalid." },
{ MT_ERR_NO_HOSTS, "No metering servers added." },
{ MT_ERR_LOCAL_MODE_RECORD_EXISTS, "A duplicate record file name was found for a local mode session." },
{ MT_ERR_LOCAL_MODE_RECORD_COPY, "An error occurred moving the local mode record to the pending area." },
{ MT_ERR_LOCAL_MODE_NOT_SET, "A local mode must be selected before setting the local mode pathinformation." },
{ MT_ERR_LOCAL_MODE_BAD_DIR, "The local mode directory does not exist." },
{ MT_ERR_LOCAL_MODE_DIR_SETUP, "An error occurred creating the local mode storage subdirectories." },
{ MT_ERR_LOCAL_PLAYBACK_FILE, "Local mode playback failed to open the playback record." },
{ MT_ERR_LOCAL_PLAYBACK_UNKNOWN_COMMAND, "An unknown command was detected in a playback record. Probably due to corrupt file or version mismatch." },
{ MT_ERR_LOCAL_CANNOT_CREATE, "Could not create the playback record." },
{ MT_ERR_COMPRESS_CODEBOOK_FILE, "Invalid codebook path." },
{ MT_ERR_COMPRESS_UNKNOWN_MESSAGE, "Unknown or bogus compressed message type." },
{ MT_ERR_COMPRESS_BAD_CODEBOOK, "Fatal syntax error in codebook definition." },
{ MT_ERR_COMPRESS_PROP_MISSING, "A required property was never set in the compression object." },
{ MT_ERR_COMPRESS_UNKNOWN_COMMAND, "Unknown or bogus command in message." },
{ MT_ERR_COMPRESS_BUFFER_OVERRUN, "Error in compressor, output buffer overrun." },
{ MT_ERR_COMPRESS_READ_EOF, "Unexpected EOF reading compressed data." },
{ MT_ERR_COMPRESS_READ_BUFFER, "Buffer overrun reading compressed data." },
{ MT_ERR_COMPRESS_PROTOCOL, "Binary stream does not match codebook protocol." },
{ MT_ERR_COMPRESS_VERSION, "Version from compressed message does not match codebook protocol." },
{ MT_ERR_CONFIG_PARSE_ERROR, "Error parsing XML configuration." },
{ MT_ERR_BAD_CONFIG, "Invalid configuration value." },
{ MT_ERR_NOT_IMPLEMENTED, "Feature has not yet been implemented." },
{ MT_ERR_FIELD_COMPUTATION, "Field computation failed." },
{ MT_ERR_READ_ERROR, "The read operation failed." },
{ MT_ERR_SYN_TIMEOUT, "Synchronized metering timeout." },
{ MT_ERR_SERVER_BUSY, "The server is busy handling requests." },
{ MT_ERR_RESPONSE_MISSING, "No response was received for a session that requested it." },
{ MT_ERR_SESSION_SET_FAILED, "Some or all sessions in the session set failed." },
{ MT_ERR_CANNOT_CLOSE, "This session is part of a session set or a child session and cannot be closed." },
{ MT_ERR_LOCALMODE_NOSUPPORT_SC_TI, "Localmode does not support sessions with the security context or the transaction id set" },
{ MT_ERR_BATCH_NAME_CANNOT_BE_BLANK, "Batch name cannot be blank when creating a batch" },
{ MT_ERR_BATCH_NAMESPACE_CANNOT_BE_BLANK, "Batch namespace cannot be blank when creating a batch" },
{ MT_ERR_BATCH_SEQUENCE_NUMBER_CANNOT_BE_BLANK, "Batch sequence number cannot be blank when creating a batch" },
{ MT_ERR_AUTHORIZATION_FAILURE_BAD_CREDENTIALS, "Authorization failure.  Please check your credentials" },
{ MT_ERR_BLANK_HOST_SPECIFIED, "Host name is required property and was specified as blank" },
{ MT_ERR_INCORRECT_PORT_SPECIFIED, "Port is required property and was specified as less than or equal to zero" },
{ MT_ERR_TERMINATE, "table terminator" }
};
