/* ANNALITICS DATAMART table*/
        CREATE TABLE Customer (
        InstanceId varchar (255) NOT NULL,
		MetraNetId int NOT NULL,
		AccountType varchar(200) NOT NULL,
		ExternalId nvarchar(255) NOT NULL,
		ExternalIdSpace nvarchar(40) NOT NULL,
		FirstName nvarchar(40),
		MiddleName nvarchar(1),
		LastName nvarchar(40),
		Company nvarchar(255),
		Currency nvarchar(10),
		City nvarchar(40),
		State nvarchar(40),
		ZipCode nvarchar(40),
		Country nvarchar(100),
		Email nvarchar(100),
		Phone nvarchar(40),
		HierarchyMetraNetId int NOT NULL,
		HierarchyAccountType varchar(200) NOT NULL,
		HierarchyExternalId nvarchar(255) NOT NULL,
		HierarchyExternalIdSpace nvarchar(40) NOT NULL,
		HierarchyFirstName nvarchar(40),
		HierarchyMiddleName nvarchar(1),
		HierarchyLastName nvarchar(40),
		HierarchyCompany nvarchar(255),
		HierarchyCurrency nvarchar(10),
		HierarchyCity nvarchar(40),
		HierarchyState nvarchar(40),
		HierarchyZipCode nvarchar(40),
		HierarchyCountry nvarchar(100),
		HierarchyEmail nvarchar(40),
		HierarchyPhone nvarchar(40))
      