create table SubscriptionsByMonth (
			InstanceId varchar(64),
            SubscriptionId int not null,
            Year int not null, 
            Month int not null,
            Currency nvarchar(3) not null,
            MRR numeric(22,10) not null,
            MRRPrimaryCurrency numeric(22,10) not null,
            MRRNew numeric(22,10) not null,
            MRRNewPrimaryCurrency numeric(22,10) not null,
            MRRBase numeric(22,10) not null,
            MRRBasePrimaryCurrency numeric(22,10) not null,
            MRRRenewal int not null,
            MRRRenewalPrimaryCurrency numeric(22,10) not null,
            MRRPriceChange numeric(22,10) not null,
			MRRPriceChangePrimaryCurrency numeric(22,10) not null,
            MRRChurn int not null,
            MRRChurnPrimaryCurrency numeric(22,10) not null,
            MRRCancelation int not null,
            MRRCancelationPrimaryCurrency numeric(22,10) not null,
            SubscriptionRevenue int not null,
            SubscriptionRevPrimaryCurrency numeric(22,10) not null,
            DaysInMonth int not null,
            DaysActiveInMonth int not null,
            ReportingCurrency nvarchar(3) null)