
        CREATE TABLE t_acc_usage
        (id_sess number(20) NOT NULL,
        tx_UID raw(16) NOT NULL,
        id_acc number(10) NOT NULL,
        id_payee number(10) NOT NULL,
        id_view number(10) NOT NULL,
        id_usage_interval number(10) NOT NULL,
        id_parent_sess number(20) NULL,
        id_prod number(10) NULL,
        id_svc number(10) NOT NULL,
        dt_session date NOT NULL,
        amount number(22,10) NOT NULL,
        am_currency nvarchar2(3) NOT NULL,
        dt_crt date NOT NULL,
        tx_batch raw(16) NULL,
        tax_federal number(22,10) NULL,
        tax_state number(22,10) NULL,
        tax_county number(22,10) NULL,
        tax_local number(22,10) NULL,
        tax_other number(22,10) NULL,
        id_pi_instance number(10) NULL,
        id_pi_template number(10) NULL,
        id_se number(10) NOT NULL,
        div_currency nvarchar2(3) NULL,
        div_amount number(22,10) NULL,
        tax_inclusive nvarchar2(1) NULL,
        tax_calculated nvarchar2(1) NULL,
        tax_informational nvarchar2(1) NULL,
        CONSTRAINT PK_t_acc_usage PRIMARY KEY (id_sess,id_usage_interval))
      