
          CREATE TABLE t_failed_transaction (
            id_failed_transaction number(10) NOT NULL ,
            State char(1) NOT NULL ,
            tx_StateReasonCode nvarchar2 (255),
          	tx_FailureID raw (16),
          	tx_FailureID_Encoded nvarchar2 (30)  NOT NULL ,
          	tx_FailureCompoundID raw (16),
          	tx_FailureCompoundID_encoded nvarchar2 (30)  NOT NULL ,
          	id_PossiblePayeeID number(10) NOT NULL ,
    	  	id_PossiblePayerID number(10) DEFAULT '-1' NOT NULL,
          	tx_FailureServiceName nvarchar2 (64)  NOT NULL ,
          	n_Code number(10) NOT NULL ,
          	n_Line number(10) NOT NULL ,
          	dt_FailureTime date NOT NULL ,
          	dt_MeteredTime date NOT NULL ,
          	tx_Sender nvarchar2 (30)  NOT NULL ,
          	tx_ErrorMessage nvarchar2 (1024)  NOT NULL ,
          	tx_StageName nvarchar2 (64)  NOT NULL ,
          	tx_PlugIn nvarchar2 (64)  NOT NULL ,
          	tx_Module nvarchar2 (255)  NOT NULL ,
          	tx_Method nvarchar2 (64)  NOT NULL ,
          	tx_Batch raw (16),
          	tx_Batch_Encoded nvarchar2 (30),
            b_compound char (1) NOT NULL,
            tx_errorcodemessage nvarchar2 (255) NOT NULL,
            id_sch_ss number(10) null,
            dt_StateLastModifiedTime date NOT NULL,
            dt_Start_Resubmit TIMESTAMP,
            resubmit_Guid VARCHAR2(36),
            CONSTRAINT PK_t_failed_transaction PRIMARY KEY (id_failed_transaction)
            )
      