#############################################################
#Generated on Thu Jul  1 11:24:00 1999
#############################################################

AUTO_BINARY_VERSION := 0

RELATIVEDIR := Core\MTUtil\test

SRC := MTDateTest.cpp

INCLUDEDIRS := $(OUTPUTROOT)\$(RELATIVEDIR)\..

MIDL_INCLUDEDIRS := 

DEFINES := 

EXTRA_LIBS := mtutil.lib

EXTRA_SYS_LIBS := 

EXENAME := mtdatetest

OVERRIDE_UNICODE_CPP_FLAGS :=
TEST_UTILITY =1 

