
		CREATE GLOBAL TEMPORARY TABLE TMP_old_units
   (	
	ID_SUB NUMBER(10,0), 
	N_VALUE NUMBER(22,10), 
	VT_START DATE, 
	VT_END DATE NOT NULL ENABLE, 
	TT_END DATE NOT NULL ENABLE) ON COMMIT preserve ROWS
	