
  CREATE GLOBAL TEMPORARY TABLE TMP_REDIR
   (   ID_PAYER NUMBER(10,0) NOT NULL ENABLE, 
       ID_PAYEE NUMBER(10,0) NOT NULL ENABLE, 
       VT_START DATE NOT NULL ENABLE, 
       VT_END DATE NOT NULL ENABLE
   ) ON COMMIT preserve ROWS

