CREATE TABLE t_rec_win_bcp_for_reverse(
  C_BILLEDTHROUGHDATE DATE,
  C_CYCLEEFFECTIVEDATE DATE,
  C__PRICEABLEITEMINSTANCEID NUMBER(10,0),
  C__PRICEABLEITEMTEMPLATEID NUMBER(10,0),
  C__PRODUCTOFFERINGID NUMBER(10,0),
  C__SUBSCRIPTIONID NUMBER(10,0) NOT NULL ENABLE
);
