CREATE GLOBAL TEMPORARY TABLE tmp_unbilledPIs (
  C__PRICEABLEITEMINSTANCEID NUMBER(10,0) NOT NULL ENABLE,
  C__PRICEABLEITEMTEMPLATEID NUMBER(10,0) NOT NULL ENABLE,
  C__SUBSCRIPTIONID NUMBER(10,0) NOT NULL ENABLE
) ON COMMIT DELETE ROWS
