#############################################################
# Generated on Thursday Jul  8 15:00:00 2004
#############################################################


RELATIVEDIR := plugins\test\C++PropTest

SRC := C++PropTest.cpp

INCLUDEDIRS := $(OUTPUTROOT)\$(RELATIVEDIR)\..\include $(OUTPUTROOT)\$(RELATIVEDIR)\..\..\include $(OUTPUTROOT)\$(RELATIVEDIR)\..\skeleton $(PLUGINS_INCLUDE)

MIDL_INCLUDEDIRS := 

DEFINES := 

EXTRA_LIBS :=   skeleton.lib  mtcomerr.lib error.lib

EXTRA_SYS_LIBS := 

DLLNAME := C++PropTestPlugIn

OVERRIDE_UNICODE_CPP_FLAGS := 

DEF_FILE := C++PropTest.def

TEST_UTILITY := 1