/* Generated with Author-it 5.5.264.13693  3/13/2013 12:35:24 PM */
Page=new Array();Page[0]=new Array("To see, access, and modify a MetraView administrative site, you require the following special account: ","MetraViewAdmin","or ","A subscriber account that has been given the following capabilities:","MetraView Admin, Read Business Modeling Entities, Write Business Modeling Entities","For more information, see MetraView User Capabilities","The MetraView URL can be http://&lt;servername&gt;/MetraView or http://&lt;servername&gt;/&lt;SiteName&gt; or https://&lt;servername&gt;/MetraView or https://&lt;servername&gt;/&lt;SiteName&gt;","The Admin tab is visible when you log into a MetraView site with one of these roles.","The Admin site provides access to all the configurable components of a MetraView site. Starting here you can create new site instances, and you can add, edit, or remove any predefined site component. ","You can add shared reports, which are query-driven grids, and new widgets, which are standard ASCX controls. To create new Business Modeling Entities (BMEs), you require MetraNet ICE. For more information, search the Documentation Set.","Accessing the Admin Site","18683.htm");
Page[1]=new Array("MetraNet installs the default MetraView site. Using MetraView Admin, you can customize this site or create new instances of MetraView sites. Each site has its own branch of folders and files (under RMP\\Extensions). This corresponds with a unique IIS virtual directory - and therefore URL. Each site can have different nested components and other customizations. A single Admin interface lets you manage all the site instances you create and their nested components.","Creating new site instances is not supported in this release.","Adding Site Instances","18692.htm");
Page[2]=new Array("The first stage in creating a new site is to use the ICE site creation tool.","From ConfigExplorer click the Sites panel.","Right-click Sites » Add.","In the Add Site dialog:","Enter the name of the site. This determines the virtual directory name also.","Select MetraView as the extension and the existing site to copy."," @","When you click Add ICE creates:","A new folder tree for your site under RMP\\Extensions\\MetraView\\Sites.","It also creates a new virtual directory for your site in IIS under the Default Site.","Now you have added the site, there are a number of manual configuration steps that need to be done. ","Please ask your MetraTech Professional Services consultant for details.","Create the Site in ICE","18692.htm#o23163");
Page[3]=new Array("Creating new site instances with the MetraView Admin user interface is not supported in this release. You should create the site in ICE first. (After this, you can edit the new site with MetraView.)","After you have added the site with ICE and completed the manual configuration steps, you are ready to create a new site instance in the Admin section (of the original MetraView site):","Create the Site in ICE.","Edit the new site properties. ","Log into MetraView as MetraViewAdmin.","Select the Admin tab and click @ Edit for your new site.","Edit the Site Components.","Expand the site to view its details and click the components you want to edit.  ","Edit the Site Instance in MetraView","18692.htm#o23164");
Page[4]=new Array("The Configure Site menu item is your single point of access to all the configurable components of a MetraView site's user interface (UI). Starting here you can edit the site properties and you can add, edit, or remove any site component. ","To edit the site properties:","From the Site list, for the site you want to work with, click @ Edit to open the Edit Site page.","A Site is a nested collection of user interface controls contained in an instance of the MetraView web framework. When you drill down through a site you are selecting the control type and then one instance of that control. ","See how to navigate the site components.","User interface controls or components are called Business Modeling Entities (BMEs) elsewhere in MetraNet documentation for system integrators and configuration developers. For clarity, this Help refers to them simply as components.","Site components","Component","Purpose","BillSetting","Sets MetraView online bill properties.","Dashboard","Contains the Column and Widget components.","EntryPoints","Sets a nonstandard entry point to the site.","ProductViewMappings","Sets the display of usage information for a particular service.","ReportInventories","Manages the subscriber report types.","Configuring a Site","18650.htm");
Page[5]=new Array("The top-level Site component is where you define basic properties of your site instance."," Parameter","Description","Site Name","A unique text string for identifying this site.","Description","A description of the site. ","Is Site Down for Maintenance?","Choose this option whenever you make changes through the Configure Site interface. You would usually require a backup MetraView server during this time.","Culture","This is the localization setting for the site. The default is US English (en-US). Do not change the culture unless the corresponding localized files exist for the MetraNet platform.","Themes","Theme names and options are determined by the CSS style sheet. Do not change the theme unless the correspondingly named style sheet exists in RMP\\Extensions\\MetraView\\Sites\\&lt;sitename&gt;\\Styles. ","Logo Image","Specify the name of a logo image: GIF, JPG, or PNG. The file should be added to RMP\\Extensions\\MetraView\\Sites\\&lt;sitename&gt;\\Images.","Site Properties","18669.htm");
Page[6]=new Array("The branding process relies on standard style sheets and images, which are easily accessed and modified as described in the previous topic.","A simple example of branding using the supplied Red theme and a different logo image","To brand a site:","Select or modify a supplied CSS style sheet or create a new one. ","Stylesheets are located in RMP\\Extensions\\MetraView\\Sites\\&lt;Site&gt;\\Styles ","The name of the Theme in site properties must match the name of the CSS file name.","Replace the logo image and images for backgrounds, column rectangles, and buttons.","All images are located in RMP\\Extensions\\MetraView\\Sites\\&lt;Site&gt;\\Images","Restart IIS and log in again to see the changes.","Branding a Site","24635.htm");
Page[7]=new Array("The Site is a container for the various components that comprise a MetraView site's user interface. From the Site instance, you can create, edit, and delete instances of these components. You can access all the properties of these individual components through the Site container.","All component changes should be thoroughly tested before going live with the site.","Navigating the Site Components","Beginning with the site instance, all components are related to their container component in a one-to-many or many-to-many relationship. For example, you can define one or more custom Dashboard instances. ","There are two ways to navigate site components: using relationships and using simple drill-down. Which one you use depends on where you are in the component hierarchy.","To add, view, edit, or delete the top-level site components:","From the Site list, for the site instance you want to work with, click @ View Relationships to open the Relationships for &lt;YourSite&gt; page.","To add, view, edit, or delete subcomponents: ","From the component list, expand (@) the site instance you want to work with, so that you see the component icons under More Items.","Click the component type you want to work with.","When you do this, the subcomponent list, such as for Dashboards, will show the @ View Relationships option.","Editing the Site Components","18654.htm");
Page[8]=new Array("Site components are potential interface items until you add them and configure them with defining properties. When you add a component, you are creating an instance of that component. After it's added, you edit the component to specify a particular set of attributes: such as page location, column position, size, color, and so on. You may need to add multiple component instances to one page or several pages in your web application. For example, a particular widget, such as calendar, might be useful on several pages.","To define or view a component:","From the Site list, click @ View Relationships.","This opens the Relationships for &lt;YourSite&gt; page - a grid with tabs for each component you add, view, or modify in your custom site. (The site has a one-to-many relationship with each component, so you can potentially add multiple instances of each component.)","The tabs are: Bill Setting, Dashboard, Entry Point, Product View Mapping, and Report Inventory.","For each component type, select @ Add, @ Edit, or @ Remove. ","For example, to add a new dashboard instance: ","Click the Dashboard tab and then click Add.","A new window opens the component list.","Click Add again to create the new component instance.","Proceed to edit the new component.","Deleting or removing a component can have serious consequences. Never do this in a production environment.","Creating new site instances is not supported in this release.","Adding, Editing, or Deleting Components","18676.htm");
Page[9]=new Array("The Admin Site's Dashboard contains a collection of Columns, layout components (which are themselves the containers for widgets and parameters. The Dashboard is therefore a container for the objects and properties defined by these other entities. The Dashboard, itself, is contained by the Site.","All the Dashboard components are BMEs. This means that all changes you make to these components are stored in the database. In order to move BME data from one development system to another or to a production system, you can use the BMEImportExport tool.","To access the Dashboard-related components:","From Configure Site, select the instance of the site you want to work with and click Edit.","Under More Items, click the Dashboard component.","Do not use @ View Relationships to select the Dashboard.","To edit the Dashboard properties:","For the Dashboard instance you want to work with, click @ Edit to open the Edit Dashboard page.","To add, view, edit, or delete a Column:","For the Dashboard instance you want to work with, click @ View Relationships.","Click Add and define the Column properties. ","To add, view, edit, or delete a Widget:","For the Column instance you want to work with, click @ View Relationships.","Click Add and define the Widget properties. ","To add, view, edit, or delete a Parameter:","For the Widget instance you want to work with, click @ View Relationships.","Click Add and define the Parameter properties. ","Editing the Dashboard","18120.htm");
Page[10]=new Array("The MetraView Dashboard contains a high-level summary of a subscriber's account information. It is usually the landing page when subscribers log in to their account. The dashboard displays the following:  ","User profile information, including account name and account number.","Payment information summary, including the last posted payment, adjustments and the amount due.","Default and favorite reports, including subscriber saved searches. ","Account usage details by product and by department. ","Access to account information. ","Subscriptions and available product offering information. ","What Is the MetraView Dashboard?","18642.htm");
Page[11]=new Array("Property","Description","Name","A unique name of the dashboard","Description","A description of the dashboard","Title","The title of the dashboard that may appear at the top. ","CssClass","An override to CSS class used for the Site theme.","Style","An additional set of styles to be added to the rendered dashboard.","Dashboard-contained components","Object","Purpose","Columns","Sets the columnar layout of the Dashboard.","Widgets","Sets widgets for each column.","Parameters","Sets optional parameters for widgets.","Dashboard Properties","24261.htm");
Page[12]=new Array("The Columns component determines how many columns the Dashboard contains and the position and content of each column.","To drill down to columns: ","Select Site » Dashboard » Columns"," Parameter","Description","Name","A unique name for the column","Description","An optional description of the column","Title","The title of the column that may appear at the top","Position","The position of the column in the dashboard (1, 2, 3)","Width","Width of the column as a decimal fraction of the dashboard. (For example an even-sized 3 column dashboard would have 3 columns with widths of .33)","CssClass","An override to CSS class used for the Site or Dashboard theme.","Style","An additional set of styles to be added to the rendered column.","Columns","18660.htm");
Page[13]=new Array("A Widget is any ASCX user control. They are contained in MetraView\\UserControls. You can add and remove widgets from the columns of your Dashboard.","To drill down to widgets: ","Select Site » Dashboards » Columns » Widgets","To add a new widget:","Click Add.","Enter the mandatory fields: name, column position, and path to ASCX file.","For example:","Name","BillAndPayments","Position","1","Widget Path","UserControls\\BillandPayments.ascx","Each widget has a set of optional, configurable properties:"," Parameter","Description","CssClass","An override to CSS class used for the Site, Dashboard, and Column themes.","Description","A description of the widget","Height","Set a fixed height in pixels (preserving aspect ratio).","Name ","A unique name for the widget","Position","The position of the widget in the column (1, 2, 3 for 1st, 2nd, 3rd, and so on).","Style","Additional set of styles to be added to the rendered widget.","Title","The title of the widget that may appear at the top.","WidgetPath","The relative path from the Site folder (UserControls/&lt;widget&gt;.ascx) ","WidgetType","Widgets","18666.htm");
Page[14]=new Array("For every widget, you have the option of setting optional parameters. ","To drill down to widget parameters: ","Select Site » Dashboard » Column » Widgets » Parameters","Parameter","Description","Name ","The parameter name.","Value","The parameter value.","Description","A description of the purpose of the parameter","Is Required","Whether or not the parameter is required.","Parameters","18675.htm");
Page[15]=new Array("The Bill Settings component has properties that determine the billing interface for the whole site."," Parameter","Default Value","Description","Allow Online Payment","True","Permits subscribers to make payments online.","Allow Saved Reports","True","Permits subscribers to save their own filters as a report.","Allow Self-Care","True","Permits the user to update their contact and account information.","Inline Adjustments","False","Shows adjustments inline or as separate line items in the bill.","Usage Note<br />This setting applies to prebill adjustments only. Those are adjustments to the bill's subtotal before tax. The default is to shows these adjustments on a separate line labeled Prebill Adjustments. If you set Inline Adjustments to be True, it means the adjustment charges or credits are not broken out as a separate amount, but are rolled into the subtotal. More Details","Inline Tax","False","Shows taxation inline or as a separate line item in the bill. ","Usage Note<br />The default is to shows taxes on a separate line labeled Tax. If Inline Adjustments is False also, a line item also appears for Tax Adjustments. If you set Inline Tax to be True, it means that taxes are not broken out as a separate amount, but are rolled into the subtotal. More Details","Show Only Hard-Closed Intervals","False","Shows estimated billing data if a billing interval is still open. By setting this to true, subscribers can see the open interval usage on the main Bill &amp; Payments page (for both by-product and by-folder views) and on the History page. ","Warning<br />This data may be inaccurate due to unprocessed charges. Depending on how your billing operations are managed, this could delay the closing of disputes and cause user dissatisfaction.","MetraView currently supports a single instance of this component. ","Bill Settings","18656.htm");
Page[16]=new Array("There are four possible cases for setting how adjustments, taxes, and tax adjustments are displayed in subscriber bills. The out-of-the-box option is shown in the first row of this table. Both Inline Taxes and Inline Adjustments are set to False - in which case all three lines appear in the bill.","False","True","What Lines Are Displayed in the Bill?","Inline Taxes<br />Inline Adjustments","Prebill Adjustments<br />Tax<br />Tax Adjustments","Inline Taxes<br />Inline Adjustments","(Adjustments and Taxes rolled into Subtotal)","Inline Taxes","Inline Adjustments","Tax<br />(Adjustments rolled into Subtotal)","Inline Adjustments","Inline Taxes","Prebill Adjustments<br />(Taxes rolled into Subtotal)","These settings affect the display only. They do not affect any calculations affecting subtotals or totals.","Using the Inline Bill Options","18656.htm#o24319");
Page[17]=new Array("The Entry Points component sets up a nonstandard entry point to the site.","Entry points use a secure &quot;ticketing&quot; method that permits users authenticated by a trusted site to enter particular pages in your MetraView site directly, without having to go through a login sequence. Users are authenticated using a ticket that is generated by a MetraNet-supplied ASPX file after their logon name/password is validated. "," Parameter","Description","Entry Point Name","A name that uniquely identifies the entry point.","Description","A description of the purpose of the entry point and the users who can access it.","URL","A entry-point page URL.","In the Documentation Set","Using Entry Points","Entry Points","18657.htm");
Page[18]=new Array("The Product View Mappings component determines how usage information for a particular service is displayed in MetraView. ","Product view mappings are currently nonconfigurable from MetraView Admin.","Product View Mappings","18658.htm");
Page[19]=new Array("MetraView supports four report types: Interactive Reports, Query-Driven Grids, Saved Filtered Grid Data, and Pre-generated PDFs. In the Report Inventory component, you can set various configuration parameters that will determine what criteria subscribers can use to search for reports.  There are no default values for these parameters.","Parameter","Required","Description","Name ","Yes","Name of the report.","Description","No","Extended description of the report.","Report Type","No","Indicates the type of report: Grid or Chart.","Category","No","Optional category used to group reports.","Extension","No","The extension in which the feature (such as BME) was defined.","Layout Name","No","The case-sensitive name of the grid as defined in ICE.","Priority","No","Numeric indicator specifying the priority ID of this report, so that it appears in the correct position in the report list.","Capabilities","No","Comma-separated list of capabilities that the end users need to view this report.","Is Visible","No","Indicates if the report is visible in the system.		","In the Documentation Set","Adding a Grid as a MetraView Shared Report","Report Inventories","18659.htm");
Page[20]=new Array("MetraView supports four report types: Interactive Reports, Query-Driven Grids, Saved Filtered Grid Data, and Pre-generated PDFs. In the Report Inventory component, you can set various configuration parameters that will determine what criteria subscribers can use to search for reports.  There are no default values for these parameters.","Parameter","Required","Description","Name ","Yes","Name of the report.","Description","No","Extended description of the report.","Report Type","No","Indicates the type of report: Grid or Chart.","Category","No","Optional category used to group reports.","Extension","No","The extension in which the feature (such as BME) was defined.","Layout Name","No","The case-sensitive name of the grid as defined in ICE.","Priority","No","Numeric indicator specifying the priority ID of this report, so that it appears in the correct position in the report list.","Capabilities","No","Comma-separated list of capabilities that the end users need to view this report.","Is Visible","No","Indicates if the report is visible in the system.		","In the Documentation Set","Adding a Grid as a MetraView Shared Report","Editing Reports","18651.htm");
Page[21]=new Array("The MetraView Log is for system administration use. It is available only when running your browser on the MetraView web server.","The error log is viewable only from a browser running on the MetraView web server.","Logs","18653.htm");
var PageCount=22;

function search(SearchWord){
var Result="";
var NrRes=0;
Result='<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">\n';
Result+="<html>\n";
Result+="<head>\n";
Result+="<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>\n";
Result+="<title>Search Results</title>\n";
Result+='<script language="javascript" type="text/javascript" charset="UTF-8" src="dhtml_search.js"></script>\n';
Result+='<link rel="stylesheet" type="text/css" href="stylesheet.css">\n';
Result+="<style type='text/css'>\n";
Result+=".searchDetails {font-family:verdana; font-size:8pt; font-weight:bold}\n";
Result+=".searchResults {font-family:verdana; font-size:8pt}\n";
Result+=".searchResults a{color:#555555; text-decoration:none;}\n";
Result+=".searchResults a:hover{color:#0000FF; text-decoration:underline;}\n";
Result+="</style>\n";
Result+="</head>\n";
Result+="<body onload='javascript:document.SearchForm.SearchText.focus()'>\n";
Result+='<table class="searchDetails" border="0" cellspacing="0" cellpadding="2" width="100%">\n';
Result+='<tr><td>Enter a keyword or <u>exact phrase</u></td></tr>';
Result+='<tr><td>';
Result+='<form name="SearchForm" action="javascript:search(document.SearchForm.SearchText.value)">';
if(SearchWord.length>=1){
   while(SearchWord.indexOf("<")>-1 || SearchWord.indexOf(">")>-1 || SearchWord.indexOf('"')>-1){
       SearchWord=SearchWord.replace("<","&lt;").replace(">","&gt;").replace('"',"&quot;");
   }
}
Result+='<input type="text" name="SearchText" size="25" value="' + SearchWord + '" />';
Result+='&nbsp;<input type="submit" value="&nbsp;Go&nbsp;"/></form>';
Result+='</td></tr></table>\n';

if(SearchWord.length>=1){
   SearchWord=SearchWord.toLowerCase();
   this.status="Searching, please wait...";
   Result+="<table border='0' cellpadding='5' class='searchResults' width='90%'>";
   for(j=0;j<PageCount;j++){
       k=Page[j].length-1;
       for(i=0;i<k;i++){
           WordPos=Page[j][i].toLowerCase().indexOf(SearchWord);
           if(WordPos>-1){
               FoundWord=Page[j][i].substr(WordPos,SearchWord.length);
               NrRes++;
               Result+="<tr><td>";
               Result+="<a target='BODY' href='"+Page[j][k]+"'>"+Page[j][k-1].replace(FoundWord,FoundWord.bold())+"</a><br/>\n";

               if(i<k-1){
                   if(Page[j][i].length>350){
                       Result+="..."+Page[j][i].substr(WordPos-100,200+FoundWord.length).replace(FoundWord,FoundWord.bold())+"...\n";
                   }
                   else{
                       Result+=Page[j][i].replace(FoundWord,FoundWord.bold())+"\n";
                   }
               }
               Result+="</td></tr>";
               break;
           }
       }
   }
   Result+="</table>";
   Result+="<p class='searchDetails'>&nbsp;" + NrRes + " result(s) found.</p>";
}

Result+="</body></html>";
this.status="";
this.document.open();
this.document.write(Result);
this.document.close();
}