#############################################################
#Generated on Thu Jul  1 11:24:33 1999
#############################################################


RELATIVEDIR := Core\Configuration\Calendar\MTCalendar\test

SRC := test.cpp

INCLUDEDIRS := $(OUTPUTROOT)\$(RELATIVEDIR)\..

MIDL_INCLUDEDIRS := 

DEFINES := 

EXTRA_LIBS := error.lib mtutil.lib

EXTRA_SYS_LIBS := 

EXENAME := TestCalendar

OVERRIDE_UNICODE_CPP_FLAGS := 1
TEST_UTILITY = 1
