using System;

namespace MetraTech.Basic.Exception
{
  [Serializable]
  public static class ErrorCode
  {
    public static int ENTITY_VALIDATION_MISSING_CLASS_NAME = 1;
    public static int ENTITY_VALIDATION_INVALID_CLASS_IDENTIFIER = 2;
    public static int ENTITY_VALIDATION_MISSING_PLURAL_NAME = 3;
    public static int ENTITY_VALIDATION_MISSING_NAMESPACE = 4;
    public static int ENTITY_VALIDATION_INVALID_NAMESPACE = 5;
    public static int ENTITY_VALIDATION_MISSING_ASSEMBLY_NAME = 6;
    public static int ENTITY_VALIDATION_DUPLICATE_CLASS_NAME = 7;
    public static int ENTITY_VALIDATION_MISSING_BUSINESS_KEY = 8;
    public static int ENTITY_VALIDATION_ENTITY_IS_NOT_CONFIG_DRIVEN = 9;
    public static int ENTITY_VALIDATION_MISSING_CODE_FILE = 10;
    public static int ENTITY_VALIDATION_MISSING_HBM_FILE = 11;
    public static int ENTITY_VALIDATION_INVALID_TYPE_NAME = 12;
    public static int ENTITY_VALIDATION_INVALID_IDENTIFIER = 13;
    public static int ENTITY_VALIDATION_MISSING_BUSINESS_ENTITY_SECTION = 14;
    public static int ENTITY_VALIDATION_DUPLICATE_PROPERTY_NAME = 15;
    public static int ENTITY_VALIDATION_MISSING_INTERMEDIATE_JOIN_CLASS = 16;
    public static int ENTITY_VALIDATION_MISSING_TABLE_NAME = 17;
    public static int ENTITY_VALIDATION_MISSING_DATABASE_NAME = 18;
    public static int ENTITY_VALIDATION_MISSING_PARENT_ENTITY_NAME = 19;

    public static int PROPERTY_VALIDATION_MISSING_NAME = 100;
    public static int PROPERTY_VALIDATION_INVALID_IDENTIFIER = 101;
    public static int PROPERTY_VALIDATION_MISSING_TYPE_NAME = 102;
    public static int PROPERTY_VALIDATION_INVALID_PROPERTY_TYPE = 103;
    public static int PROPERTY_VALIDATION_CANNOT_CONVERT_DEFAULT_VALUE_TO_PROPERTY_TYPE = 104;
    public static int PROPERTY_VALIDATION_MISSING_ENTITY = 105;
    public static int PROPERTY_VALIDATION_RESERVED_NAME = 106;
    public static int PROPERTY_VALIDATION_MISSING_COMPUTATION_TYPE_NAME = 107;
    public static int PROPERTY_VALIDATION_CANNOT_PARSE_COMPUTATION_TYPE_NAME = 108;
    public static int PROPERTY_VALIDATION_CANNOT_CANNOT_CREATE_COMPUTATION_TYPE = 109;
    public static int PROPERTY_VALIDATION_INVALID_BASE_CLASS_FOR_COMPUTATION_TYPE = 110;
    public static int PROPERTY_VALIDATION_COMPUTATION_TYPE_NAME_SPECIFIED_FOR_NON_COMPUTED_PROPERTY = 111;
    public static int PROPERTY_VALIDATION_ENCRYPTED_PROPERTY_CAN_ONLY_BE_STRING = 112;
    public static int PROPERTY_VALIDATION_INVALID_BUSINESS_KEY_PROPERTY = 113;
    public static int PROPERTY_VALIDATION_INVALID_STRING_LENGTH = 114;
    public static int PROPERTY_VALIDATION_MISSING_COLUMN_NAME = 115;
    public static int PROPERTY_VALIDATION_MISSING_COLUMN_METADATA = 116;

    public static int RELATIONSHIP_VALIDATION_MISSING_SOURCE = 200;
    public static int RELATIONSHIP_VALIDATION_MISSING_TARGET = 201;
    public static int RELATIONSHIP_VALIDATION_INVALID_RELATIONSHIP_TYPE = 202;
    public static int RELATIONSHIP_VALIDATION_INVALID_SOURCE_MULTIPLICITY = 203;
    public static int RELATIONSHIP_VALIDATION_MISSING_SOURCE_ENTITY_NAME = 204;
    public static int RELATIONSHIP_VALIDATION_MISSING_SOURCE_KEY_COLUMN = 205;
    public static int RELATIONSHIP_VALIDATION_MISSING_SOURCE_PROPERTY_NAME = 206;
    public static int RELATIONSHIP_VALIDATION_INVALID_TARGET_MULTIPLICITY = 207;
    public static int RELATIONSHIP_VALIDATION_MISSING_TARGET_ENTITY_NAME = 208;
    public static int RELATIONSHIP_VALIDATION_MISSING_TARGET_KEY_COLUMN = 209;
    public static int RELATIONSHIP_VALIDATION_MISSING_TARGET_PROPERTY_NAME = 210;
    public static int RELATIONSHIP_VALIDATION_MISSING_JOIN_PROPERTY_NAME = 211;
    public static int RELATIONSHIP_VALIDATION_MISSING_CASCADE = 212;
    public static int RELATIONSHIP_VALIDATION_INVALID_CASCADE = 213;
    public static int RELATIONSHIP_VALIDATION_MISSING_RELATIONSHIP_ENTITY = 214;
    public static int RELATIONSHIP_VALIDATION_INVALID_IS_DEFAULT = 215;
    public static int RELATIONSHIP_VALIDATION_INVALID_IS_SELF_RELATIONSHIP = 216;
    public static int RELATIONSHIP_VALIDATION_INVALID_HAS_JOIN_TABLE = 217;
    public static int RELATIONSHIP_VALIDATION_INVALID_IS_BIDIRECTIONAL = 218;

    public static int RELATIONSHIP_END_VALIDATION_MISSING_QUALIFIED_NAME = 300;
    public static int RELATIONSHIP_END_VALIDATION_MISSING_PROPERTY_NAME = 301;
    public static int RELATIONSHIP_END_VALIDATION_INVALID_PROPERTY_NAME = 302;

    public static int QUALIFIED_NAME_VALIDATION_MISSING_TYPE_NAME = 400;
    public static int QUALIFIED_NAME_VALIDATION_MISSING_ASSEMBLY_NAME = 401;
    public static int QUALIFIED_NAME_VALIDATION_MISSING_TENANT_NAME = 402;

    public static int SELF_RELATIONSHIP_ENTITY_VALIDATION_MISSING_ENTITY = 500;

    public static int HISTORY_ENTITY_VALIDATION_MISSING_ENTITY = 600;

    public static int COLUMN_METADATA_VALIDATION_MISSING_TABLE_NAME = 700;
    public static int COLUMN_METADATA_VALIDATION_MISSING_COLUMN_NAME = 701;
    public static int COLUMN_METADATA_VALIDATION_MISSING_PROPERTY_NAME = 702;
    public static int COLUMN_METADATA_VALIDATION_MISSING_DB_TYPE_NAME = 703;
    public static int COLUMN_METADATA_VALIDATION_MISSING_CSHARP_TYPE_NAME = 704;

  }

  
}
