
				SELECT 
				*
				FROM 
				CI_INFOOBJECTS 
				WHERE SI_INSTANCE = 1
				AND SI_SCHEDULEINFO.SI_PROGRESS < 2
				AND USAGE_SERVER_RUN_ID = '%%ID_RUN%%'
				AND USAGE_SERVER_BILLGROUP_ID = '%%ID_BILLGROUP%%'
			