
				SELECT TOP 1000
				SI_ID, SI_SCHEDULE_STATUS, SI_SCHEDULEINFO.SI_SCHEDULE_FLAGS
				FROM 
				CI_INFOOBJECTS 
				WHERE SI_INSTANCE = 1
				AND SI_NAME = '%%SI_NAME%%'
				AND USAGE_SERVER_RUN_ID = '%%ID_RUN%%'
				AND USAGE_SERVER_BILLGROUP_ID = '%%ID_BILLGROUP%%'
				AND USAGE_SERVER_ACCOUNT_ID = '%%ID_ACCOUNT%%'
				AND SI_SCHEDULEINFO.SI_SCHEDULE_FLAGS != 1
			