
				SELECT 
				SI_SCHEDULEINFO.SI_OUTCOME,
				SI_STATUSINFO
				FROM 
				CI_INFOOBJECTS 
				WHERE SI_INSTANCE = 1
				AND SI_NAME = '%%SI_NAME%%'
				AND USAGE_SERVER_RUN_ID = '%%ID_RUN%%'
				AND USAGE_SERVER_BILLGROUP_ID = '%%ID_BILLGROUP%%'
				AND SI_SCHEDULE_STATUS = 3
			