
				SELECT TOP 100
				SI_ID, SI_SCHEDULEINFO.SI_DESTINATION 
				FROM 
				CI_INFOOBJECTS 
				WHERE SI_INSTANCE = 1
				AND SI_NAME = '%%SI_NAME%%'
				AND USAGE_SERVER_RUN_ID = '%%ID_RUN%%'
				AND USAGE_SERVER_BILLGROUP_ID = '%%ID_BILLGROUP%%'
				AND USAGE_SERVER_ACCOUNT_ID = '%%ID_ACCOUNT%%'
			