
	   CREATE TABLE DM_T_ACC_USAGE_CREDIT (
		id_sess number(38) not null,
		tx_uid raw(16) not null,
		id_acc number(38) not null,
		id_payee number(38) not null,
 		top_lvl_1 int null, top_lvl_1_desc varchar(200) null, 
 		top_lvl_2 int null, top_lvl_2_desc varchar(200) null, 
 		top_lvl_3 int null, top_lvl_3_desc varchar(200) null, 
 		top_lvl_4 int null, top_lvl_4_desc varchar(200) null, 
 		top_lvl_5 int null, top_lvl_5_desc varchar(200) null, 
 		top_lvl_6 int null, top_lvl_6_desc varchar(200) null,
 		top_lvl_7 int null, top_lvl_7_desc varchar(200) null,
 		top_lvl_8 int null, top_lvl_8_desc varchar(200) null,
 		top_lvl_9 int null, top_lvl_9_desc varchar(200) null,
 		top_lvl_10 int null, top_lvl_10_desc varchar(200) null,
		id_view number(38) not null,
		id_prod number(38) null,
		dt_session date not null,
		id_usage_interval number(38) not null,
		amount number(22,10) not null,
		am_currency varchar2 (3) not null,
		dt_crt date not null,
		tax_federal number(22,10) null,
		tax_state number(22,10) null,
		tax_county number(22,10) null,
		tax_local number(22,10) null,
		tax_other number(22,10) null,
		c_status varchar2 (20) not null,
		c_issuer varchar2 (80) not null,
		c_reason varchar2 (80) not null,
		c_invoicecomment varchar2 (255) not null,
		c_internalcomment varchar2 (255) not null,
		c_requestamount number(22,10) not null,
		c_creditamount number(22,10) not null) 
	     