
	   CREATE TABLE t_acc_usage_credit (
		id_sess bigint NOT NULL,
		tx_uid varbinary (16) NOT NULL,
		id_acc int NOT NULL,
		id_view int NOT NULL,
		id_prod int NULL,
		dt_session datetime NOT NULL,
		id_usage_interval int NOT NULL,
		amount numeric(22,10) NOT NULL,
		am_currency nvarchar (3) NOT NULL,
		dt_crt datetime NOT NULL,
		tax_federal numeric(22,10) NULL,
		tax_state numeric(22,10) NULL,
		tax_county numeric(22,10) NULL,
		tax_local numeric(22,10) NULL,
		tax_other numeric(22,10) NULL,
		c_Status varchar (20) NOT NULL,
		c_Issuer varchar (80) NOT NULL,
		c_Reason varchar (80) NOT NULL,
		c_InvoiceComment varchar (255) NOT NULL,
		c_InternalComment varchar (255) NOT NULL,
		c_RequestAmount numeric(22,10) NOT NULL,
		c_CreditAmount numeric(22,10) NOT NULL) 
	     