
           CREATE TABLE DM_T_INV_SUMM_PARENT (
	   	id_sess number(38) not null,
	   	id_parent_sess number(38) null,
	   	id_acc number(38) not null,
		id_payee number(38) not null,
 		top_lvl_1 int null, top_lvl_1_desc varchar(200) null, 
 		top_lvl_2 int null, top_lvl_2_desc varchar(200) null, 
 		top_lvl_3 int null, top_lvl_3_desc varchar(200) null, 
 		top_lvl_4 int null, top_lvl_4_desc varchar(200) null, 
 		top_lvl_5 int null, top_lvl_5_desc varchar(200) null, 
 		top_lvl_6 int null, top_lvl_6_desc varchar(200) null,
 		top_lvl_7 int null, top_lvl_7_desc varchar(200) null,
 		top_lvl_8 int null, top_lvl_8_desc varchar(200) null,
 		top_lvl_9 int null, top_lvl_9_desc varchar(200) null,
 		top_lvl_10 int null, top_lvl_10_desc varchar(200) null,
	   	id_view number(38) not null,
	   	tx_view_name varchar2 (255) not null,
	   	tx_view_description nvarchar2 (255) null,
	   	id_usage_interval number(38) not null,
	   	confcall_amount number(22,10) not null,
	   	confcall_tax_federal number(22,10) null,
	   	confcall_tax_state number(22,10) null,
	   	confcall_tax_county number(22,10) null,
	   	confcall_tax_local number(22,10) null,
	   	confcall_tax_other number(22,10) null,
	   	accountcredit_amount number(22,10) not null,
	   	accountcredit_tax_federal number(22,10) null,
	   	accountcredit_tax_state number(22,10) null,
	   	accountcredit_tax_county number(22,10) null,
	   	accountcredit_tax_local number(22,10) null,
	   	accountcredit_tax_other number(22,10) null,
	   	bundleddiscounts_name varchar2 (30) null,
	   	bundleddiscounts_amount number(22,10) not null,
	   	bundleddiscounts_tax_federal number(22,10) null,
	   	bundleddiscounts_tax_state number(22,10) null,
	   	bundleddiscounts_tax_county number(22,10) null,
	   	bundleddiscounts_tax_local number(22,10) null,
	   	bundleddiscounts_tax_other number(22,10) null,
	   	unbundleddiscounts_name varchar2 (80) null,
	   	unbundleddiscounts_amount number(22,10) not null,
	   	unbundleddiscounts_tax_federal number(22,10) null,
	   	unbundleddiscounts_tax_state number(22,10) null,
	   	unbundleddiscounts_tax_county number(22,10) null,
	   	unbundleddiscounts_tax_local number(22,10) null,
	   	unbundleddiscounts_tax_other number(22,10) null,
	   	misccharges_amount number(22,10) not null,
	   	misccharges_tax_federal number(22,10) null,
	   	misccharges_tax_state number(22,10) null,
	   	misccharges_tax_county number(22,10) null,
	   	misccharges_tax_local number(22,10) null,
	   	misccharges_tax_other number(22,10) null,
	   	id_invoice number(38) null,
	   	invoice_string varchar2 (50) null,
	   	nm_space varchar2 (100) null,
	   	invoice_date date null,
	   	invoice_due_date date null,
	   	c_recurringchargename varchar2 (40) null,
	   	c_dailyrate number(22,10) null,
	   	c_recurringchargestartdate date null,
	   	c_recurringchargeenddate date null,
	   	c_recurringcharge number(22,10) null,
	   	c_activedays number(38) null,
	   	c_proratedcharge number(22,10) null,
	   	c_issuer varchar2 (80) null,
	   	c_misccharges_inv_comment varchar2 (255) null,
	   	c_credittime date null,
	   	c_reason varchar2 (255) null,
	   	c_invoicecomment varchar2 (255) null,
	   	c_conferenceid nvarchar2 (30) null,
	   	c_conferencename nvarchar2 (60) null,
	   	c_leadername nvarchar2 (60) null,
	   	c_actualstarttime date null,
	   	c_actualduration number(22,10) null,
	   	c_actualnumconnections number(38) null,
	   	c_balanceforwardcalculateddate date null,
	   	c_previousbalance number (22,10) null,
	   	c_balanceadjustmentstotal number (22,10) null,
	   	c_balanceforward number (22,10) null,
	   	c_description varchar(255) null,
	   	c_eventdate date null,
	   	accountstatus nvarchar2 (510) null,
	   	c_reservationcharges number (22,10) null,
	   	c_unusedportcharges number (22,10) null,
	   	c_connectiontotalamount number (22,10) null,
	   	c_adjustmentamount number (22,10) null,
	   	c_overusedportcharges number (22,10) null,
	   	CONSTRAINT pk_dm_t_inv_summ_parent PRIMARY KEY (id_sess)) 
	  