
	   CREATE TABLE DM_T_INV_SUMM_CHILDREN (
		id_sess number(38) not null,
		id_parent_sess number(38) null,
		id_acc number(38) not null,
		id_payee number(38) not null,
 		top_lvl_1 int null, top_lvl_1_desc varchar(200) null, 
 		top_lvl_2 int null, top_lvl_2_desc varchar(200) null, 
 		top_lvl_3 int null, top_lvl_3_desc varchar(200) null, 
 		top_lvl_4 int null, top_lvl_4_desc varchar(200) null, 
 		top_lvl_5 int null, top_lvl_5_desc varchar(200) null, 
 		top_lvl_6 int null, top_lvl_6_desc varchar(200) null,
 		top_lvl_7 int null, top_lvl_7_desc varchar(200) null,
 		top_lvl_8 int null, top_lvl_8_desc varchar(200) null,
 		top_lvl_9 int null, top_lvl_9_desc varchar(200) null,
 		top_lvl_10 int null, top_lvl_10_desc varchar(200) null,
		id_view number(38) not null,
		tx_view_name varchar2 (255) not null,
		tx_view_description nvarchar2 (255) null,
		id_usage_interval number(38) not null,
		confconn_amount number(22,10) not null,
		confconn_tax_federal number(22,10) null,
		confconn_tax_state number(22,10) null,
		confconn_tax_county number(22,10) null,
		confconn_tax_local number(22,10) null,
		confconn_tax_other number(22,10) null,
		id_invoice number(38) null,
		invoice_string varchar2 (50) null,
		c_conferenceid nvarchar2 (30) null,
		c_participantname nvarchar2 (60) null,
		c_actualstarttime date null,
		c_actualendtime date null,
		c_userrole nvarchar2 (255) null,
		c_calltype nvarchar2 (255) null,
		c_transport nvarchar2 (255) null) 
	  