
	   CREATE TABLE DM_T_CC_FAILURE (
		id_sess number(38) not null,
		id_acc number(38) not null,
		id_payee number(38) not null,
 		top_lvl_1 int null, top_lvl_1_desc varchar(200) null, 
 		top_lvl_2 int null, top_lvl_2_desc varchar(200) null, 
 		top_lvl_3 int null, top_lvl_3_desc varchar(200) null, 
 		top_lvl_4 int null, top_lvl_4_desc varchar(200) null, 
 		top_lvl_5 int null, top_lvl_5_desc varchar(200) null, 
 		top_lvl_6 int null, top_lvl_6_desc varchar(200) null,
 		top_lvl_7 int null, top_lvl_7_desc varchar(200) null,
 		top_lvl_8 int null, top_lvl_8_desc varchar(200) null,
 		top_lvl_9 int null, top_lvl_9_desc varchar(200) null,
 		top_lvl_10 int null, top_lvl_10_desc varchar(200) null,
		id_view number(38) not null,
		tx_view_name varchar2 (255) not null,
	   	tx_view_description nvarchar2 (255) null,	
		id_usage_interval number(38) not null,
		dt_session date not null,
		dt_crt date not null,
		amount number (22,10) not null,
		tax_federal number (22,10) null,
		tax_state number (22,10) null,
		tax_county number (22,10) null,
		tax_local number (22,10) null,
		tax_other number (22,10) null,
		c_originalaccountid number(38) not null,
		c_creditcardtype number(38) not null,
		tx_cc_name varchar2 (255) not null,
		tx_cc_description nvarchar2 (255) not null,
		c_lastfourdigits varchar2 (4) not null,
		c_reason varchar2 (256) null,
		c_retcode number(38) not null,
		c_respstring varchar2 (128) not null,
		c_terminalid number(38) null,
		c_csrid varchar2 (40) null,
		c_paymentservicetransactionid varchar2 (32) null,
		c_exported varchar2 (1) not null)
	     