
	   CREATE TABLE t_inv_summ_children (
		id_sess number(20) NOT NULL,
		id_parent_sess number(20) NULL,
		id_acc int NOT NULL,
		id_view int NOT NULL,
		tx_view_name varchar (255) NOT NULL,
		tx_view_description nvarchar2 (255) NULL,
		id_usage_interval int NOT NULL,
		confconn_amount numeric(22,10) NOT NULL,
		confconn_tax_federal numeric(22,10) NULL,
		confconn_tax_state numeric(22,10) NULL,
		confconn_tax_county numeric(22,10) NULL,
		confconn_tax_local numeric(22,10) NULL,
		confconn_tax_other numeric(22,10) NULL,
		id_invoice int NULL,
		invoice_string varchar (50) NULL,
		c_ConferenceID nvarchar2 (30) NULL,
		c_ParticipantName nvarchar2 (60) NULL,
		c_ActualStartTime date NULL,
		c_ActualEndtime date NULL,
		c_UserRole nvarchar2 (255) NULL,
		c_CallType nvarchar2 (255) NULL,
		c_Transport nvarchar2 (255) NULL) 
	  