
	   CREATE TABLE DM_T_ACC_USAGE_SUMM (
		id_sess number(38) not null,
		id_acc number(38) not null,
		id_payee number(38) not null,
 		top_lvl_1 int null, top_lvl_1_desc varchar(200) null, 
 		top_lvl_2 int null, top_lvl_2_desc varchar(200) null, 
 		top_lvl_3 int null, top_lvl_3_desc varchar(200) null, 
 		top_lvl_4 int null, top_lvl_4_desc varchar(200) null, 
 		top_lvl_5 int null, top_lvl_5_desc varchar(200) null, 
 		top_lvl_6 int null, top_lvl_6_desc varchar(200) null,
 		top_lvl_7 int null, top_lvl_7_desc varchar(200) null,
 		top_lvl_8 int null, top_lvl_8_desc varchar(200) null,
 		top_lvl_9 int null, top_lvl_9_desc varchar(200) null,
 		top_lvl_10 int null, top_lvl_10_desc varchar(200) null,
		id_view number(38) not null,
		id_usage_interval number(38) not null,
		call_count number(38) null,
		amount number(22,10) not null,
		am_currency varchar2 (3) not null,
		dt_crt date null,
		tax_federal number(22,10) null,
		tax_state number(22,10) null,
		tax_county number(22,10) null,
		tax_local number(22,10) null,
		tax_other number(22,10) null,
		view_desc nvarchar2 (255) null)
	     