/**************************************************************************
 * @doc
 *
 * Copyright 1997-2000 by MetraTech Corporation
 * All rights reserved.
 *
 * THIS SOFTWARE IS PROVIDED "AS IS", AND MetraTech Corporation MAKES
 * NO REPRESENTATIONS OR WARRANTIES, EXPRESS OR IMPLIED. By way of
 * example, but not limitation, MetraTech Corporation MAKES NO
 * REPRESENTATIONS OR WARRANTIES OF MERCHANTABILITY OR FITNESS FOR ANY
 * PARTICULAR PURPOSE OR THAT THE USE OF THE LICENSED SOFTWARE OR
 * DOCUMENTATION WILL NOT INFRINGE ANY THIRD PARTY PATENTS,
 * COPYRIGHTS, TRADEMARKS OR OTHER RIGHTS.
 *
 * Title to copyright in this software and any associated
 * documentation shall at all times remain with MetraTech Corporation,
 * and USER agrees to preserve the same.
 *
 * Created by: Chen He
 * $Header$
 ***************************************************************************/
// PropGen.idl : IDL source for PropGen.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (PropGen.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

import "MTPipelinePlugIn.idl";

	[
		object,
		uuid(BD498481-37A4-11D2-80EE-006008C0E8B7),
		dual,
		helpstring("Dummy Interface"),
		pointer_default(unique)
	]
	interface IDummy : IDispatch
	{
	};
[
	uuid(BD498471-37A4-11D2-80EE-006008C0E8B7),
	version(1.0),
	helpstring("PropGen 1.0 Type Library")
]
library PROPGENLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(BD498482-37A4-11D2-80EE-006008C0E8B7),
		helpstring("PropGenProcessor Class")
	]
	coclass PropGenProcessor
	{
		[default] interface IMTPipelinePlugIn;
	};
};
