
CREATE GLOBAL TEMPORARY TABLE TMP_RC_ADVANCE_1
(
  ID_ACC                    NUMBER(10),
  ID_SUB                    NUMBER(10),
  O_VT_START                DATE,
  O_VT_END                  DATE,
  O_TT_START                DATE,
  O_TT_END                  DATE,
  B_PER_SUBSCRIPTION        CHAR(1),
  ID_PAYER                  NUMBER(10),
  P_TT_START                DATE,
  P_TT_END                  DATE,
  P_VT_START                DATE,
  P_VT_END                  DATE,
  B_DT_START                DATE,
  B_DT_END                  DATE,
  B_ID_USAGE_INTERVAL       NUMBER(10),
  NB_DT_START               DATE,
  NB_DT_START_CORRECTED		DATE,				
  NB_DT_END                 DATE,
  NB_ID_USAGE_INTERVAL      NUMBER(10),
  ID_PI_INSTANCE            NUMBER(10),
  ID_PI_TEMPLATE            NUMBER(10),
  ID_PO                     NUMBER(10),
  S_DT_START                DATE,
  S_DT_END                  DATE,
  S_DT_END1                 DATE,
  B_ID_USAGE_CYCLE          NUMBER(10),
  RCI_ID_CYCLE              NUMBER(10),
  B_ADVANCE                 CHAR(1)   ,
  B_PRORATE_ON_ACTIVATE     CHAR(1)   ,
  B_PRORATE_INSTANTLY       CHAR(1)   ,
  B_PRORATE_ON_DEACTIVATE   CHAR(1)   ,
  B_FIXED_PRORATION_LENGTH  CHAR(1)   ,
  N_PRORATION_LENGTH        NUMBER(10),
  V_VALUE                   NUMBER(22,10),
  V_VT_START                DATE,
  V_VT_END                  DATE,
  V_TT_START                DATE,
  V_TT_END                  DATE,
  N_RATING_TYPE             NUMBER(10),
  RUN_ID_EVENT              NUMBER(10),
  RUN_VT_START              DATE,
  PREV_RUN_VT_START			DATE
)
ON COMMIT PRESERVE ROWS
