using System;
using System.Globalization;
using System.Text;
using MetraTech.ExpressionEngine.MTProperties;

namespace MetraTech.ExpressionEngine.Mvm
{
    public static class MvmHelper
    {

        public static void GetScriptGenerationHeader(StringBuilder sb, object objectGeneratingScript)
        {
            sb.AppendLine("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
            sb.AppendLine(GetComment(string.Format(CultureInfo.InvariantCulture, "Script Auto Generated by {0} on {1}", objectGeneratingScript.ToString(), DateTime.Now)));
            sb.AppendLine(GetStartTag("MVMScript"));
        }


        public static string GetAssigment(Property property, bool encasedInTag=false)
        {
            var content = string.Format(CultureInfo.InvariantCulture, "OBJECT.{0} = {1}", property.DatabaseName, property.CalculationExpression);
            if (encasedInTag)
                return string.Format(CultureInfo.InvariantCulture, "{0}{1}{2}", GetStartTag("Script"), content, GetEndTag("Script"));
            return content;
        }

        public static string GetComment(string content)
        {
            return string.Format(CultureInfo.InvariantCulture, "<!-- {0} -->", content);
        }

        public static string GetStartTag(string name)
        {
            return "<" + name + ">";
        }

        public static string GetEndTag(string name)
        {
            return "</" + name + ">";
        }
    }
}
