#define MT_USERDEFINE_DESCRIPTION "preauthlookup\0" 
#define MT_USERDEFINE_INTERNALNAME "preauthlookup\0" 
#define MT_USERDEFINEORIGFILENAME MT_USERDEFINE_INTERNALNAME 
#define MT_USERDEFINEPRODUCTNAME MT_USERDEFINE_DESCRIPTION 
#define MT_USERDEF_PROJECTNAME MT_USERDEFINE_DESCRIPTION 
#define IDS_PROJNAME 100
