#############################################################
#Generated on Thu Jul  1 11:24:30 1999
#############################################################


RELATIVEDIR := Core\dirwatch\test

SRC := test.cpp

INCLUDEDIRS := 

MIDL_INCLUDEDIRS := 

DEFINES := 

EXTRA_LIBS :=   dirwatch.lib err.lib error.lib mtsl.lib stdutil.lib

EXTRA_SYS_LIBS := 

EXENAME := DirWatchTest

OVERRIDE_UNICODE_CPP_FLAGS := 1
TEST_UTILITY = 1