CREATE GLOBAL TEMPORARY TABLE TMP_CHANGED_UNITS
(
    ID_PROP NUMBER(10, 0),
    ID_SUB NUMBER(10, 0),
    N_VALUE NUMBER(22, 10),
    VT_START DATE,
    VT_END DATE NOT NULL ENABLE,
    TT_START DATE NOT NULL ENABLE,
    TT_END DATE NOT NULL ENABLE
) ON COMMIT PRESERVE ROWS