
  CREATE GLOBAL TEMPORARY TABLE TMP_NEWRW
   (   C_CYCLEEFFECTIVEDATE DATE NOT NULL ENABLE, 
       C_CYCLEEFFECTIVESTART DATE NOT NULL ENABLE, 
       C_CYCLEEFFECTIVEEND DATE NOT NULL ENABLE, 
       C_SUBSCRIPTIONSTART DATE NOT NULL ENABLE, 
       C_SUBSCRIPTIONEND DATE NOT NULL ENABLE, 
       C_ADVANCE CHAR(1 BYTE) NOT NULL ENABLE, 
       C__ACCOUNTID NUMBER(10,0) NOT NULL ENABLE, 
       C__PAYINGACCOUNT NUMBER(10,0) NOT NULL ENABLE, 
       C__PRICEABLEITEMINSTANCEID NUMBER(10,0), 
       C__PRICEABLEITEMTEMPLATEID NUMBER(10,0), 
       C__PRODUCTOFFERINGID NUMBER(10,0), 
       C_PAYERSTART DATE NOT NULL ENABLE, 
       C_PAYEREND DATE NOT NULL ENABLE, 
       C__SUBSCRIPTIONID NUMBER(10,0) NOT NULL ENABLE, 
       C_UNITVALUESTART DATE, 
       C_UNITVALUEEND DATE, 
       C_UNITVALUE NUMBER(22,10), 
       C_BILLEDTHROUGHDATE DATE, 
       C_LASTIDRUN NUMBER, 
       C_MEMBERSHIPSTART DATE, 
       C_MEMBERSHIPEND DATE,
	   c__IsAllowGenChargeByTrigger SMALLINT,
	   c__QuoteBatchId raw(16) NULL
   ) ON COMMIT preserve ROWS 

