CREATE GLOBAL TEMPORARY TABLE tmp_backoutArrearsUsages (
  C__PRICEABLEITEMINSTANCEID NUMBER(10,0) NOT NULL ENABLE,
  C__PRICEABLEITEMTEMPLATEID NUMBER(10,0) NOT NULL ENABLE,
  C__SUBSCRIPTIONID NUMBER(10,0) NOT NULL ENABLE
) ON COMMIT PRESERVE ROWS
