nunit-console /fixture:MetraTech.Tax.UnitTests.ParamTable /assembly:o:\debug\bin\MetraTech.Tax.UnitTests.dll
nunit-console /fixture:MetraTech.Tax.UnitTests.OutputTableTests /assembly:o:\debug\bin\MetraTech.Tax.UnitTests.dll
nunit-console /fixture:MetraTech.Tax.UnitTests.InputTable /assembly:o:\debug\bin\MetraTech.Tax.UnitTests.dll
nunit-console /fixture:MetraTech.Tax.UnitTests.ProductMappingTest /assembly:o:\debug\bin\MetraTech.Tax.UnitTests.dll
nunit-console /fixture:MetraTech.Tax.UnitTests.ProductCodeMapperTest /assembly:o:\debug\bin\MetraTech.Tax.UnitTests.dll
nunit-console /fixture:MetraTech.Tax.UnitTests.BillSoftConfigurationTest /assembly:o:\debug\bin\MetraTech.Tax.UnitTests.dll
nunit-console /fixture:MetraTech.Tax.UnitTests.DetailTableTests /assembly:o:\debug\bin\MetraTech.Tax.UnitTests.dll
nunit-console /fixture:MetraTech.Tax.Framework.Test.VendorParamsManagerTests /assembly:O:\debug\bin\MetraTech.Tax.Framework.Test.dll
nunit-console /fixture:MetraTech.Tax.Taxware.Test.TaxwareTests /assembly:O:\debug\bin\MetraTech.Tax.Taxware.Test.dll
nunit-console /fixture:MetraTech.Tax.UnitTests.BillSoft /assembly:o:\debug\bin\MetraTech.Tax.UnitTests.dll
nunit-console /fixture:MetraTech.Tax.MetraTax.Test.MetraTaxTests /assembly:O:\debug\bin\MetraTech.Tax.MetraTax.Test.dll
nunit-console /fixture:MetraTech.Tax.Framework.Test.AssistantTests /assembly:O:\debug\bin\MetraTech.Tax.Framework.Test.dll
nunit-console /fixture:MetraTech.Tax.Framework.Test.FrameworkTests /assembly:O:\debug\bin\MetraTech.Tax.Framework.Test.dll
mstest /testcontainer:o:\debug\bin\VertexSocketConsoleTest.dll /detail:testtype