VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "RecurringChargeCycle"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Attribute VB_Ext_KEY = "SavedWithClassBuilder6" ,"Yes"
Attribute VB_Ext_KEY = "Top_Level" ,"Yes"
' Object: RecurringChargeCycle
' Description: Configuration of a recurring charge cycle

Option Explicit

' --- public properties ----------------------------------------------------

Public CycleType As Integer


' --- internal properties ----------------------------------------------------

' --- public methods ----------------------------------------------------



' --- internal methods ----------------------------------------------------


