
CXXAPPNAME = errortest

CXXOBJECTS = errortest.o

LIBLIST += errobj sdk_msg 
OTHERLIBS += std15s 

default: directories app

include $(BUILD_ROOT)/Build/unix/base.mak

include $(BUILD_ROOT)/Build/unix/app.mak
