//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetraTech.Agreements.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AgreementTemplateModels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AgreementTemplateModels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MetraTech.Agreements.Properties.AgreementTemplateModels", typeof(AgreementTemplateModels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string AgreementTemplateDescriptionModel_AgreementTemplateDescriptionDisplayNames {
            get {
                return ResourceManager.GetString("AgreementTemplateDescriptionModel_AgreementTemplateDescriptionDisplayNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string AgreementTemplateDescriptionModel_AgreementTemplateNameDisplayNames {
            get {
                return ResourceManager.GetString("AgreementTemplateDescriptionModel_AgreementTemplateNameDisplayNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Description.
        /// </summary>
        public static string AgreementTemplateDescriptionModel_ErrorDescription {
            get {
                return ResourceManager.GetString("AgreementTemplateDescriptionModel_ErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Desc ID.
        /// </summary>
        public static string AgreementTemplateModel_AgreementTemplateDescId {
            get {
                return ResourceManager.GetString("AgreementTemplateModel_AgreementTemplateDescId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string AgreementTemplateModel_AgreementTemplateDescription {
            get {
                return ResourceManager.GetString("AgreementTemplateModel_AgreementTemplateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the description for the agreement template..
        /// </summary>
        public static string AgreementTemplateModel_AgreementTemplateDescriptionPrompt {
            get {
                return ResourceManager.GetString("AgreementTemplateModel_AgreementTemplateDescriptionPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement Template ID.
        /// </summary>
        public static string AgreementTemplateModel_AgreementTemplateId {
            get {
                return ResourceManager.GetString("AgreementTemplateModel_AgreementTemplateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Name:.
        /// </summary>
        public static string AgreementTemplateModel_AgreementTemplateName {
            get {
                return ResourceManager.GetString("AgreementTemplateModel_AgreementTemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name ID.
        /// </summary>
        public static string AgreementTemplateModel_AgreementTemplateNameId {
            get {
                return ResourceManager.GetString("AgreementTemplateModel_AgreementTemplateNameId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of the agreement template..
        /// </summary>
        public static string AgreementTemplateModel_AgreementTemplateNamePrompt {
            get {
                return ResourceManager.GetString("AgreementTemplateModel_AgreementTemplateNamePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available End Date.
        /// </summary>
        public static string AgreementTemplateModel_AvailableEndDate {
            get {
                return ResourceManager.GetString("AgreementTemplateModel_AvailableEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Start Date.
        /// </summary>
        public static string AgreementTemplateModel_AvailableStartDate {
            get {
                return ResourceManager.GetString("AgreementTemplateModel_AvailableStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By:.
        /// </summary>
        public static string AgreementTemplateModel_CreatedBy {
            get {
                return ResourceManager.GetString("AgreementTemplateModel_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date:.
        /// </summary>
        public static string AgreementTemplateModel_CreatedDate {
            get {
                return ResourceManager.GetString("AgreementTemplateModel_CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective End Date.
        /// </summary>
        public static string AgreementTemplateModel_EffectiveEndDate {
            get {
                return ResourceManager.GetString("AgreementTemplateModel_EffectiveEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective Start Date.
        /// </summary>
        public static string AgreementTemplateModel_EffectiveStartDate {
            get {
                return ResourceManager.GetString("AgreementTemplateModel_EffectiveStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Description.
        /// </summary>
        public static string AgreementTemplateModel_ErrorDescription {
            get {
                return ResourceManager.GetString("AgreementTemplateModel_ErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapped Entities.
        /// </summary>
        public static string AgreementTemplateModel_MappedEntities {
            get {
                return ResourceManager.GetString("AgreementTemplateModel_MappedEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string AgreementTemplateModel_Status {
            get {
                return ResourceManager.GetString("AgreementTemplateModel_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated By:.
        /// </summary>
        public static string AgreementTemplateModel_UpdatedBy {
            get {
                return ResourceManager.GetString("AgreementTemplateModel_UpdatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated:.
        /// </summary>
        public static string AgreementTemplateModel_UpdatedDate {
            get {
                return ResourceManager.GetString("AgreementTemplateModel_UpdatedDate", resourceCulture);
            }
        }
    }
}
