
RELATIVEDIR := \MetraTech\Auth\Capabilities\Test

SRC :=  

ASSEMBLIES := \
	nunit.framework.dll \
	MTAuth.interop.dll \
	MetraTech.Test.dll \
	MTServerAccess.interop.dll \
	MTYAAC.interop.dll \
	MetraTech.Auth.Capabilities.dll \
	GenericCollection.interop.dll \
	MetraTech.Localization.dll \
	MetraTime.interop.dll \
	MetraTech.Common.dll \

SYSTEM_ASSEMBLIES :=

DEFINES := 

CSHARPDLL := MetraTech.Capabilities.Test

REGISTER_COMINTEROP := 0
SIGN_WITH_METRATECH_KEY := 1
