//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MTProductCatalogExec.rc
//
#define IDS_PROJNAME                    100
#define IDR_MTPRODUCTOFFERINGREADER     101
#define IDR_MTPRODUCTOFFERINGWRITER     102
#define IDR_MTPRICEABLEITEMREADER       103
#define IDR_MTCOUNTERTYPEREADER         104
#define IDR_MTCOUNTERREADER             105
#define IDR_MTCOUNTERWRITER             106
#define IDR_MTCOUNTERPARAMREADER        107
#define IDR_MTPARAMTABLEDEFINITIONREADER 108
#define IDR_MTPCTIMESPANWRITER          109
#define IDR_MTPRICEABLEITEMTYPEREADER   110
#define IDR_MTPRICEABLEITEMTYPEWRITER   111
#define IDR_MTRATESCHEDULEWRITER        112
#define IDR_MTRULESETWRITER             113
#define IDR_MTPRICEABLEITEMWRITER       114
#define IDR_MTRATESCHEDULEREADER        115
#define IDR_MTRULESETREADER             117
#define IDR_MTPRICELISTREADER           118
#define IDR_MTPRICELISTWRITER           119
#define IDR_MTDISCOUNTREADER            120
#define IDR_MTDISCOUNTWRITER            121
#define IDR_MTACCOUNTREADER             122
#define IDR_MTACCOUNTWRITER             123
#define IDR_MTCOUNTERVIEWREADER         124
#define IDR_MTPRICELISTMAPPINGREADER    125
#define IDR_MTSUBSCRIPTIONREADER        126
#define IDR_MTSUBSCRIPTIONWRITER        127
#define IDR_MTPROPERTYMETADATASETREADER 128
#define IDR_MTNONRECURRINGCHARGEREADER  129
#define IDR_MTNONRECURRINGCHARGEWRITER  130
#define IDR_MTPRICELISTMAPPINGWRITER    131
#define IDR_MTCOUNTERPROPERTYDEFINITIONREADER 132
#define IDR_MTCOUNTERPROPERTYDEFINITIONWRITER 134
#define IDR_MTATTRIBUTEMETADATASETREADER 135
#define IDR_MTRECURRINGCHARGEREADER     136
#define IDR_MTRECURRINGCHARGEWRITER     137
#define IDR_MTCOUNTERMAPREADER          138
#define IDR_MTCOUNTERMAPWRITER          139
#define IDR_MTCOUNTERTYPEWRITER         140
#define IDR_MTBASEPROPSWRITER           141
#define IDR_MTAGGREGATECHARGEREADER     142
#define IDR_MTAGGREGATECHARGEWRITER     143
#define IDR_MTEXTENDEDPROPWRITER        144
#define IDR_MTCALENDARREADER            145
#define IDR_MTCALENDARWRITER            146
#define IDR_MTPARAMTABLEDEFINITIONWRITER 147
#define IDR_MTDDLWRITER                 148
#define IDR_MTPRODUCTVIEWWRITER         149
#define IDR_MTCHARGEREADER              150
#define IDR_MTCHARGEWRITER              151
#define IDR_MTPREDICATEWRITER           153
#define IDR_MTCHARGEPROPERTYWRITER      154
#define IDR_MTCHARGEPROPERTYREADER      155
#define IDR_MTCOUNTERPARAMWRITER        156

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        201
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         201
#define _APS_NEXT_SYMED_VALUE           158
#endif
#endif
