#define MT_USERDEFINE_DESCRIPTION "AudioConfMeteringTestApp\0" 
#define MT_USERDEFINE_INTERNALNAME "AudioConfMeteringTestApp\0" 
#define MT_USERDEFINEORIGFILENAME MT_USERDEFINE_INTERNALNAME 
#define MT_USERDEFINEPRODUCTNAME MT_USERDEFINE_DESCRIPTION 
#define MT_USERDEF_PROJECTNAME MT_USERDEFINE_DESCRIPTION 

#ifndef MT_FILEVERSION
  #define MT_FILEVERSION 1,0,0,1
#endif

#ifndef MT_PRODUCTVERSION
#define MT_PRODUCTVERSION 1,0,0,1
#endif

#ifndef MT_COMPANYNAME_STR
#define MT_COMPANYNAME_STR 
#endif

#ifndef MT_FILEVERSION_STR
#define MT_FILEVERSION_STR
#endif

#ifndef MT_COPYRIGHT_STR
#define MT_COPYRIGHT_STR
#endif

#ifndef MT_PRODUCTVERSION_STR
#define MT_PRODUCTVERSION_STR
#endif

#ifndef IDS_PROJNAME
#define IDS_PROJNAME 100 
#endif
