#define MT_USERDEFINE_DESCRIPTION "Generic SQL Insert plugin\0"
#define MT_USERDEFINE_INTERNALNAME "GenericInsert\0"
#define MT_USERDEFINEORIGFILENAME MT_USERDEFINE_INTERNALNAME
#define MT_USERDEFINEPRODUCTNAME MT_USERDEFINE_DESCRIPTION
#define IDS_PROJNAME 100
#define MT_USERDEF_PROJECTNAME MT_USERDEFINE_DESCRIPTION
