#############################################################
#Generated on Thu Jul  1 11:24:24 1999
#############################################################


RELATIVEDIR := AccountHierarchies\BatchHierarchy

SRC := BatchHierarchy.cpp

INCLUDEDIRS := $(SRCROOT)\Core\DataAccess\MTODBC 

MIDL_INCLUDEDIRS := 

DEFINES := 
EXTRA_LIBS :=   

EXTRA_SYS_LIBS := 

SLIBNAME := BatchHierarchy

OVERRIDE_UNICODE_CPP_FLAGS := 1


TEST_UTILITY := 1