//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.FileLandingService
{
  using System;
  using System.Collections.Generic;
  using System.Collections.ObjectModel;
  using System.Runtime.Serialization;
  using System.Linq;
  using MetraTech.Basic;
  using MetraTech.BusinessEntity.Core;
  using MetraTech.BusinessEntity.Core.Model;
  using MetraTech.BusinessEntity.DataAccess.Metadata;
  using MetraTech.BusinessEntity.DataAccess.Persistence;
  
  
  [System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
  [System.SerializableAttribute()]
  [System.Runtime.Serialization.KnownTypeAttribute("GetKnownTypes")]
  [MetraTech.BusinessEntity.Core.Model.ConfigDrivenAttribute()]
  public partial class ConfigurationBE : MetraTech.BusinessEntity.DataAccess.Metadata.DataObject, global::Core.FileLandingService.Interface.IConfigurationBE
  {
    
    public const string FullName = "Core.FileLandingService.ConfigurationBE";
    
    private int @__Version;
    
    public const string Property__Version = "_Version";
    
    private System.Nullable<System.DateTime> _creationDate;
    
    public const string Property_CreationDate = "CreationDate";
    
    private System.Nullable<System.DateTime> _updateDate;
    
    public const string Property_UpdateDate = "UpdateDate";
    
    private System.Nullable<System.Int32> _uID;
    
    public const string Property_UID = "UID";
    
    public const string Property_Id = "Id";
    
    private global::Core.FileLandingService.ConfigurationBEBusinessKey _configurationBEBusinessKey = new ConfigurationBEBusinessKey();
    
    private bool @__UseToken = false;
    
    public const string Property__UseToken = "_UseToken";
    
    private bool @__UseSHA1 = false;
    
    public const string Property__UseSHA1 = "_UseSHA1";
    
    private bool @__UseMD5 = false;
    
    public const string Property__UseMD5 = "_UseMD5";
    
    private int @__MaximumActiveTargets = 5;
    
    public const string Property__MaximumActiveTargets = "_MaximumActiveTargets";
    
    private string @__CompletedDirectory;
    
    public const string Property__CompletedDirectory = "_CompletedDirectory";
    
    private string @__ActiveDirectory;
    
    public const string Property__ActiveDirectory = "_ActiveDirectory";
    
    private int @__ConfRefreshIntervalInMS = 10000;
    
    public const string Property__ConfRefreshIntervalInMS = "_ConfRefreshIntervalInMS";
    
    private bool @__UseDescriptorFile = false;
    
    public const string Property__UseDescriptorFile = "_UseDescriptorFile";
    
    private string @__FailedDirectory;
    
    public const string Property__FailedDirectory = "_FailedDirectory";
    
    private string @__IncomingDirectory;
    
    public const string Property__IncomingDirectory = "_IncomingDirectory";
    
    public const string Property_InternalKey = "InternalKey";
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public override int _Version
    {
      get
      {
        return this.@__Version;
      }
      set
      {
        this.@__Version = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public override System.Nullable<System.DateTime> CreationDate
    {
      get
      {
        return this._creationDate;
      }
      set
      {
        this._creationDate = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public override System.Nullable<System.DateTime> UpdateDate
    {
      get
      {
        return this._updateDate;
      }
      set
      {
        this._updateDate = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual System.Nullable<System.Int32> UID
    {
      get
      {
        return this._uID;
      }
      set
      {
        this._uID = value;
      }
    }
    
    [MetraTech.BusinessEntity.DataAccess.Metadata.BusinessKeyAttribute()]
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual global::Core.FileLandingService.ConfigurationBEBusinessKey ConfigurationBEBusinessKey
    {
      get
      {
        return this._configurationBEBusinessKey;
      }
      set
      {
        this._configurationBEBusinessKey = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual bool _UseToken
    {
      get
      {
        return this.@__UseToken;
      }
      set
      {
        this.@__UseToken = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual bool _UseSHA1
    {
      get
      {
        return this.@__UseSHA1;
      }
      set
      {
        this.@__UseSHA1 = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual bool _UseMD5
    {
      get
      {
        return this.@__UseMD5;
      }
      set
      {
        this.@__UseMD5 = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual int _MaximumActiveTargets
    {
      get
      {
        return this.@__MaximumActiveTargets;
      }
      set
      {
        this.@__MaximumActiveTargets = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual string _CompletedDirectory
    {
      get
      {
        return this.@__CompletedDirectory;
      }
      set
      {
        this.@__CompletedDirectory = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual string _ActiveDirectory
    {
      get
      {
        return this.@__ActiveDirectory;
      }
      set
      {
        this.@__ActiveDirectory = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual int _ConfRefreshIntervalInMS
    {
      get
      {
        return this.@__ConfRefreshIntervalInMS;
      }
      set
      {
        this.@__ConfRefreshIntervalInMS = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual bool _UseDescriptorFile
    {
      get
      {
        return this.@__UseDescriptorFile;
      }
      set
      {
        this.@__UseDescriptorFile = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual string _FailedDirectory
    {
      get
      {
        return this.@__FailedDirectory;
      }
      set
      {
        this.@__FailedDirectory = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual string _IncomingDirectory
    {
      get
      {
        return this.@__IncomingDirectory;
      }
      set
      {
        this.@__IncomingDirectory = value;
      }
    }
    
    public override void SetupRelationships()
    {
    }
    
    public virtual object Clone()
    {
      var _configurationBE = new global::Core.FileLandingService.ConfigurationBE();
      _configurationBE.ConfigurationBEBusinessKey = (global::Core.FileLandingService.ConfigurationBEBusinessKey)ConfigurationBEBusinessKey.Clone();
      _configurationBE._UseToken = _UseToken;
      _configurationBE._UseSHA1 = _UseSHA1;
      _configurationBE._UseMD5 = _UseMD5;
      _configurationBE._MaximumActiveTargets = _MaximumActiveTargets;
      _configurationBE._CompletedDirectory = _CompletedDirectory;
      _configurationBE._ActiveDirectory = _ActiveDirectory;
      _configurationBE._ConfRefreshIntervalInMS = _ConfRefreshIntervalInMS;
      _configurationBE._UseDescriptorFile = _UseDescriptorFile;
      _configurationBE._FailedDirectory = _FailedDirectory;
      _configurationBE._IncomingDirectory = _IncomingDirectory;
      return _configurationBE;
    }
    
    public virtual void Save()
    {
      var item = this;
      global::MetraTech.BusinessEntity.DataAccess.Persistence.StandardRepository.Instance.SaveInstance(ref item);
    }
    
    public override void CopyPropertiesFrom(global::MetraTech.BusinessEntity.DataAccess.Metadata.DataObject dataObject)
    {
      var item = dataObject as global::Core.FileLandingService.ConfigurationBE;
      _UseToken = item._UseToken;
      _UseSHA1 = item._UseSHA1;
      _UseMD5 = item._UseMD5;
      _MaximumActiveTargets = item._MaximumActiveTargets;
      _CompletedDirectory = item._CompletedDirectory;
      _ActiveDirectory = item._ActiveDirectory;
      _ConfRefreshIntervalInMS = item._ConfRefreshIntervalInMS;
      _UseDescriptorFile = item._UseDescriptorFile;
      _FailedDirectory = item._FailedDirectory;
      _IncomingDirectory = item._IncomingDirectory;
      ConfigurationBEBusinessKey = item.ConfigurationBEBusinessKey;
    }
    
    public static new System.Type[] GetKnownTypes()
    {
      var knownTypes = new List<System.Type>();
      knownTypes.Add(typeof(global::Core.FileLandingService.ConfigurationBEBusinessKey));
      return knownTypes.ToArray();
    }
  }
  
  [System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
  [System.SerializableAttribute()]
  public partial class ConfigurationBEBusinessKey : MetraTech.BusinessEntity.DataAccess.Metadata.BusinessKey, global::Core.FileLandingService.Interface.IConfigurationBEBusinessKey
  {
    
    private string _entityFullName = "Core.FileLandingService.ConfigurationBE";
    
    private System.Guid _internalKey;
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public override string EntityFullName
    {
      get
      {
        return this._entityFullName;
      }
      set
      {
        this._entityFullName = "Core.FileLandingService.ConfigurationBE";
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual System.Guid InternalKey
    {
      get
      {
        return this._internalKey;
      }
      set
      {
        this._internalKey = value;
      }
    }
    
    public override object Clone()
    {
      var _businessKey = new ConfigurationBEBusinessKey();
      _businessKey.InternalKey = InternalKey;
      return _businessKey;
    }
  }
}
