//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.FileLandingService
{
  using System;
  using System.Collections.Generic;
  using System.Collections.ObjectModel;
  using System.Runtime.Serialization;
  using System.Linq;
  using MetraTech.Basic;
  using MetraTech.BusinessEntity.Core;
  using MetraTech.BusinessEntity.Core.Model;
  using MetraTech.BusinessEntity.DataAccess.Metadata;
  using MetraTech.BusinessEntity.DataAccess.Persistence;
  
  
  [System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
  [System.SerializableAttribute()]
  [System.Runtime.Serialization.KnownTypeAttribute("GetKnownTypes")]
  [MetraTech.BusinessEntity.Core.Model.ConfigDrivenAttribute()]
  public partial class InvocationRecordBE : MetraTech.BusinessEntity.DataAccess.Metadata.DataObject, global::Core.FileLandingService.Interface.IInvocationRecordBE, MetraTech.BusinessEntity.DataAccess.Persistence.IRecordHistory
  {
    
    public const string FullName = "Core.FileLandingService.InvocationRecordBE";
    
    private int @__Version;
    
    public const string Property__Version = "_Version";
    
    private System.Nullable<System.DateTime> _creationDate;
    
    public const string Property_CreationDate = "CreationDate";
    
    private System.Nullable<System.DateTime> _updateDate;
    
    public const string Property_UpdateDate = "UpdateDate";
    
    private System.Nullable<System.Int32> _uID;
    
    public const string Property_UID = "UID";
    
    public const string Property_Id = "Id";
    
    private global::Core.FileLandingService.InvocationRecordBEBusinessKey _invocationRecordBEBusinessKey = new InvocationRecordBEBusinessKey();
    
    private string @__Command;
    
    public const string Property__Command = "_Command";
    
    private long @__ErrorCode = 0;
    
    public const string Property__ErrorCode = "_ErrorCode";
    
    private MetraTech.DomainModel.Enums.Core.Metratech_com_FileLandingService.EInvocationState @__State = MetraTech.DomainModel.Enums.Core.Metratech_com_FileLandingService.EInvocationState.UNKNOWN;
    
    public const string Property__State = "_State";
    
    private string @__ControlNumber;
    
    public const string Property__ControlNumber = "_ControlNumber";
    
    private System.DateTime @__DateTime = DateTime.Parse("7/14/2006 4:20:06 AM");
    
    public const string Property__DateTime = "_DateTime";
    
    private string @__BatchId;
    
    public const string Property__BatchId = "_BatchId";
    
    private string @__TrackingId;
    
    public const string Property__TrackingId = "_TrackingId";
    
    private IList<global::Core.FileLandingService.Interface.IFileBE> _fileBEs = new List<global::Core.FileLandingService.Interface.IFileBE>();
    
    private IList<global::Core.FileLandingService.Interface.IInvocationRecordBE_FileBE> _invocationRecordBE_FileBEList = new List<global::Core.FileLandingService.Interface.IInvocationRecordBE_FileBE>();
    
    private global::Core.FileLandingService.Interface.ITargetBE _targetBE;
    
    private IList<global::Core.FileLandingService.Interface.ITargetBE_InvocationRecordBE> _targetBE_InvocationRecordBEList = new List<global::Core.FileLandingService.Interface.ITargetBE_InvocationRecordBE>();
    
    public const string Relationship_InvocationRecordBE_FileBE = "InvocationRecordBE_FileBE";
    
    public const string Relationship_TargetBE_InvocationRecordBE = "TargetBE_InvocationRecordBE";
    
    public const string Property_InternalKey = "InternalKey";
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public override int _Version
    {
      get
      {
        return this.@__Version;
      }
      set
      {
        this.@__Version = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public override System.Nullable<System.DateTime> CreationDate
    {
      get
      {
        return this._creationDate;
      }
      set
      {
        this._creationDate = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public override System.Nullable<System.DateTime> UpdateDate
    {
      get
      {
        return this._updateDate;
      }
      set
      {
        this._updateDate = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual System.Nullable<System.Int32> UID
    {
      get
      {
        return this._uID;
      }
      set
      {
        this._uID = value;
      }
    }
    
    [MetraTech.BusinessEntity.DataAccess.Metadata.BusinessKeyAttribute()]
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual global::Core.FileLandingService.InvocationRecordBEBusinessKey InvocationRecordBEBusinessKey
    {
      get
      {
        return this._invocationRecordBEBusinessKey;
      }
      set
      {
        this._invocationRecordBEBusinessKey = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual string _Command
    {
      get
      {
        return this.@__Command;
      }
      set
      {
        this.@__Command = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual long _ErrorCode
    {
      get
      {
        return this.@__ErrorCode;
      }
      set
      {
        this.@__ErrorCode = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual MetraTech.DomainModel.Enums.Core.Metratech_com_FileLandingService.EInvocationState _State
    {
      get
      {
        return this.@__State;
      }
      set
      {
        this.@__State = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual string _ControlNumber
    {
      get
      {
        return this.@__ControlNumber;
      }
      set
      {
        this.@__ControlNumber = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual System.DateTime _DateTime
    {
      get
      {
        return this.@__DateTime;
      }
      set
      {
        this.@__DateTime = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual string _BatchId
    {
      get
      {
        return this.@__BatchId;
      }
      set
      {
        this.@__BatchId = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual string _TrackingId
    {
      get
      {
        return this.@__TrackingId;
      }
      set
      {
        this.@__TrackingId = value;
      }
    }
    
    public virtual List<global::Core.FileLandingService.Interface.IFileBE> FileBEs
    {
      get
      {
        return _fileBEs as List<global::Core.FileLandingService.Interface.IFileBE>;
      }
      set
      {
        this._fileBEs = value;
      }
    }
    
    public virtual IList<global::Core.FileLandingService.Interface.IInvocationRecordBE_FileBE> InvocationRecordBE_FileBEList
    {
      get
      {
        return this._invocationRecordBE_FileBEList;
      }
      set
      {
        this._invocationRecordBE_FileBEList = value;
      }
    }
    
    public virtual global::Core.FileLandingService.Interface.ITargetBE TargetBE
    {
      get
      {
        return this._targetBE;
      }
      set
      {
        this._targetBE = value;
      }
    }
    
    public virtual IList<global::Core.FileLandingService.Interface.ITargetBE_InvocationRecordBE> TargetBE_InvocationRecordBEList
    {
      get
      {
        return this._targetBE_InvocationRecordBEList;
      }
      set
      {
        this._targetBE_InvocationRecordBEList = value;
      }
    }
    
    public virtual MetraTech.BusinessEntity.DataAccess.Persistence.BaseHistory GetHistoryObject()
    {
      var _invocationRecordBEHistory = new global::Core.FileLandingService.InvocationRecordBEHistory();
      _invocationRecordBEHistory.Id = Id;
      _invocationRecordBEHistory._Version = _Version;
      _invocationRecordBEHistory.InvocationRecordBEBusinessKey = InvocationRecordBEBusinessKey;
      _invocationRecordBEHistory._Command = _Command;
      _invocationRecordBEHistory._ErrorCode = _ErrorCode;
      _invocationRecordBEHistory._State = _State;
      _invocationRecordBEHistory._ControlNumber = _ControlNumber;
      _invocationRecordBEHistory._DateTime = _DateTime;
      _invocationRecordBEHistory._BatchId = _BatchId;
      _invocationRecordBEHistory._TrackingId = _TrackingId;
      return _invocationRecordBEHistory;
    }
    
    public override void SetupRelationships()
    {
    }
    
    public virtual object Clone()
    {
      var _invocationRecordBE = new global::Core.FileLandingService.InvocationRecordBE();
      _invocationRecordBE.InvocationRecordBEBusinessKey = (global::Core.FileLandingService.InvocationRecordBEBusinessKey)InvocationRecordBEBusinessKey.Clone();
      _invocationRecordBE._Command = _Command;
      _invocationRecordBE._ErrorCode = _ErrorCode;
      _invocationRecordBE._State = _State;
      _invocationRecordBE._ControlNumber = _ControlNumber;
      _invocationRecordBE._DateTime = _DateTime;
      _invocationRecordBE._BatchId = _BatchId;
      _invocationRecordBE._TrackingId = _TrackingId;
      return _invocationRecordBE;
    }
    
    public virtual void Save()
    {
      var item = this;
      global::MetraTech.BusinessEntity.DataAccess.Persistence.StandardRepository.Instance.SaveInstance(ref item);
    }
    
    public override void CopyPropertiesFrom(global::MetraTech.BusinessEntity.DataAccess.Metadata.DataObject dataObject)
    {
      var item = dataObject as global::Core.FileLandingService.InvocationRecordBE;
      _Command = item._Command;
      _ErrorCode = item._ErrorCode;
      _State = item._State;
      _ControlNumber = item._ControlNumber;
      _DateTime = item._DateTime;
      _BatchId = item._BatchId;
      _TrackingId = item._TrackingId;
      InvocationRecordBEBusinessKey = item.InvocationRecordBEBusinessKey;
    }
    
    public static new System.Type[] GetKnownTypes()
    {
      var knownTypes = new List<System.Type>();
      knownTypes.Add(typeof(MetraTech.DomainModel.Enums.Core.Metratech_com_FileLandingService.EInvocationState));
      knownTypes.Add(typeof(global::Core.FileLandingService.InvocationRecordBEBusinessKey));
      return knownTypes.ToArray();
    }
  }
  
  [System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
  [System.SerializableAttribute()]
  public partial class InvocationRecordBEBusinessKey : MetraTech.BusinessEntity.DataAccess.Metadata.BusinessKey, global::Core.FileLandingService.Interface.IInvocationRecordBEBusinessKey
  {
    
    private string _entityFullName = "Core.FileLandingService.InvocationRecordBE";
    
    private System.Guid _internalKey;
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public override string EntityFullName
    {
      get
      {
        return this._entityFullName;
      }
      set
      {
        this._entityFullName = "Core.FileLandingService.InvocationRecordBE";
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual System.Guid InternalKey
    {
      get
      {
        return this._internalKey;
      }
      set
      {
        this._internalKey = value;
      }
    }
    
    public override object Clone()
    {
      var _businessKey = new InvocationRecordBEBusinessKey();
      _businessKey.InternalKey = InternalKey;
      return _businessKey;
    }
  }
}
