using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using MetraTech.Interop.MTAuditEvents;

namespace MetraTech.ActivityServices.Services.Common
{
    public class AuditManager
    {
        #region Private Members
        private static Auditor mAuditor = new Auditor();

        #endregion

        #region Public Static Methods
        public static int FireEventAdditionalData(int eventID, int userID, int entityTypeID, int entityID, string details, string loggedInAs, string applicationName)
        {
            AuditEventHandler handler = new AuditEventHandler();

            AuditEvent auditEvent = new AuditEvent();
            auditEvent.EventId          = eventID;
            auditEvent.UserId           = userID;
            auditEvent.EntityTypeId     = entityTypeID;
            auditEvent.EntityId         = entityID;
            auditEvent.Details          = details;
            auditEvent.Success          = true;
            auditEvent.LoggedInAs       = loggedInAs;
            auditEvent.ApplicationName  = applicationName;

            handler.HandleEvent(auditEvent);

            return auditEvent.AuditId;
        }

        public static void FireFailureEvent(int eventID, int userID, int entityTypeID, int entityID, string details)
        {
            mAuditor.FireFailureEvent(eventID, userID, entityTypeID, entityID, details);
        }

        public static void FireFailureEventWithAdditionalData(int eventID, int userID, int entityTypeID, int entityID, string details, string loggedInAs, string applicationName)
        {
            mAuditor.FireFailureEventWithAdditionalData(eventID, userID, entityTypeID, entityID, details, loggedInAs, applicationName);
        }

        public static int FireEvent(int eventID, int userID, int entityTypeID, int entityID, string details)
        {
          return FireEventAdditionalData(eventID, userID, entityTypeID, entityID, details, null, null);
        }

      #endregion
        #region Enums
        public enum MTAuditEntityType
        {
            AUDITENTITY_TYPE_NONE = 0,
            AUDITENTITY_TYPE_ACCOUNT = 1,
            AUDITENTITY_TYPE_PRODCAT = 2,
            AUDITENTITY_TYPE_GROUPSUB = 3,
            AUDITENTITY_TYPE_ROLE = 4,
            AUDITENTITY_TYPE_FAILEDTRANSACTION = 5,
            AUDITENTITY_TYPE_BATCH = 6,
            AUDITENTITY_TYPE_BILLINGRERUN = 7,
            AUDITENTITY_TYPE_LOGIN = 8,
            AUDITENTITY_TYPE_PAYMENT = 9,
            AUDITENTITY_TYPE_APPROVAL = 10,
            AUDITENTITY_TYPE_AGREEMENT = 11
        };

        public enum MTAuditEvents
        {
            AUDITEVENT_UNKNOWN = 0,
            AUDITEVENT_OTHER = 1,
            AUDITEVENT_PO_CREATE = 1100,
            AUDITEVENT_PO_CREATE_DENIED = 11100,
            AUDITEVENT_PO_UPDATE = 1101,
            AUDITEVENT_PO_UPDATE_DENIED = 11101,
            AUDITEVENT_PO_ADDPI = 1102,
            AUDITEVENT_PO_ADDPI_DENIED = 11102,
            AUDITEVENT_PO_DELETEPI = 1103,
            AUDITEVENT_PO_DELETEPI_DENIED = 11103,
            AUDITEVENT_PO_UPDATEPI = 1104,
            AUDITEVENT_PO_UPDATEPI_DENIED = 11104,
            AUDITEVENT_PO_UPDATEPLM = 1105,
            AUDITEVENT_PO_UPDATEPLM_DENIED = 11105,
            AUDITEVENT_PO_DELETE = 1106,
            AUDITEVENT_PO_DELETE_DENIED = 11106,
            AUDITEVENT_TEMPLATE_CREATE = 1200,
            AUDITEVENT_TEMPLATE_CREATE_DENIED = 11200,
            AUDITEVENT_TEMPLATE_UPDATE = 1201,
            AUDITEVENT_TEMPLATE_UPDATE_DENIED = 11201,
            AUDITEVENT_TEMPLATE_DELETE = 1202,
            AUDITEVENT_TEMPLATE_DELETE_DENIED = 11202,
            AUDITEVENT_PL_CREATE = 1300,
            AUDITEVENT_PL_CREATE_DENIED = 11300,
            AUDITEVENT_PL_UPDATE = 1301,
            AUDITEVENT_PL_UPDATE_DENIED = 11301,
            AUDITEVENT_PL_DELETE = 1302,
            AUDITEVENT_PL_DELETE_DENIED = 11302,
            AUDITEVENT_RS_CREATE = 1400,
            AUDITEVENT_RS_CREATE_DENIED = 11400,
            AUDITEVENT_RS_UPDATE = 1401,
            AUDITEVENT_RS_UPDATE_DENIED = 11401,
            AUDITEVENT_RS_RULE_UPDATE = 1402,
            AUDITEVENT_RS_RULE_UPDATE_DENIED = 11402,
            AUDITEVENT_RS_DELETE = 1403,
            AUDITEVENT_RS_DELETE_DENIED = 11403,
            AUDITEVENT_ICB_CREATE = 1450,
            AUDITEVENT_ICB_CREATE_DENIED = 11450,
            AUDITEVENT_ICB_UPDATE = 1451,
            AUDITEVENT_ICB_UPDATE_DENIED = 11451,
            AUDITEVENT_ICB_REMOVE = 1452,
            AUDITEVENT_ICB_REMOVE_DENIED = 11452,
            AUDITEVENT_GROUP_ICB_CREATE = 1453,
            AUDITEVENT_GROUP_ICB_CREATE_DENIED = 11453,
            AUDITEVENT_GROUP_ICB_UPDATE = 1454,
            AUDITEVENT_GROUP_ICB_UPDATE_DENIED = 11454,
            AUDITEVENT_GROUP_ICB_REMOVE = 1455,
            AUDITEVENT_GROUP_ICB_REMOVE_DENIED = 11455,
            AUDITEVENT_SUB_BULK = 1500,
            AUDITEVENT_SUB_BULK_DENIED = 11500,
            AUDITEVENT_SUB_CREATE = 1501,
            AUDITEVENT_SUB_CREATE_DENIED = 11501,
            AUDITEVENT_SUB_UPDATE = 1502,
            AUDITEVENT_SUB_UPDATE_DENIED = 11502,
            AUDITEVENT_SUB_UNSUBSCRIBE = 1503,
            AUDITEVENT_SUB_UNSUBSCRIBE_DENIED = 11503,
            AUDITEVENT_SUB_DELETE = 1504,
            AUDITEVENT_SUB_DELETE_DENIED = 11504,
            AUDITEVENT_GSUB_CREATE = 1505,
            AUDITEVENT_GSUB_CREATE_DENIED = 11505,
            AUDITEVENT_GSUB_UPDATE = 1506,
            AUDITEVENT_GSUB_UPDATE_DENIED = 11506,
            AUDITEVENT_GSUB_MEMBER_ADD = 1507,
            AUDITEVENT_GSUB_MEMBER_ADD_DENIED = 11507,
            AUDITEVENT_GSUB_MEMBER_UPDATE = 1508,
            AUDITEVENT_GSUB_MEMBER_UPDATE_DENIED = 11508,
            AUDITEVENT_GSUB_MEMBER_DELETE = 1509,
            AUDITEVENT_GSUB_MEMBER_DELETE_DENIED = 11509,
            AUDITEVENT_GSUB_MEMBER_UNSUBSCRIBE = 1513,
            AUDITEVENT_GSUB_MEMBER_UNSUBSCRIBE_DENIED = 11513,
            AUDITEVENT_ACCOUNT_CREDIT = 1510,
            AUDITEVENT_ACCOUNT_CREDIT_DENIED = 11510,
            AUDITEVENT_ADDITIONAL_CHARGE = 1511,
            AUDITEVENT_ADDITIONAL_CHARGE_DENIED = 11511,
            AUDITEVENT_ACCOUNT_CREDIT_TO_REQUEST = 1512,
            AUDITEVENT_ACCOUNT_CREATE = 1520,
            AUDITEVENT_ACCOUNT_CREATE_DENIED = 11520,
            AUDITEVENT_ACCOUNT_UPDATE = 1521,
            AUDITEVENT_ACCOUNT_UPDATE_DENIED = 11521,
            AUDITEVENT_CONTACT_CREATE = 1525,
            AUDITEVENT_CONTACT_CREATE_DENIED = 11525,
            AUDITEVENT_CONTACT_UPDATE = 1526,
            AUDITEVENT_CONTACT_UPDATE_DENIED = 11526,
            AUDITEVENT_ACCOUNT_MAPPING_CREATE = 1530,
            AUDITEVENT_ACCOUNT_MAPPING_CREATE_DENIED = 11530,
            AUDITEVENT_ACCOUNT_MAPPING_UPDATE = 1531,
            AUDITEVENT_ACCOUNT_MAPPING_UPDATE_DENIED = 11531,
            AUDITEVENT_ACCOUNT_MAPPING_DELETE = 1532,
            AUDITEVENT_ACCOUNT_MAPPING_DELETE_DENIED = 11532,
            AUDITEVENT_ROLE_CREATE = 1600,
            AUDITEVENT_ROLE_CREATE_DENIED = 11600,
            AUDITEVENT_ROLE_UPDATE = 1601,
            AUDITEVENT_ROLE_UPDATE_DENIED = 11601,
            AUDITEVENT_ROLE_DELETE = 1602,
            AUDITEVENT_ROLE_DELETE_DENIED = 11602,
            AUDITEVENT_SUBAUTH_UPDATE = 1610,
            AUDITEVENT_SUBAUTH_UPDATE_DENIED = 11610,
            AUDITEVENT_CSRAUTH_UPDATE = 1611,
            AUDITEVENT_CSRAUTH_UPDATE_DENIED = 11611,
            AUDITEVENT_SELF_SUB = 1612,
            AUDITEVENT_SELF_SUB_DENIED = 11612,
            AUDITEVENT_SELF_SUB_UNSUBSCRIBE = 1613,
            AUDITEVENT_BATCH_CREATED = 1750,
            AUDITEVENT_BATCH_MARK_AS_ACTIVE = 1751,
            AUDITEVENT_BATCH_MARK_AS_FAILED = 1752,
            AUDITEVENT_BATCH_MARK_AS_BACKOUT = 1753,
            // not really used -- 1754.  there as a placeholder
            AUDITEVENT_BATCH_MARK_AS_RESUBMITTED = 1754,
            AUDITEVENT_BATCH_MARK_AS_COMPLETED = 1755,
            AUDITEVENT_BATCH_MARK_AS_DISMISSED = 1756,
            AUDITEVENT_SE_CONNECT = 1800,
            AUDITEVENT_SE_CONNECT_DENIED = 11800,
            AUDITEVENT_SE_UPDATE_CONNECTION = 1801,
            AUDITEVENT_SE_UPDATE_CONNECTION_DENIED = 11801,
            AUDITEVENT_SE_MOVE_CONNECTION = 1802,
            AUDITEVENT_SE_MOVE_CONNECTION_DENIED = 11802,
            AUDITEVENT_SE_REMOVE_CONNECTION = 1803,
            AUDITEVENT_SE_REMOVE_CONNECTION_DENIED = 11803,
            AUDITEVENT_SE_MANAGE_HIERARCHY_DENIED = 11804,
            //Adjustments
            AUDITEVENT_PREBILL_ADJUSTMENT_CREATE = 1900,
            AUDITEVENT_PREBILL_ADJUSTMENT_CREATE_DENIED = 11900,
            AUDITEVENT_PREBILL_ADJUSTMENT_CREATE_PENDING = 1901,
            AUDITEVENT_PREBILL_ADJUSTMENT_APPROVE = 1902,
            AUDITEVENT_PREBILL_ADJUSTMENT_APPROVE_DENIED = 11902,
            AUDITEVENT_PREBILL_ADJUSTMENT_DELETE = 1903,
            AUDITEVENT_PREBILL_ADJUSTMENT_DELETE_DENIED = 11903,

            AUDITEVENT_POSTBILL_ADJUSTMENT_CREATE = 1904,
            AUDITEVENT_POSTBILL_ADJUSTMENT_CREATE_DENIED = 11904,
            AUDITEVENT_POSTBILL_ADJUSTMENT_CREATE_PENDING = 1905,
            AUDITEVENT_POSTBILL_ADJUSTMENT_APPROVE = 1906,
            AUDITEVENT_POSTBILL_ADJUSTMENT_APPROVE_DENIED = 11906,
            AUDITEVENT_POSTBILL_ADJUSTMENT_DELETE = 1907,
            AUDITEVENT_POSTBILL_ADJUSTMENT_DELETE_DENIED = 11907,


            AUDITEVENT_PREBILL_REASSIGN_CREATE = 1908,
            AUDITEVENT_PREBILL_REASSIGN_CREATE_DENIED = 11908,
            AUDITEVENT_POSTBILL_REASSIGN_CREATE = 1909,
            AUDITEVENT_POSTBILL_REASSIGN_CREATE_DENIED = 11909,
            AUDITEVENT_PREBILL_MIU_REASSIGN_CREATE = 1910,
            AUDITEVENT_PREBILL_MIU_REASSIGN_CREATE_DENIED = 11910,
            AUDITEVENT_POSTBILL_MIU_REASSIGN_CREATE = 1911,
            AUDITEVENT_POSTBILL_MIU_REASSIGN_CREATE_DENIED = 11911,
            AUDITEVENT_ACCOUNT_OWNERSHIP_CREATE = 1912,
            AUDITEVENT_ACCOUNT_OWNERSHIP_CREATE_DENIED = 11912,
            AUDITEVENT_ACCOUNT_OWNERSHIP_DELETE = 1913,
            AUDITEVENT_ACCOUNT_OWNERSHIP_DELETE_DENIED = 11913,

            //billing rerun

            AUDITEVENT_RERUNCREATE_SUCCESS = 2000,
            AUDITEVENT_RERUNCREATE_FAILED = 12000,
            AUDITEVENT_IDENTIFY_SUCCESS = 2001,
            AUDITEVENT_IDENTIFY_FAILED = 12001,
            AUDITEVENT_ANALYZE_SUCCESS = 2002,
            AUDITEVENT_ANALYZE_FAILED = 12002,
            AUDITEVENT_BACKOUTDELETE_SUCCESS = 2003,
            AUDITEVENT_BACKOUTDELETE_FAILED = 12003,
            AUDITEVENT_BACKOUTRESUBMIT_SUCCESS = 2004,
            AUDITEVENT_BACKOUTRESUBMIT_FAILED = 12004,

            //Login events (PCI compliance)
            AUDITEVENT_LOGIN_SUCCESS = 3000,
            AUDITEVENT_LOGIN_FAILED = 13000,
            AUDITEVENT_LOGIN_DORMANT_ACCOUNT_FAILED = 13001,
            AUDITEVENT_LOGIN_PASSWORD_EXPIRED_FAILED = 13002,
            AUDITEVENT_LOGIN_ACCOUNT_LOCKED_FAILED = 13003,
            AUDITEVENT_LOGIN_NO_CAPABILITY_FAILED = 13004,

            //Change password events
            AUDITEVENT_CHANGE_PASSWORD_SUCCESS = 4000,
            AUDITEVENT_CHANGE_PASSWORD_INVALID_FAILED = 14005,
            AUDITEVENT_CHANGE_PASSWORD_NO_CAPABILITY_FAILED = 14006,

            //Unlock and Lock account events
            AUDITEVENT_LOCK_ACCOUNT_SUCCESS = 5000,
            AUDITEVENT_LOCK_ACCOUNT_FAILED = 15000,
            AUDITEVENT_UNLOCK_ACCOUNT_SUCCESS = 6000,
            AUDITEVENT_UNLOCK_ACCOUNT_FAILED = 16000,

            //Credit card add/update/delete/process
            AUDITEVENT_ADD_CREDITCARD_SUCCESS = 7000,
            AUDITEVENT_UPDATE_CREDITCARD_SUCCESS = 7010,
            AUDITEVENT_DELETE_CREDITCARD_SUCCESS = 7020,
            AUDITEVENT_ASSIGN_CREDITCARD_SUCCESS = 7030,

            AUDITEVENT_SCHEDULE_PAYMENT_SUCCESS = 8000,
            AUDITEVENT_SCHEDULE_PAYMENT_FAILURE = 8100,

            AUDITEVENT_ADD_CREDITCARD_FAILED = 17000,
            AUDITEVENT_UPDATE_CREDITCARD_FAILED = 17100,
            AUDITEVENT_DELETE_CREDITCARD_FAILED = 17200,
            AUDITEVENT_ASSIGN_CREDITCARD_FAILED = 17300,
            AUDITEVENT_DEBIT_CREDITCARD_SUCCESS = 17400,
            AUDITEVENT_DEBIT_CREDITCARD_FAILED = 17500,
            AUDITEVENT_PREAUTH_CREDITCARD_SUCCESS = 17600,
            AUDITEVENT_PREAUTH_CREDITCARD_FAILED = 17700,
            AUDITEVENT_PREAUTH_CAPTURE_CREDITCARD_SUCCESS = 17800,
            AUDITEVENT_PREAUTH_CAPTURE_CREDITCARD_FAILED = 17900,
            AUDITEVENT_CREDIT_CREDITCARD_SUCCESS = 18000,
            AUDITEVENT_CREDIT_CREDITCARD_FAILED = 18100,
            AUDITEVENT_ONETIME_DEBIT_CREDITCARD_SUCCESS = 18200,
            AUDITEVENT_ONETIME_DEBIT_CREDITCARD_FAILED = 18300,
            AUDITEVENT_ONETIME_CREDIT_CREDITCARD_SUCCESS = 18400,
            AUDITEVENT_ONETIME_CREDIT_CREDITCARD_FAILED = 18500,

            AUDITEVENT_ADD_ACH_SUCCESS = 18600,
            AUDITEVENT_UPDATE_ACH_SUCCESS = 18700,
            AUDITEVENT_DELETE_ACH_SUCCESS = 18800,
            AUDITEVENT_ASSIGN_ACH_SUCCESS = 18900,
            AUDITEVENT_ADD_ACH_FAILED = 19000,
            AUDITEVENT_UPDATE_ACH_FAILED = 19100,
            AUDITEVENT_DELETE_ACH_FAILED = 19200,
            AUDITEVENT_ASSIGN_ACH_FAILED = 19300,
            AUDITEVENT_DEBIT_ACH_SUCCESS = 19400,
            AUDITEVENT_DEBIT_ACH_FAILED = 19500,
            AUDITEVENT_CREDIT_ACH_SUCCESS = 19600,
            AUDITEVENT_CREDIT_ACH_FAILED = 19700,
            AUDITEVENT_ONETIME_DEBIT_ACH_SUCCESS = 19800,
            AUDITEVENT_ONETIME_DEBIT_ACH_FAILED = 19900,
            AUDITEVENT_ONETIME_CREDIT_ACH_SUCCESS = 20000,
            AUDITEVENT_ONETIME_CREDIT_ACH_FAILED = 20100,
            AUDITEVENT_CHECK_ACH_TX_STAT_SUCCESS = 20200,
            AUDITEVENT_CHECK_ACH_TX_STAT_FAILED = 20300,
            AUDITEVENT_DOWNLOAD_ACH_TX_REP_SUCCESS = 20400,
            AUDITEVENT_DOWNLOAD_ACH_TX_REP_FAILED = 20500,

            //Price List Mapping
            AUDITEVENT_PLM_CREATE = 21000,
            AUDITEVENT_PLM_CREATE_DENIED = 21001,
            AUDITEVENT_PLM_UPDATE = 21100,
            AUDITEVENT_PLM_UPDATE_DENIED = 21101,
            AUDITEVENT_PLM_DELETE = 21200,
            AUDITEVENT_PLM_DELETE_DENIED = 21201,

            // Account Template Save / Apply / Delete / Update Events
            AUDITEVENT_ACCOUNT_TEMPLATE_SAVE_SUCCESS = 22000,
            AUDITEVENT_ACCOUNT_TEMPLATE_SAVE_FAILED = 22001,
            AUDITEVENT_ACCOUNT_TEMPLATE_APPLY_SUCCESS = 22100,
            AUDITEVENT_ACCOUNT_TEMPLATE_APPLY_FAILED = 22101,
            AUDITEVENT_ACCOUNT_TEMPLATE_UPDATE_SUCCESS = 22200,
            AUDITEVENT_ACCOUNT_TEMPLATE_UPDATE_FAILED = 22201,
            AUDITEVENT_ACCOUNT_TEMPLATE_DELETE_SUCCESS = 22300,
            AUDITEVENT_ACCOUNT_TEMPLATE_DELETE_FAILED = 22301,

            //Group Subscription Delete
            AUDITEVENT_GSUB_DELETE = 22400,
            AUDITEVENT_GSUB_DELETE_DENIED = 22401,

            //Approval Framework Related Audit Events
            AUDITEVENT_APPROVALMANAGEMENT_CHANGESUBMITTED = 23601,
            AUDITEVENT_APPROVALMANAGEMENT_CHANGEAPPROVED = 23602,
            AUDITEVENT_APPROVALMANAGEMENT_CHANGEAPPLIED = 23603,
            AUDITEVENT_APPROVALMANAGEMENT_CHANGEDENIED = 23604,
            AUDITEVENT_APPROVALMANAGEMENT_CHANGEREMOVED = 23605,
            AUDITEVENT_APPROVALMANAGEMENT_CHANGEDETAILSUPDATED = 23606,
            AUDITEVENT_APPROVALMANAGEMENT_CHANGEAPPLYFAILED = 23607,
            AUDITEVENT_APPROVALMANAGEMENT_CHANGEDISMISSED = 23608,
            AUDITEVENT_APPROVALMANAGEMENT_FAILEDCHANGERESUBMITTED = 23609,

          //Agreement Template Related Audit Events
            AUDITEVENT_AGREEMENT_TEMPLATECREATED = 23801,
            AUDITEVENT_AGREEMENT_TEMPLATEUPDATED = 23802,
            AUDITEVENT_AGREEMENT_UPDATE_FAILED = 23803,
        };

        #endregion
    }
}
