
 		   if NOT EXISTS (select name from sysobjects where name = 't_rpt_Invoice' and xtype = 'U')
 		   CREATE TABLE t_rpt_Invoice (
			InvoiceID int NOT NULL,
			InvoiceString nvarchar(50) NOT NULL,
			AccountID int NOT NULL,
			Name nvarchar (100) NOT NULL,
			IntervalID int NOT NULL,
			Company nvarchar (255) NULL,
			Address1 nvarchar (100) NULL,
			Address2 nvarchar (100) NULL,
			Address3 nvarchar (100) NULL,
			City nvarchar (30) NULL,
			Zip nvarchar (40) NULL,
			Country nvarchar (255) NULL,
			InvoiceDate datetime NULL,
			InvoiceDueDate datetime NULL,
			PreviousBalance numeric (22,10) NOT NULL,
			Payments numeric (22,10) NOT NULL,
			TotalPostBillAdjustments numeric (22,10) NOT NULL,
			BalanceForward numeric (22,10) NOT NULL,
			CurrentPreTaxAmount numeric (22,10) NOT NULL,
			CurrentTaxAmount numeric (22,10) NOT NULL,
			CurrentAmount numeric (22,10) NOT NULL,
			CurrentBalance numeric (22,10) NOT NULL,
			CurrentTotalConfCharge numeric (22,10) NOT NULL,
			CurrentTotalDiscounts numeric (22,10) NOT NULL,
			CurrentTotalRecurringCharge numeric(22,10) NOT NULL,
			CurrentTotalOtherCharge numeric(22,10) NOT NULL,
			TotalPreBillAdjustments numeric(22,10) NOT NULL,
			Currency nvarchar (10) NULL,
			InvoiceLanguage nvarchar (10) NOT NULL,
			InvoiceMethod nvarchar (255) NULL,
			CONSTRAINT PK_t_rpt_invoice PRIMARY KEY CLUSTERED (InvoiceID)
			)			
	   