
	   CREATE OR REPLACE VIEW sub_invoice_subreport (
			invoiceid,
			invoicestring,
			accountid,
			name,
			intervalid,
			company,
			address1,
			address2,
			address3,
			city,
			zip,
			country,
			invoicedate,
			invoiceduedate,
			previousbalance,
			payments,
			totalpostbilladjustments,
			balanceforward,
			currentpretaxamount,
			currenttaxamount,
			currentamount,
			currentbalance,
			currenttotalconfcharge,
			currenttotaldiscounts,
			currenttotalrecurringcharge,
			currenttotalothercharge,
			totalprebilladjustments,
			currency,
			invoicelanguage,
			invoicemethod )
			AS
			select "INVOICEID","INVOICESTRING","ACCOUNTID","NAME","INTERVALID","COMPANY","ADDRESS1","ADDRESS2","ADDRESS3","CITY","ZIP","COUNTRY","INVOICEDATE","INVOICEDUEDATE","PREVIOUSBALANCE","PAYMENTS","TOTALPOSTBILLADJUSTMENTS","BALANCEFORWARD","CURRENTPRETAXAMOUNT","CURRENTTAXAMOUNT","CURRENTAMOUNT","CURRENTBALANCE","CURRENTTOTALCONFCHARGE","CURRENTTOTALDISCOUNTS","CURRENTTOTALRECURRINGCHARGE","CURRENTTOTALOTHERCHARGE","TOTALPREBILLADJUSTMENTS","CURRENCY","INVOICELANGUAGE","INVOICEMETHOD" from t_rpt_Invoice
	   