create table SubscriptionsByMonth (
			InstanceId varchar2(64),
            SubscriptionId int not null,
            Year int not null, 
            Month int not null,
            Currency nvarchar2(3) not null,
            MRR number(22,10) not null,
            MRRPrimaryCurrency number(22,10) not null,
            MRRNew number(22,10) not null,
            MRRNewPrimaryCurrency number(22,10) not null,
            MRRBase number(22,10) not null,
            MRRBasePrimaryCurrency number(22,10) not null,
            MRRRenewal int not null,
            MRRRenewalPrimaryCurrency number(22,10) not null,
            MRRPriceChange number(22,10) not null,
			MRRPriceChangePrimaryCurrency number(22,10) not null,
            MRRChurn int not null,
            MRRChurnPrimaryCurrency number(22,10) not null,
            MRRCancelation int not null,
            MRRCancelationPrimaryCurrency number(22,10) not null,
            SubscriptionRevenue int not null,
            SubscriptionRevPrimaryCurrency number(22,10) not null,
            DaysInMonth int not null,
            DaysActiveInMonth int not null,
            ReportingCurrency nvarchar2(3) null)