/* ANNALITICS DATAMART table*/
CREATE TABLE Customer
      (InstanceId nvarchar(64) NOT NULL,
			MetraNetId int NOT NULL,
			AccountType nvarchar(200) NOT NULL,
			ExternalId nvarchar(255) NOT NULL,
			ExternalIdSpace nvarchar(40) NULL,
			FirstName nvarchar(40) NULL,
			MiddleName nvarchar(1) NULL,
			LastName nvarchar(40) NULL,
			Company nvarchar(255) NULL,
			Currency nvarchar(10) NULL,
			City nvarchar(40) NULL,
			State nvarchar(40) NULL,
			ZipCode nvarchar(40) NULL,
			Email varchar(100) NULL,
			Country nvarchar(100) NULL,
			Phone nvarchar(40) NULL,
			HierarchyMetraNetId int NOT NULL,
			HierarchyAccountType nvarchar(200) NULL,
			HierarchyExternalId nvarchar(255) NULL,
			HierarchyExternalIdSpace nvarchar(40) NULL,
			HierarchyFirstName nvarchar(40) NULL,
			HierarchyMiddleName nvarchar(1) NULL,
			HierarchyLastName nvarchar(40) NULL,
			HierarchyCompany nvarchar(255) NULL,
			HierarchyCurrency nvarchar(10) NULL,
			HierarchyCity nvarchar(40) NULL,
			HierarchyState nvarchar(40) NULL,
			HierarchyZipCode nvarchar(40) NULL,
			HierarchyCountry nvarchar(100) NULL,
			HierarchyEmail nvarchar(100) NULL,
			HierarchyPhone nvarchar(40) NULL,
			StartDate datetime NULL,
			EndDate datetime NULL,
			CONSTRAINT PK_Customer PRIMARY KEY CLUSTERED(InstanceId, MetraNetId));