
	   ALTER DATABASE %%DATABASE_NAME%% SET ARITHABORT ON
	   ALTER DATABASE %%DATABASE_NAME%% SET ANSI_NULLS ON
	   ALTER DATABASE %%DATABASE_NAME%% SET ANSI_PADDING ON
	   ALTER DATABASE %%DATABASE_NAME%% SET ANSI_WARNINGS ON
	   ALTER DATABASE %%DATABASE_NAME%% SET CONCAT_NULL_YIELDS_NULL ON
	   ALTER DATABASE %%DATABASE_NAME%% SET QUOTED_IDENTIFIER ON
	   ALTER DATABASE %%DATABASE_NAME%% SET NUMERIC_ROUNDABORT OFF
	 