/* MIDL: this ALWAYS GENERATED file contains the definitions for the interfaces */
#define MT_USERDEFINE_DESCRIPTION "RetrieveTransactionStatus\0" 
#define MT_USERDEFINE_INTERNALNAME "RetrieveTransactionStatus\0" 
#define MT_USERDEFINEORIGFILENAME MT_USERDEFINE_INTERNALNAME 
#define MT_USERDEFINEPRODUCTNAME MT_USERDEFINE_DESCRIPTION 
#define MT_USERDEF_PROJECTNAME MT_USERDEFINE_DESCRIPTION 
#define IDS_PROJNAME 100 
