
/* ===========================================================
Insert data.
============================================================== */
 INSERT into mt_audioconfcall 
   (c_ConferenceID,
    c_Payer,
    c_AccountingCode,
    c_ConferenceName,
    c_ConferenceSubject,
    c_OrganizationName,
    c_SpecialInfo,
    c_SchedulerComments,
    c_ScheduledConnections,
    c_ScheduledStartTime,
    c_ScheduledTimeGMTOffset,
    c_ScheduledDuration,
    c_CancelledFlag,
    c_CancellationTime,
    c_ServiceLevel,
    c_TerminationReason,
    c_SystemName,
    c_SalesPersonID,
    c_OperatorID,
    c_ActualNumConnections,
    c_ActualStartTime,
    c_ActualDuration,
    c_ConferenceEndTime,
    c_ConferenceTotal,
    c_LeaderName,
    c_ReservationCharges,
    c_CancelCharges,
    c_UnusedPortCharges,
    c_ConnectionTotalAmount,
    c_AdjustmentAmount,
    c_OverusedPortCharges,
    c_MTBatchID,
    c_MTBatchNamespace,
    c_MeteringStatus,
    c_MTSentTime,
    c_MTErrorMesg) 
   VALUES 
   (%%CONFERENCE_ID%%,
    '%%ACCOUNT_NAME%%',
    'pp',
    '<Conf>&',
    '%%TEST_NAME%%',
    N'abc',
    N'pqr',
    'Scheduling the call',
    1,
    %%SCHEDULED_START_TIME%%,
    5.000000,
    4,
    'N',
    %%%SYSTEMDATE%%%,
    'Standard',
    'Not Known',
    'Bridge1',
    'Amy',
    'Philip',
    1,
    %%%SYSTEMDATE%%%,
    30.000000,
    %%%SYSTEMDATE%%%,
    30.000000,
    'philip',
    .000000,
    .000000,
    .000000,
    55.000000,
    64.000000,
    .000000,
    '1',
    'MT        ',
    NULL,
    %%%SYSTEMDATE%%%,
    '')

 