//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MTAuthCapabilities.rc
//
#define IDS_PROJNAME                    100
#define IDR_MTMANAGEAHCAPABILITY        103
#define IDR_MTAPPLICATIONLOGONCAPABILITY 104
#define IDR_MTMANAGEGLOBALAUTHCAPABILITY 105
#define IDR_MTALLCAPABILITY             106
#define IDR_MTVIEWONLINEBILLCAPABILITY  107
#define IDR_MTISSUECREDITCAPABILITY     108
#define IDR_CMTCREATECORPORATEACCOUNTCAPABILITY 109
#define IDR_CMTUPDATECORPORATEACCOUNTCAPABILITY 110
#define IDR_MTCREATECSRCAPABILITY       111
#define IDR_MTUPDATECSRCAPABILITY       112
#define IDR_MTCREATESUBSCRIBERCAPABILITY 113
#define IDR_MTUPDATESUBSCRIBERCAPABILITY 114
#define IDR_MTCREATEFOLDERCAPABILITY    115
#define IDR_MTUPDATEFOLDERCAPABILITY    116
#define IDR_MTMOVEACCOUNTCAPABILITY     117
#define IDR_MTMOVEFOLDERCAPABILITY      118
#define IDR_MTMANAGEPAYMENTCAPABILITY   119
#define IDR_MTMANAGEBILLABLECAPABILITY  120
#define IDR_MTUPDACCFROMACTIVETOSUSPENDEDCAPABILITY 121
#define IDR_MTUPDACCFROMSUSPENDEDTOACTIVECAPABILITY 122
#define IDR_MTUPDACCFROMACTIVETOCLOSEDCAPABILITY 123
#define IDR_MTCREATEGROUPSUBCAPABILITY  124
#define IDR_MTUPDATEGROUPSUBCAPABILITY  125
#define IDR_MTADDMEMBERTOGROUPSUBCAPABILITY 126
#define IDR_MTMODIFYGROUPSUBMEMBERCAPABILITY 127
#define IDR_MTCREATESUBSCRIPTIONCAPABILITY 128
#define IDR_MTUPDATESUBSCRIPTIONCAPABILITY 129
#define IDR_MTICBSUBSCRIPTIONCAPABILITY 130
#define IDR_MTICBGROUPSUBSCRIPTIONCAPABILITY 131
#define IDR_MTMANAGESUBSCRIBERAUTHCAPABILITY 132
#define IDR_MTMANAGECSRAUTHCAPABILITY   133
#define IDR_MTVIEWSUBSCRIPTIONSCAPABILITY 134
#define IDR_MTVIEWGROUPSUBCAPABILITY    135
#define IDR_MTMANAGENHACCOUNTS          136
#define IDR_MTIMPERSONATEUSERCAPABILITY 137
#define IDR_MTDELETESUBSCRIPTIONCAPABILITY 138
#define IDR_MTUPDACCFROMPENDINGFINALBILLTOACTIVECAPABILITY 139
#define IDR_MTSELFSUBSCRIBE             140
#define IDR_MTUPDATEFAILEDTRANSACTIONS  141
#define IDR_MTMANAGERATESCAPABILITY     142
#define IDR_MTMANAGEPRODUCTOFFERINGSCAPABILITY 143

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        201
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         201
#define _APS_NEXT_SYMED_VALUE           144
#endif
#endif
