
	CREATE TABLE t_acc_usage_quoting
        (
		quote_id number(20) NOT NULL,
		id_sess number(20) NOT NULL,
        tx_UID raw(16) NOT NULL,
        id_acc number(10) NOT NULL,
        id_payee number(10) NOT NULL,
        id_view number(10) NOT NULL,
        id_usage_interval number(10) NOT NULL,
        id_parent_sess number(20) NULL,
        id_prod number(10) NULL,
        id_svc number(10) NOT NULL,
        dt_session date NOT NULL,
        amount number(22,10) NOT NULL,
        am_currency nvarchar2(3) NOT NULL,
        dt_crt date NOT NULL,
        tx_batch raw(16) NULL,
        tax_federal number(22,10) NULL,
        tax_state number(22,10) NULL,
        tax_county number(22,10) NULL,
        tax_local number(22,10) NULL,
        tax_other number(22,10) NULL,
        id_pi_instance number(10) NULL,
        id_pi_template number(10) NULL,
        id_se number(10) NOT NULL,
        div_currency nvarchar2(3) NULL,
        div_amount number(22,10) NULL,
        is_implied_tax char(1) NOT NULL,
        tax_calculated char(1) NULL,
        tax_informational char(1) NOT NULL,
        CONSTRAINT PK_t_acc_usage_quoting PRIMARY KEY (quote_id, id_sess,id_usage_interval));