//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.UI.Interface
{
  using System;
  using System.Collections.Generic;
  using System.Collections.ObjectModel;
  using MetraTech.BusinessEntity.Core.Model;
  using MetraTech.BusinessEntity.DataAccess.Metadata;
  
  
  public interface IUserProfile : global::MetraTech.BusinessEntity.DataAccess.Metadata.IDataObject
  {
    
    System.Nullable<System.Int32> AccountId
    {
      get;
      set;
    }
    
    System.Nullable<MetraTech.DomainModel.Enums.Core.Global.TimeZoneID> Timezone
    {
      get;
      set;
    }
    
    string Culture
    {
      get;
      set;
    }
    
    string Theme
    {
      get;
      set;
    }
    
    void Save();
  }
  
  public interface IUserProfileBusinessKey : global::MetraTech.BusinessEntity.DataAccess.Metadata.IBusinessKey
  {
    
    System.Guid InternalKey
    {
      get;
      set;
    }
  }
}
