//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.BillMessages.Interface
{
  using System;
  using System.Collections.Generic;
  using System.Collections.ObjectModel;
  using MetraTech.BusinessEntity.Core.Model;
  using MetraTech.BusinessEntity.DataAccess.Metadata;
  
  
  public interface IBillMessage : global::MetraTech.BusinessEntity.DataAccess.Metadata.IDataObject
  {
    
    MetraTech.DomainModel.Enums.Core.Metratech_com.BillMessageType MessageType
    {
      get;
      set;
    }
    
    string MessageText
    {
      get;
      set;
    }
    
    string MessageFormat
    {
      get;
      set;
    }
    
    List<global::Core.BillMessages.Interface.IBillMessageAccount> BillMessageAccounts
    {
      get;
      set;
    }
    
    void Save();
  }
  
  public interface IBillMessageBusinessKey : global::MetraTech.BusinessEntity.DataAccess.Metadata.IBusinessKey
  {
    
    string MessageCode
    {
      get;
      set;
    }
  }
}
