//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.FileLandingService.Interface
{
  using System;
  using System.Collections.Generic;
  using System.Collections.ObjectModel;
  using MetraTech.BusinessEntity.Core.Model;
  using MetraTech.BusinessEntity.DataAccess.Metadata;
  
  
  public interface IServiceHostBE : global::MetraTech.BusinessEntity.DataAccess.Metadata.IDataObject
  {
    
    string _Name
    {
      get;
      set;
    }
    
    string _Address
    {
      get;
      set;
    }
    
    MetraTech.DomainModel.Enums.Core.Metratech_com_FileLandingService.EServiceState _State
    {
      get;
      set;
    }
    
    void Save();
  }
  
  public interface IServiceHostBEBusinessKey : global::MetraTech.BusinessEntity.DataAccess.Metadata.IBusinessKey
  {
    
    System.Guid InternalKey
    {
      get;
      set;
    }
  }
}
