//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.UI.Interface
{
  using System;
  using System.Collections.Generic;
  using System.Collections.ObjectModel;
  using MetraTech.BusinessEntity.Core.Model;
  using MetraTech.BusinessEntity.DataAccess.Metadata;
  
  
  public interface ISite : global::MetraTech.BusinessEntity.DataAccess.Metadata.IDataObject
  {
    
    string Description
    {
      get;
      set;
    }
    
    string RootUrl
    {
      get;
      set;
    }
    
    System.Nullable<System.Boolean> IsSiteDownForMaintenance
    {
      get;
      set;
    }
    
    System.Nullable<MetraTech.DomainModel.Enums.Core.Global.TimeZoneID> Timezone
    {
      get;
      set;
    }
    
    string LogoImage
    {
      get;
      set;
    }
    
    string Theme
    {
      get;
      set;
    }
    
    string Culture
    {
      get;
      set;
    }
    
    global::Core.UI.Interface.IBillSetting BillSetting
    {
      get;
      set;
    }
    
    IList<global::Core.UI.Interface.ISite_BillSetting> Site_BillSettingList
    {
      get;
      set;
    }
    
    List<global::Core.UI.Interface.IDashboard> Dashboards
    {
      get;
      set;
    }
    
    IList<global::Core.UI.Interface.ISite_Dashboard> Site_DashboardList
    {
      get;
      set;
    }
    
    List<global::Core.UI.Interface.IEntryPoint> EntryPoints
    {
      get;
      set;
    }
    
    IList<global::Core.UI.Interface.ISite_EntryPoint> Site_EntryPointList
    {
      get;
      set;
    }
    
    List<global::Core.UI.Interface.IProductViewMapping> ProductViewMappings
    {
      get;
      set;
    }
    
    IList<global::Core.UI.Interface.ISite_ProductViewMapping> Site_ProductViewMappingList
    {
      get;
      set;
    }
    
    List<global::Core.UI.Interface.IReportInventory> ReportInventories
    {
      get;
      set;
    }
    
    IList<global::Core.UI.Interface.ISite_ReportInventory> Site_ReportInventoryList
    {
      get;
      set;
    }
    
    void Save();
  }
  
  public interface ISiteBusinessKey : global::MetraTech.BusinessEntity.DataAccess.Metadata.IBusinessKey
  {
    
    string SiteName
    {
      get;
      set;
    }
  }
}
