//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.UI.Interface
{
  using System;
  using System.Collections.Generic;
  using System.Collections.ObjectModel;
  using MetraTech.BusinessEntity.Core.Model;
  using MetraTech.BusinessEntity.DataAccess.Metadata;
  
  
  public interface ISite_BillSetting : global::MetraTech.BusinessEntity.DataAccess.Metadata.IDataObject
  {
    
    global::Core.UI.Interface.ISite Site
    {
      get;
      set;
    }
    
    global::Core.UI.Interface.IBillSetting BillSetting
    {
      get;
      set;
    }
    
    void SetRelationshipItem(object item);
    
    void Save();
  }
  
  public interface ISite_BillSettingBusinessKey : global::MetraTech.BusinessEntity.DataAccess.Metadata.IBusinessKey
  {
    
    System.Guid InternalKey
    {
      get;
      set;
    }
  }
}
