//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Core.Interface
{
  using System;
  using System.Collections.Generic;
  using System.Collections.ObjectModel;
  using MetraTech.BusinessEntity.Core.Model;
  using MetraTech.BusinessEntity.DataAccess.Metadata;
  
  
  public interface IDispute : global::MetraTech.BusinessEntity.DataAccess.Metadata.IDataObject
  {
    
    System.Nullable<System.Int32> invoiceId
    {
      get;
      set;
    }
    
    string invoiceNum
    {
      get;
      set;
    }
    
    MetraTech.DomainModel.Enums.Core.Metratech_com_Dispute.DisputeStatus status
    {
      get;
      set;
    }
    
    string title
    {
      get;
      set;
    }
    
    string description
    {
      get;
      set;
    }
    
    string NewProperty
    {
      get;
      set;
    }
    
    List<global::Core.Core.Interface.IChargeAdjustment> ChargeAdjustments
    {
      get;
      set;
    }
    
    global::Core.Core.Interface.IInvoiceAdjustment InvoiceAdjustment
    {
      get;
      set;
    }
    
    void Save();
  }
  
  public interface IDisputeBusinessKey : global::MetraTech.BusinessEntity.DataAccess.Metadata.IBusinessKey
  {
    
    System.Guid InternalKey
    {
      get;
      set;
    }
  }
}
