//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetraTech.Core.CreditNotes.Interface
{
  using System;
  using System.Collections.Generic;
  using System.Collections.ObjectModel;
  using MetraTech.BusinessEntity.Core.Model;
  using MetraTech.BusinessEntity.DataAccess.Metadata;
  
  
  public interface ICreditNoteItem : global::MetraTech.BusinessEntity.DataAccess.Metadata.IDataObject
  {
    
    long UsageIntervalID
    {
      get;
      set;
    }
    
    int CreditNoteItemID
    {
      get;
      set;
    }
    
    int AdjustmentType
    {
      get;
      set;
    }
    
    System.Nullable<System.Int32> AdjustmentTransactionID
    {
      get;
      set;
    }
    
    System.Nullable<System.Int64> SessionID
    {
      get;
      set;
    }
    
    global::MetraTech.Core.CreditNotes.Interface.ICreditNote CreditNote
    {
      get;
      set;
    }
    
    void Save();
  }
  
  public interface ICreditNoteItemBusinessKey : global::MetraTech.BusinessEntity.DataAccess.Metadata.IBusinessKey
  {
    
    System.Guid InternalKey
    {
      get;
      set;
    }
  }
}
