
               CREATE TABLE t_export_workqueue
              (
                id_work_queue RAW(16) DEFAULT (SYS_GUID()) NOT NULL,
                id_rep_instance_id NUMBER(10,0)  ,
                id_rep NUMBER(10,0)  ,
                id_schedule NUMBER(10,0)  ,
                c_sch_type VARCHAR2(10)  ,
                dt_queued DATE NOT NULL,
                dt_sched_run DATE  ,
                c_use_database VARCHAR2(50)  ,
                c_rep_title VARCHAR2(50)  NOT NULL,
                c_rep_type VARCHAR2(50)  NOT NULL,
                c_rep_def_source VARCHAR2(100)  ,
                c_rep_query_tag VARCHAR2(100)  ,
                c_rep_output_type VARCHAR2(10)  ,                
                c_rep_distrib_type VARCHAR2(50)  ,
                c_rep_destn VARCHAR2(500)  ,
                c_destn_direct NUMBER(1,0)  ,
                c_destn_access_user VARCHAR2(50)  ,
                c_destn_access_pwd NVARCHAR2(2000)  ,
                c_exec_type CHAR(10)  ,
                c_eop_step_instance_name NVARCHAR2(510)  ,
                c_generate_control_file NUMBER(1,0)  ,
                c_control_file_delivery_locati VARCHAR2(255)  ,
                c_compressreport NUMBER(1,0)  ,
                c_compressthreshold NUMBER(10,0)  ,
                c_output_execute_params_info NUMBER(1,0)  ,
                c_use_quoted_identifiers NUMBER(1,0) DEFAULT (0),
                c_ds_id NUMBER(10,0)  ,
                dt_last_run DATE  NOT NULL,
                dt_next_run DATE  ,
                c_current_process_stage NUMBER(10,0)  ,
                c_processing_server VARCHAR2(50)  ,
                c_param_name_values VARCHAR2(1000)  ,
                id_run NUMBER(10,0)  ,
                c_queuerow_source VARCHAR2(100)  ,
                c_output_file_name VARCHAR2(50)  ,
                c_id_work_queue_int NUMBER(10,0)  NOT NULL,
                CONSTRAINT PK_t_export_workqueue PRIMARY KEY( id_work_queue )
              )
			 