
              CREATE TABLE t_export_execute_audit
              (
                id_audit NUMBER(10,0)  NOT NULL,
                id_work_queue CHAR(36)  ,
                id_rep NUMBER(10,0)  ,
                id_rep_instance_id NUMBER(10,0)  ,
                id_schedule NUMBER(10,0)  ,
                c_sch_type VARCHAR2(10)  ,
                dt_queued DATE  ,
                dt_sched_run DATE  ,
                c_use_database VARCHAR2(50)  NOT NULL,
                c_rep_title VARCHAR2(50)  NOT NULL,
                c_rep_type VARCHAR2(50)  NOT NULL,
                c_rep_def_source VARCHAR2(100)  ,
                c_rep_query_tag VARCHAR2(100)  ,
                c_rep_output_type VARCHAR2(10)  ,
                c_rep_distrib_type VARCHAR2(50)  ,
                c_rep_destn VARCHAR2(500)  ,
                c_destn_access_user VARCHAR2(50)  ,
                c_exec_type CHAR(10)  ,
                c_processed_server VARCHAR2(50)  ,
                c_eop_step_instance_name NVARCHAR2(510)  ,
                c_generate_control_file NUMBER(1,0)  ,
                c_control_file_delivery_locati VARCHAR2(255)  ,
                c_compressreport NUMBER(1,0)  ,
                c_compressthreshold NUMBER(10,0)  ,
                c_output_execute_params_info NUMBER(1,0)  ,
                c_use_quoted_identifiers NUMBER(1,0) DEFAULT (0) NOT NULL,
                c_ds_id NUMBER(10,0)  ,
                id_run NUMBER(10,0)  ,
                run_start_dt DATE  NOT NULL,
                run_end_dt DATE  NOT NULL,
                c_run_result_status VARCHAR2(50)  NOT NULL,
                c_run_result_descr VARCHAR2(2000)  ,
                c_execute_paraminfo VARCHAR2(1000)  NOT NULL,
                c_execution_backedout NUMBER(10,0) DEFAULT (0) NOT NULL,
                c_queuerow_source VARCHAR2(100)  NOT NULL,
                c_output_file_name VARCHAR2(50)  ,
                CONSTRAINT PK_t_export_execute_audit PRIMARY KEY( id_audit )
              )
			 