SELECT DISTINCT TABLE_NAME  FROM DBA_TAB_PARTITIONS 
WHERE TABLE_OWNER = USER AND (TABLE_NAME LIKE 'T_SVC_%'
OR TABLE_NAME LIKE 'T_PV_%'
OR TABLE_NAME in ('T_ACC_USAGE', 'T_MESSAGE', 'T_SESSION', 'T_SESSION_SET', 'T_SESSION_STATE', 'AGG_CHARGE_AUDIT_TRAIL', 'AGG_USAGE_AUDIT_TRIAL'))