@echo Removing MetraPay code...
RMDIR Payments /s /q
cd App_code
del MetraPayManager.cs
@echo The MetraPay code has been removed.  You shold also set the site Bill Setting property AllowOnlinePayment to false...  