
CREATE GLOBAL TEMPORARY TABLE tmp_discount_1 
( 
  ID_ACC          NUMBER(10), 
  ID_PAYER        NUMBER(10), 
  ID_PI_INSTANCE  NUMBER(10), 
  ID_PI_TEMPLATE  NUMBER(10), 
  ID_PO           NUMBER(10), 
  ID_USAGE_CYCLE  NUMBER(10), 
  DT_BILL_START   DATE, 
  DT_BILL_END     DATE, 
  DT_SUB_START    DATE, 
  DT_SUB_END      DATE,
  VT_PAY_START    DATE, 
  VT_PAY_END      DATE, 
  TT_PAY_START    DATE, 
  TT_PAY_END      DATE
) ON COMMIT PRESERVE ROWS
