
CREATE GLOBAL TEMPORARY TABLE tmp_recurring_charge_candidate
(
  C_RCACTIONTYPE                 VARCHAR2(32),
  C__ACCOUNTID                   NUMBER(10),
  C__PAYINGACCOUNT               NUMBER(10)     ,
  C_BILLINGINTERVALSTART         DATE           ,
  C_BILLINGINTERVALEND           DATE           ,
  C_NEXTBILLINGINTERVALSTART     DATE           ,
  C_NEXTBILLINGINTERVALEND       DATE           ,
  C__PRICEABLEITEMINSTANCEID     NUMBER(10),
  C__PRICEABLEITEMTEMPLATEID     NUMBER(10),
  C__PRODUCTOFFERINGID           NUMBER(10),
  C_RCINTERVALSTART              DATE           ,
  C_RCINTERVALEND                DATE           ,
  C__SUBSCRIPTIONID              NUMBER(10),
  C_SUBSCRIPTIONSTART            DATE,
  C_SUBSCRIPTIONEND              DATE,
  C_RCINTERVALSUBSCRIPTIONSTART  DATE,
  C_RCINTERVALSUBSCRIPTIONEND    DATE,
  C_ADVANCE                      CHAR(1)        ,
  C_PRORATEONSUBSCRIPTION        CHAR(1)        ,
  C_PRORATEINSTANTLY             CHAR(1)        ,
  C_PRORATEONUNSUBSCRIPTION      CHAR(1)        ,
  C_PRORATIONCYCLELENGTH         NUMBER(10),
  C_BILLEDRATEDATE               DATE,
  CANDIDATE_TT_END               DATE           ,
  CANDIDATE_ORIGINATOR_TT_END    DATE,
  B_PER_SUBSCRIPTION             CHAR(1),
  C_UNITVALUE                    NUMBER(22,10)   ,
  C_UNITVALUESTART               DATE           ,
  C_UNITVALUEEND                 DATE           ,
  C_RATINGTYPE                   NUMBER(10)     ,
  RUN_ID_EVENT                   NUMBER(10)     ,
  RUN_VT_START                   DATE           
) ON COMMIT PRESERVE ROWS
