
		CREATE GLOBAL TEMPORARY TABLE TEMPEFF
		 (ID_SCHED INT NOT NULL,
		  DT_MODIFIED DATE NOT NULL,
		  ID_PARAMTABLE INT NOT NULL,
		  ID_PRICELIST INT NOT NULL,
		  ID_SUB INT NULL,
		  ID_PO INT NULL,
		  ID_PI_INSTANCE INT NULL)
		  ON COMMIT PRESERVE ROWS
		 