
CREATE GLOBAL TEMPORARY TABLE tmp_discount_2
( 
  ID_INTERVAL        NUMBER(10),  
  ID_ACC             NUMBER(10), 
  ID_PAYER           NUMBER(10), 
  ID_PI_INSTANCE     NUMBER(10), 
  ID_PI_TEMPLATE     NUMBER(10), 
  ID_PO              NUMBER(10), 
  DT_BILL_START	     DATE, 
  DT_BILL_END        DATE, 
  DT_SUB_START	     DATE, 
  DT_SUB_END         DATE, 
  DT_EFFDISC_START   DATE, 
  DT_EFFDISC_END     DATE, 
  DT_DISC_START	     DATE, 
  DT_DISC_END        DATE,
  TT_PAY_END         DATE
) ON COMMIT PRESERVE ROWS
