#define MT_USERDEFINE_DESCRIPTION "QueryAdapter\0" 
#define MT_USERDEFINE_INTERNALNAME "QueryAdapter\0" 
#define MT_USERDEFINEORIGFILENAME MT_USERDEFINE_INTERNALNAME 
#define MT_USERDEFINEPRODUCTNAME MT_USERDEFINE_DESCRIPTION 
#define MT_USERDEF_PROJECTNAME MT_USERDEFINE_DESCRIPTION 
