//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.UI
{
  using System;
  using System.Collections.Generic;
  using System.Collections.ObjectModel;
  using System.Runtime.Serialization;
  using System.Linq;
  using MetraTech.Basic;
  using MetraTech.BusinessEntity.Core;
  using MetraTech.BusinessEntity.Core.Model;
  using MetraTech.BusinessEntity.DataAccess.Metadata;
  using MetraTech.BusinessEntity.DataAccess.Persistence;
  
  
  [System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
  [System.SerializableAttribute()]
  [System.Runtime.Serialization.KnownTypeAttribute("GetKnownTypes")]
  [MetraTech.BusinessEntity.Core.Model.ConfigDrivenAttribute()]
  public partial class BillSetting : MetraTech.BusinessEntity.DataAccess.Metadata.DataObject, global::Core.UI.Interface.IBillSetting
  {
    
    public const string FullName = "Core.UI.BillSetting";
    
    private int @__Version;
    
    public const string Property__Version = "_Version";
    
    private System.Nullable<System.DateTime> _creationDate;
    
    public const string Property_CreationDate = "CreationDate";
    
    private System.Nullable<System.DateTime> _updateDate;
    
    public const string Property_UpdateDate = "UpdateDate";
    
    private System.Nullable<System.Int32> _uID;
    
    public const string Property_UID = "UID";
    
    public const string Property_Id = "Id";
    
    private global::Core.UI.BillSettingBusinessKey _billSettingBusinessKey = new BillSettingBusinessKey();
    
    private System.Nullable<System.Boolean> _inlineTax;
    
    public const string Property_InlineTax = "InlineTax";
    
    private System.Nullable<System.Boolean> _inlineAdjustments;
    
    public const string Property_InlineAdjustments = "InlineAdjustments";
    
    private System.Nullable<System.Boolean> _allowSelfCare;
    
    public const string Property_AllowSelfCare = "AllowSelfCare";
    
    private System.Nullable<System.Boolean> _allowOnlinePayment;
    
    public const string Property_AllowOnlinePayment = "AllowOnlinePayment";
    
    private System.Nullable<System.Boolean> _allowSavedReports;
    
    public const string Property_AllowSavedReports = "AllowSavedReports";
    
    private System.Nullable<System.Boolean> _showSecondPassData;
    
    public const string Property_ShowSecondPassData = "ShowSecondPassData";
    
    private System.Nullable<System.Boolean> _allowSharedReports = true;
    
    public const string Property_AllowSharedReports = "AllowSharedReports";
    
    private System.Nullable<System.Boolean> _showOnlyHardClosedIntervals = false;
    
    public const string Property_ShowOnlyHardClosedIntervals = "ShowOnlyHardClosedIntervals";
    
    private global::Core.UI.Interface.ISite _site;
    
    private IList<global::Core.UI.Interface.ISite_BillSetting> _site_BillSettingList = new List<global::Core.UI.Interface.ISite_BillSetting>();
    
    public const string Relationship_Site_BillSetting = "Site_BillSetting";
    
    public const string Property_InternalKey = "InternalKey";
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public override int _Version
    {
      get
      {
        return this.@__Version;
      }
      set
      {
        this.@__Version = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public override System.Nullable<System.DateTime> CreationDate
    {
      get
      {
        return this._creationDate;
      }
      set
      {
        this._creationDate = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public override System.Nullable<System.DateTime> UpdateDate
    {
      get
      {
        return this._updateDate;
      }
      set
      {
        this._updateDate = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual System.Nullable<System.Int32> UID
    {
      get
      {
        return this._uID;
      }
      set
      {
        this._uID = value;
      }
    }
    
    [MetraTech.BusinessEntity.DataAccess.Metadata.BusinessKeyAttribute()]
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual global::Core.UI.BillSettingBusinessKey BillSettingBusinessKey
    {
      get
      {
        return this._billSettingBusinessKey;
      }
      set
      {
        this._billSettingBusinessKey = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual System.Nullable<System.Boolean> InlineTax
    {
      get
      {
        return this._inlineTax;
      }
      set
      {
        this._inlineTax = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual System.Nullable<System.Boolean> InlineAdjustments
    {
      get
      {
        return this._inlineAdjustments;
      }
      set
      {
        this._inlineAdjustments = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual System.Nullable<System.Boolean> AllowSelfCare
    {
      get
      {
        return this._allowSelfCare;
      }
      set
      {
        this._allowSelfCare = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual System.Nullable<System.Boolean> AllowOnlinePayment
    {
      get
      {
        return this._allowOnlinePayment;
      }
      set
      {
        this._allowOnlinePayment = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual System.Nullable<System.Boolean> AllowSavedReports
    {
      get
      {
        return this._allowSavedReports;
      }
      set
      {
        this._allowSavedReports = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual System.Nullable<System.Boolean> ShowSecondPassData
    {
      get
      {
        return this._showSecondPassData;
      }
      set
      {
        this._showSecondPassData = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual System.Nullable<System.Boolean> AllowSharedReports
    {
      get
      {
        return this._allowSharedReports;
      }
      set
      {
        this._allowSharedReports = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual System.Nullable<System.Boolean> ShowOnlyHardClosedIntervals
    {
      get
      {
        return this._showOnlyHardClosedIntervals;
      }
      set
      {
        this._showOnlyHardClosedIntervals = value;
      }
    }
    
    public virtual global::Core.UI.Interface.ISite Site
    {
      get
      {
        return this._site;
      }
      set
      {
        this._site = value;
      }
    }
    
    public virtual IList<global::Core.UI.Interface.ISite_BillSetting> Site_BillSettingList
    {
      get
      {
        return this._site_BillSettingList;
      }
      set
      {
        this._site_BillSettingList = value;
      }
    }
    
    public override void SetupRelationships()
    {
    }
    
    public virtual object Clone()
    {
      var _billSetting = new global::Core.UI.BillSetting();
      _billSetting.BillSettingBusinessKey = (global::Core.UI.BillSettingBusinessKey)BillSettingBusinessKey.Clone();
      _billSetting.InlineTax = InlineTax;
      _billSetting.InlineAdjustments = InlineAdjustments;
      _billSetting.AllowSelfCare = AllowSelfCare;
      _billSetting.AllowOnlinePayment = AllowOnlinePayment;
      _billSetting.AllowSavedReports = AllowSavedReports;
      _billSetting.ShowSecondPassData = ShowSecondPassData;
      _billSetting.AllowSharedReports = AllowSharedReports;
      _billSetting.ShowOnlyHardClosedIntervals = ShowOnlyHardClosedIntervals;
      return _billSetting;
    }
    
    public virtual void Save()
    {
      var item = this;
      global::MetraTech.BusinessEntity.DataAccess.Persistence.StandardRepository.Instance.SaveInstance(ref item);
    }
    
    public override void CopyPropertiesFrom(global::MetraTech.BusinessEntity.DataAccess.Metadata.DataObject dataObject)
    {
      var item = dataObject as global::Core.UI.BillSetting;
      InlineTax = item.InlineTax;
      InlineAdjustments = item.InlineAdjustments;
      AllowSelfCare = item.AllowSelfCare;
      AllowOnlinePayment = item.AllowOnlinePayment;
      AllowSavedReports = item.AllowSavedReports;
      ShowSecondPassData = item.ShowSecondPassData;
      AllowSharedReports = item.AllowSharedReports;
      ShowOnlyHardClosedIntervals = item.ShowOnlyHardClosedIntervals;
      BillSettingBusinessKey = item.BillSettingBusinessKey;
    }
    
    public static new System.Type[] GetKnownTypes()
    {
      var knownTypes = new List<System.Type>();
      knownTypes.Add(typeof(global::Core.UI.BillSettingBusinessKey));
      return knownTypes.ToArray();
    }
  }
  
  [System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
  [System.SerializableAttribute()]
  public partial class BillSettingBusinessKey : MetraTech.BusinessEntity.DataAccess.Metadata.BusinessKey, global::Core.UI.Interface.IBillSettingBusinessKey
  {
    
    private string _entityFullName = "Core.UI.BillSetting";
    
    private System.Guid _internalKey;
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public override string EntityFullName
    {
      get
      {
        return this._entityFullName;
      }
      set
      {
        this._entityFullName = "Core.UI.BillSetting";
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual System.Guid InternalKey
    {
      get
      {
        return this._internalKey;
      }
      set
      {
        this._internalKey = value;
      }
    }
    
    public override object Clone()
    {
      var _businessKey = new BillSettingBusinessKey();
      _businessKey.InternalKey = InternalKey;
      return _businessKey;
    }
  }
}
