//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.UI
{
  using System;
  using System.Collections.Generic;
  using System.Collections.ObjectModel;
  using System.Runtime.Serialization;
  using System.Linq;
  using MetraTech.Basic;
  using MetraTech.BusinessEntity.Core;
  using MetraTech.BusinessEntity.Core.Model;
  using MetraTech.BusinessEntity.DataAccess.Metadata;
  using MetraTech.BusinessEntity.DataAccess.Persistence;
  
  
  [System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
  [System.SerializableAttribute()]
  [System.Runtime.Serialization.KnownTypeAttribute("GetKnownTypes")]
  [MetraTech.BusinessEntity.Core.Model.ConfigDrivenAttribute()]
  public partial class EntryPoint : MetraTech.BusinessEntity.DataAccess.Metadata.DataObject, global::Core.UI.Interface.IEntryPoint
  {
    
    public const string FullName = "Core.UI.EntryPoint";
    
    private int @__Version;
    
    public const string Property__Version = "_Version";
    
    private System.Nullable<System.DateTime> _creationDate;
    
    public const string Property_CreationDate = "CreationDate";
    
    private System.Nullable<System.DateTime> _updateDate;
    
    public const string Property_UpdateDate = "UpdateDate";
    
    private System.Nullable<System.Int32> _uID;
    
    public const string Property_UID = "UID";
    
    public const string Property_Id = "Id";
    
    private global::Core.UI.EntryPointBusinessKey _entryPointBusinessKey = new EntryPointBusinessKey();
    
    private string _url;
    
    public const string Property_Url = "Url";
    
    private string _description;
    
    public const string Property_Description = "Description";
    
    private global::Core.UI.Interface.ISite _site;
    
    private IList<global::Core.UI.Interface.ISite_EntryPoint> _site_EntryPointList = new List<global::Core.UI.Interface.ISite_EntryPoint>();
    
    public const string Relationship_Site_EntryPoint = "Site_EntryPoint";
    
    public const string Property_EntryPointName = "EntryPointName";
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public override int _Version
    {
      get
      {
        return this.@__Version;
      }
      set
      {
        this.@__Version = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public override System.Nullable<System.DateTime> CreationDate
    {
      get
      {
        return this._creationDate;
      }
      set
      {
        this._creationDate = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public override System.Nullable<System.DateTime> UpdateDate
    {
      get
      {
        return this._updateDate;
      }
      set
      {
        this._updateDate = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual System.Nullable<System.Int32> UID
    {
      get
      {
        return this._uID;
      }
      set
      {
        this._uID = value;
      }
    }
    
    [MetraTech.BusinessEntity.DataAccess.Metadata.BusinessKeyAttribute()]
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual global::Core.UI.EntryPointBusinessKey EntryPointBusinessKey
    {
      get
      {
        return this._entryPointBusinessKey;
      }
      set
      {
        this._entryPointBusinessKey = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual string Url
    {
      get
      {
        return this._url;
      }
      set
      {
        this._url = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual string Description
    {
      get
      {
        return this._description;
      }
      set
      {
        this._description = value;
      }
    }
    
    public virtual global::Core.UI.Interface.ISite Site
    {
      get
      {
        return this._site;
      }
      set
      {
        this._site = value;
      }
    }
    
    public virtual IList<global::Core.UI.Interface.ISite_EntryPoint> Site_EntryPointList
    {
      get
      {
        return this._site_EntryPointList;
      }
      set
      {
        this._site_EntryPointList = value;
      }
    }
    
    public override void SetupRelationships()
    {
    }
    
    public virtual object Clone()
    {
      var _entryPoint = new global::Core.UI.EntryPoint();
      _entryPoint.EntryPointBusinessKey = (global::Core.UI.EntryPointBusinessKey)EntryPointBusinessKey.Clone();
      _entryPoint.Url = Url;
      _entryPoint.Description = Description;
      return _entryPoint;
    }
    
    public virtual void Save()
    {
      var item = this;
      global::MetraTech.BusinessEntity.DataAccess.Persistence.StandardRepository.Instance.SaveInstance(ref item);
    }
    
    public override void CopyPropertiesFrom(global::MetraTech.BusinessEntity.DataAccess.Metadata.DataObject dataObject)
    {
      var item = dataObject as global::Core.UI.EntryPoint;
      Url = item.Url;
      Description = item.Description;
      EntryPointBusinessKey = item.EntryPointBusinessKey;
    }
    
    public static new System.Type[] GetKnownTypes()
    {
      var knownTypes = new List<System.Type>();
      knownTypes.Add(typeof(global::Core.UI.EntryPointBusinessKey));
      return knownTypes.ToArray();
    }
  }
  
  [System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
  [System.SerializableAttribute()]
  public partial class EntryPointBusinessKey : MetraTech.BusinessEntity.DataAccess.Metadata.BusinessKey, global::Core.UI.Interface.IEntryPointBusinessKey
  {
    
    private string _entityFullName = "Core.UI.EntryPoint";
    
    private string _entryPointName;
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public override string EntityFullName
    {
      get
      {
        return this._entityFullName;
      }
      set
      {
        this._entityFullName = "Core.UI.EntryPoint";
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual string EntryPointName
    {
      get
      {
        return this._entryPointName;
      }
      set
      {
        this._entryPointName = value;
      }
    }
    
    public override object Clone()
    {
      var _businessKey = new EntryPointBusinessKey();
      _businessKey.EntryPointName = EntryPointName;
      return _businessKey;
    }
  }
}
