//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.UI
{
  using System;
  using System.Collections.Generic;
  using System.Collections.ObjectModel;
  using System.Runtime.Serialization;
  using System.Linq;
  using MetraTech.Basic;
  using MetraTech.BusinessEntity.Core;
  using MetraTech.BusinessEntity.Core.Model;
  using MetraTech.BusinessEntity.DataAccess.Metadata;
  using MetraTech.BusinessEntity.DataAccess.Persistence;
  
  
  [System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
  [System.SerializableAttribute()]
  [System.Runtime.Serialization.KnownTypeAttribute("GetKnownTypes")]
  [MetraTech.BusinessEntity.Core.Model.ConfigDrivenAttribute()]
  public partial class Parameter : MetraTech.BusinessEntity.DataAccess.Metadata.DataObject, global::Core.UI.Interface.IParameter
  {
    
    public const string FullName = "Core.UI.Parameter";
    
    private int @__Version;
    
    public const string Property__Version = "_Version";
    
    private System.Nullable<System.DateTime> _creationDate;
    
    public const string Property_CreationDate = "CreationDate";
    
    private System.Nullable<System.DateTime> _updateDate;
    
    public const string Property_UpdateDate = "UpdateDate";
    
    private System.Nullable<System.Int32> _uID;
    
    public const string Property_UID = "UID";
    
    public const string Property_Id = "Id";
    
    private global::Core.UI.ParameterBusinessKey _parameterBusinessKey = new ParameterBusinessKey();
    
    private string _name;
    
    public const string Property_Name = "Name";
    
    private string _value;
    
    public const string Property_Value = "Value";
    
    private string _description;
    
    public const string Property_Description = "Description";
    
    private System.Nullable<System.Boolean> _isRequired;
    
    public const string Property_IsRequired = "IsRequired";
    
    private global::Core.UI.Interface.IWidget _widget;
    
    private IList<global::Core.UI.Interface.IWidget_Parameter> _widget_ParameterList = new List<global::Core.UI.Interface.IWidget_Parameter>();
    
    public const string Relationship_Widget_Parameter = "Widget_Parameter";
    
    public const string Property_InternalKey = "InternalKey";
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public override int _Version
    {
      get
      {
        return this.@__Version;
      }
      set
      {
        this.@__Version = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public override System.Nullable<System.DateTime> CreationDate
    {
      get
      {
        return this._creationDate;
      }
      set
      {
        this._creationDate = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public override System.Nullable<System.DateTime> UpdateDate
    {
      get
      {
        return this._updateDate;
      }
      set
      {
        this._updateDate = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual System.Nullable<System.Int32> UID
    {
      get
      {
        return this._uID;
      }
      set
      {
        this._uID = value;
      }
    }
    
    [MetraTech.BusinessEntity.DataAccess.Metadata.BusinessKeyAttribute()]
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual global::Core.UI.ParameterBusinessKey ParameterBusinessKey
    {
      get
      {
        return this._parameterBusinessKey;
      }
      set
      {
        this._parameterBusinessKey = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual string Name
    {
      get
      {
        return this._name;
      }
      set
      {
        this._name = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual string Value
    {
      get
      {
        return this._value;
      }
      set
      {
        this._value = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual string Description
    {
      get
      {
        return this._description;
      }
      set
      {
        this._description = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual System.Nullable<System.Boolean> IsRequired
    {
      get
      {
        return this._isRequired;
      }
      set
      {
        this._isRequired = value;
      }
    }
    
    public virtual global::Core.UI.Interface.IWidget Widget
    {
      get
      {
        return this._widget;
      }
      set
      {
        this._widget = value;
      }
    }
    
    public virtual IList<global::Core.UI.Interface.IWidget_Parameter> Widget_ParameterList
    {
      get
      {
        return this._widget_ParameterList;
      }
      set
      {
        this._widget_ParameterList = value;
      }
    }
    
    public override void SetupRelationships()
    {
    }
    
    public virtual object Clone()
    {
      var _parameter = new global::Core.UI.Parameter();
      _parameter.ParameterBusinessKey = (global::Core.UI.ParameterBusinessKey)ParameterBusinessKey.Clone();
      _parameter.Name = Name;
      _parameter.Value = Value;
      _parameter.Description = Description;
      _parameter.IsRequired = IsRequired;
      return _parameter;
    }
    
    public virtual void Save()
    {
      var item = this;
      global::MetraTech.BusinessEntity.DataAccess.Persistence.StandardRepository.Instance.SaveInstance(ref item);
    }
    
    public override void CopyPropertiesFrom(global::MetraTech.BusinessEntity.DataAccess.Metadata.DataObject dataObject)
    {
      var item = dataObject as global::Core.UI.Parameter;
      Name = item.Name;
      Value = item.Value;
      Description = item.Description;
      IsRequired = item.IsRequired;
      ParameterBusinessKey = item.ParameterBusinessKey;
    }
    
    public static new System.Type[] GetKnownTypes()
    {
      var knownTypes = new List<System.Type>();
      knownTypes.Add(typeof(global::Core.UI.ParameterBusinessKey));
      return knownTypes.ToArray();
    }
  }
  
  [System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
  [System.SerializableAttribute()]
  public partial class ParameterBusinessKey : MetraTech.BusinessEntity.DataAccess.Metadata.BusinessKey, global::Core.UI.Interface.IParameterBusinessKey
  {
    
    private string _entityFullName = "Core.UI.Parameter";
    
    private System.Guid _internalKey;
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public override string EntityFullName
    {
      get
      {
        return this._entityFullName;
      }
      set
      {
        this._entityFullName = "Core.UI.Parameter";
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual System.Guid InternalKey
    {
      get
      {
        return this._internalKey;
      }
      set
      {
        this._internalKey = value;
      }
    }
    
    public override object Clone()
    {
      var _businessKey = new ParameterBusinessKey();
      _businessKey.InternalKey = InternalKey;
      return _businessKey;
    }
  }
}
