//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.UI
{
  using System;
  using System.Collections.Generic;
  using System.Collections.ObjectModel;
  using System.Runtime.Serialization;
  using System.Linq;
  using MetraTech.Basic;
  using MetraTech.BusinessEntity.Core;
  using MetraTech.BusinessEntity.Core.Model;
  using MetraTech.BusinessEntity.DataAccess.Metadata;
  using MetraTech.BusinessEntity.DataAccess.Persistence;
  
  
  [System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
  [System.SerializableAttribute()]
  [System.Runtime.Serialization.KnownTypeAttribute("GetKnownTypes")]
  [MetraTech.BusinessEntity.Core.Model.ConfigDrivenAttribute()]
  public partial class ProductViewMapping : MetraTech.BusinessEntity.DataAccess.Metadata.DataObject, global::Core.UI.Interface.IProductViewMapping
  {
    
    public const string FullName = "Core.UI.ProductViewMapping";
    
    private int @__Version;
    
    public const string Property__Version = "_Version";
    
    private System.Nullable<System.DateTime> _creationDate;
    
    public const string Property_CreationDate = "CreationDate";
    
    private System.Nullable<System.DateTime> _updateDate;
    
    public const string Property_UpdateDate = "UpdateDate";
    
    private System.Nullable<System.Int32> _uID;
    
    public const string Property_UID = "UID";
    
    public const string Property_Id = "Id";
    
    private global::Core.UI.ProductViewMappingBusinessKey _productViewMappingBusinessKey = new ProductViewMappingBusinessKey();
    
    private string _customPage = "Custom/MyPage.aspx";
    
    public const string Property_CustomPage = "CustomPage";
    
    private string _customLayout;
    
    public const string Property_CustomLayout = "CustomLayout";
    
    private global::Core.UI.Interface.ISite _site;
    
    private IList<global::Core.UI.Interface.ISite_ProductViewMapping> _site_ProductViewMappingList = new List<global::Core.UI.Interface.ISite_ProductViewMapping>();
    
    public const string Relationship_Site_ProductViewMapping = "Site_ProductViewMapping";
    
    public const string Property_ProductViewName = "ProductViewName";
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public override int _Version
    {
      get
      {
        return this.@__Version;
      }
      set
      {
        this.@__Version = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public override System.Nullable<System.DateTime> CreationDate
    {
      get
      {
        return this._creationDate;
      }
      set
      {
        this._creationDate = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public override System.Nullable<System.DateTime> UpdateDate
    {
      get
      {
        return this._updateDate;
      }
      set
      {
        this._updateDate = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual System.Nullable<System.Int32> UID
    {
      get
      {
        return this._uID;
      }
      set
      {
        this._uID = value;
      }
    }
    
    [MetraTech.BusinessEntity.DataAccess.Metadata.BusinessKeyAttribute()]
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual global::Core.UI.ProductViewMappingBusinessKey ProductViewMappingBusinessKey
    {
      get
      {
        return this._productViewMappingBusinessKey;
      }
      set
      {
        this._productViewMappingBusinessKey = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual string CustomPage
    {
      get
      {
        return this._customPage;
      }
      set
      {
        this._customPage = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual string CustomLayout
    {
      get
      {
        return this._customLayout;
      }
      set
      {
        this._customLayout = value;
      }
    }
    
    public virtual global::Core.UI.Interface.ISite Site
    {
      get
      {
        return this._site;
      }
      set
      {
        this._site = value;
      }
    }
    
    public virtual IList<global::Core.UI.Interface.ISite_ProductViewMapping> Site_ProductViewMappingList
    {
      get
      {
        return this._site_ProductViewMappingList;
      }
      set
      {
        this._site_ProductViewMappingList = value;
      }
    }
    
    public override void SetupRelationships()
    {
    }
    
    public virtual object Clone()
    {
      var _productViewMapping = new global::Core.UI.ProductViewMapping();
      _productViewMapping.ProductViewMappingBusinessKey = (global::Core.UI.ProductViewMappingBusinessKey)ProductViewMappingBusinessKey.Clone();
      _productViewMapping.CustomPage = CustomPage;
      _productViewMapping.CustomLayout = CustomLayout;
      return _productViewMapping;
    }
    
    public virtual void Save()
    {
      var item = this;
      global::MetraTech.BusinessEntity.DataAccess.Persistence.StandardRepository.Instance.SaveInstance(ref item);
    }
    
    public override void CopyPropertiesFrom(global::MetraTech.BusinessEntity.DataAccess.Metadata.DataObject dataObject)
    {
      var item = dataObject as global::Core.UI.ProductViewMapping;
      CustomPage = item.CustomPage;
      CustomLayout = item.CustomLayout;
      ProductViewMappingBusinessKey = item.ProductViewMappingBusinessKey;
    }
    
    public static new System.Type[] GetKnownTypes()
    {
      var knownTypes = new List<System.Type>();
      knownTypes.Add(typeof(global::Core.UI.ProductViewMappingBusinessKey));
      return knownTypes.ToArray();
    }
  }
  
  [System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
  [System.SerializableAttribute()]
  public partial class ProductViewMappingBusinessKey : MetraTech.BusinessEntity.DataAccess.Metadata.BusinessKey, global::Core.UI.Interface.IProductViewMappingBusinessKey
  {
    
    private string _entityFullName = "Core.UI.ProductViewMapping";
    
    private string _productViewName;
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public override string EntityFullName
    {
      get
      {
        return this._entityFullName;
      }
      set
      {
        this._entityFullName = "Core.UI.ProductViewMapping";
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual string ProductViewName
    {
      get
      {
        return this._productViewName;
      }
      set
      {
        this._productViewName = value;
      }
    }
    
    public override object Clone()
    {
      var _businessKey = new ProductViewMappingBusinessKey();
      _businessKey.ProductViewName = ProductViewName;
      return _businessKey;
    }
  }
}
