//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.UI
{
  using System;
  using System.Collections.Generic;
  using System.Collections.ObjectModel;
  using System.Runtime.Serialization;
  using System.Linq;
  using MetraTech.Basic;
  using MetraTech.BusinessEntity.Core;
  using MetraTech.BusinessEntity.Core.Model;
  using MetraTech.BusinessEntity.DataAccess.Metadata;
  using MetraTech.BusinessEntity.DataAccess.Persistence;
  
  
  [System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
  [System.SerializableAttribute()]
  [System.Runtime.Serialization.KnownTypeAttribute("GetKnownTypes")]
  [MetraTech.BusinessEntity.Core.Model.ConfigDrivenAttribute()]
  public partial class Site_ReportInventory : MetraTech.BusinessEntity.DataAccess.Metadata.DataObject, global::Core.UI.Interface.ISite_ReportInventory
  {
    
    public const string FullName = "Core.UI.Site_ReportInventory";
    
    private int @__Version;
    
    public const string Property__Version = "_Version";
    
    private System.Nullable<System.DateTime> _creationDate;
    
    public const string Property_CreationDate = "CreationDate";
    
    private System.Nullable<System.DateTime> _updateDate;
    
    public const string Property_UpdateDate = "UpdateDate";
    
    private System.Nullable<System.Int32> _uID;
    
    public const string Property_UID = "UID";
    
    public const string Property_Id = "Id";
    
    private global::Core.UI.Site_ReportInventoryBusinessKey _site_ReportInventoryBusinessKey = new Site_ReportInventoryBusinessKey();
    
    private global::Core.UI.Interface.ISite _site;
    
    private global::Core.UI.Interface.IReportInventory _reportInventory;
    
    public const string Property_InternalKey = "InternalKey";
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public override int _Version
    {
      get
      {
        return this.@__Version;
      }
      set
      {
        this.@__Version = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public override System.Nullable<System.DateTime> CreationDate
    {
      get
      {
        return this._creationDate;
      }
      set
      {
        this._creationDate = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public override System.Nullable<System.DateTime> UpdateDate
    {
      get
      {
        return this._updateDate;
      }
      set
      {
        this._updateDate = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual System.Nullable<System.Int32> UID
    {
      get
      {
        return this._uID;
      }
      set
      {
        this._uID = value;
      }
    }
    
    [MetraTech.BusinessEntity.DataAccess.Metadata.BusinessKeyAttribute()]
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual global::Core.UI.Site_ReportInventoryBusinessKey Site_ReportInventoryBusinessKey
    {
      get
      {
        return this._site_ReportInventoryBusinessKey;
      }
      set
      {
        this._site_ReportInventoryBusinessKey = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual global::Core.UI.Interface.ISite Site
    {
      get
      {
        return this._site;
      }
      set
      {
        this._site = value;
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual global::Core.UI.Interface.IReportInventory ReportInventory
    {
      get
      {
        return this._reportInventory;
      }
      set
      {
        this._reportInventory = value;
      }
    }
    
    public virtual void SetRelationshipItem(object item)
    {
      if (item is global::Core.UI.Interface.ISite)
      {
        Site = item as global::Core.UI.Interface.ISite;
      }
      else
      {
        if (item is global::Core.UI.Interface.IReportInventory)
        {
          ReportInventory = item as global::Core.UI.Interface.IReportInventory;
        }
        else
        {
          throw new ApplicationException("Invalid argument");
        }
      }
    }
    
    public override void SetupRelationships()
    {
    }
    
    public virtual object Clone()
    {
      var _site_ReportInventory = new global::Core.UI.Site_ReportInventory();
      _site_ReportInventory.Site_ReportInventoryBusinessKey = (global::Core.UI.Site_ReportInventoryBusinessKey)Site_ReportInventoryBusinessKey.Clone();
      return _site_ReportInventory;
    }
    
    public virtual void Save()
    {
      var item = this;
      global::MetraTech.BusinessEntity.DataAccess.Persistence.StandardRepository.Instance.SaveInstance(ref item);
    }
    
    public override void CopyPropertiesFrom(global::MetraTech.BusinessEntity.DataAccess.Metadata.DataObject dataObject)
    {
      var item = dataObject as global::Core.UI.Site_ReportInventory;
      Site_ReportInventoryBusinessKey = item.Site_ReportInventoryBusinessKey;
    }
    
    public static new System.Type[] GetKnownTypes()
    {
      var knownTypes = new List<System.Type>();
      knownTypes.Add(typeof(global::Core.UI.Site_ReportInventoryBusinessKey));
      return knownTypes.ToArray();
    }
  }
  
  [System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
  [System.SerializableAttribute()]
  public partial class Site_ReportInventoryBusinessKey : MetraTech.BusinessEntity.DataAccess.Metadata.BusinessKey, global::Core.UI.Interface.ISite_ReportInventoryBusinessKey
  {
    
    private string _entityFullName = "Core.UI.Site_ReportInventory";
    
    private System.Guid _internalKey;
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public override string EntityFullName
    {
      get
      {
        return this._entityFullName;
      }
      set
      {
        this._entityFullName = "Core.UI.Site_ReportInventory";
      }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public virtual System.Guid InternalKey
    {
      get
      {
        return this._internalKey;
      }
      set
      {
        this._internalKey = value;
      }
    }
    
    public override object Clone()
    {
      var _businessKey = new Site_ReportInventoryBusinessKey();
      _businessKey.InternalKey = InternalKey;
      return _businessKey;
    }
  }
}
