CREATE TABLE Customer
      (InstanceId nvarchar2(64) NOT NULL,
			MetraNetId int NOT NULL,
			AccountType NVARCHAR2(200) NOT NULL,
			ExternalId NVARCHAR2(255) NOT NULL,
			ExternalIdSpace NVARCHAR2(40) NULL,
			FirstName NVARCHAR2(40) NULL,
			MiddleName NVARCHAR2(1) NULL,
			LastName NVARCHAR2(40) NULL,
			Company NVARCHAR2(255) NULL,
			Currency NVARCHAR2(10) NULL,
			City NVARCHAR2(40) NULL,
			State NVARCHAR2(40) NULL,
			ZipCode NVARCHAR2(40) NULL,
			Email NVARCHAR2(100) NULL,
			Country NVARCHAR2(100) NULL,
			Phone NVARCHAR2(40) NULL,
			HierarchyMetraNetId int NOT NULL,
			HierarchyAccountType NVARCHAR2(200) NULL,
			HierarchyExternalId NVARCHAR2(255) NOT NULL,
			HierarchyExternalIdSpace NVARCHAR2(40) NULL,
			HierarchyFirstName NVARCHAR2(40) NULL,
			HierarchyMiddleName NVARCHAR2(1) NULL,
			HierarchyLastName NVARCHAR2(40) NULL,
			HierarchyCompany NVARCHAR2(255) NULL,
			HierarchyCurrency NVARCHAR2(10) NULL,
			HierarchyCity NVARCHAR2(40) NULL,
			HierarchyState NVARCHAR2(40) NULL,
			HierarchyZipCode NVARCHAR2(40) NULL,
			HierarchyCountry NVARCHAR2(100) NULL,
			HierarchyEmail NVARCHAR2(100) NULL,
			HierarchyPhone NVARCHAR2(40) NULL,
			StartDate DATE NULL,
			EndDate DATE NULL,
			CONSTRAINT PK_Customer PRIMARY KEY(InstanceId, MetraNetId));