CREATE TABLE Problem
(
	ID INTEGER NOT NULL,
	SubsystemID INTEGER,
	Name TEXT NOT NULL,
	CONSTRAINT PK_Problem PRIMARY KEY (ID),
	CONSTRAINT FK_Problem_SubsystemID FOREIGN KEY (SubsystemID)
		REFERENCES Subsystem (ID) ON DELETE RESTRICT
);
