#define MT_USERDEFINE_DESCRIPTION "MetraTech Yet Another Acccount Class Executant\0" 
#define MT_USERDEFINE_INTERNALNAME "MTYAACExec" 
#define MT_USERDEFINEORIGFILENAME MT_USERDEFINE_INTERNALNAME 
#define MT_USERDEFINEPRODUCTNAME MT_USERDEFINE_DESCRIPTION 
#define MT_USERDEF_PROJECTNAME "YAAC Butter is good food"
