#define MT_USERDEFINE_DESCRIPTION "rscachetest\0" 
#define MT_USERDEFINE_INTERNALNAME "rscachetest\0" 
#define MT_USERDEFINEORIGFILENAME MT_USERDEFINE_INTERNALNAME 
#define MT_USERDEFINEPRODUCTNAME MT_USERDEFINE_DESCRIPTION 
#define MT_USERDEF_PROJECTNAME MT_USERDEFINE_DESCRIPTION 
