
			   CREATE TABLE %%ACCOUNT_VIEW_NAME%% (id_acc int NOT NULL, %%DDL_INNARDS%%, 
				 CONSTRAINT PK_%%ACCOUNT_VIEW_NAME%% PRIMARY KEY CLUSTERED (id_acc
				 %%KEY_COLUMNS%%), 
				 CONSTRAINT FK_%%ACCOUNT_VIEW_NAME%% FOREIGN KEY (id_acc) 
				 REFERENCES t_account)
			