
			BEGIN
				FOR I IN (SELECT 'X' FROM USER_SOURCE WHERE NAME = upper('UPDATE_%%ACCOUNT_VIEW_NAME%%'))
				LOOP
					EXECUTE IMMEDIATE 'DROP PROCEDURE ' || 'UPDATE_%%ACCOUNT_VIEW_NAME%%';
					EXIT;
				END LOOP;
			END;
			