
			BEGIN
				FOR I IN (SELECT 'X' FROM USER_TABLES WHERE TABLE_NAME = upper('%%ACCOUNT_VIEW_NAME%%'))
				LOOP
					EXECUTE IMMEDIATE 'DROP TABLE ' || '%%ACCOUNT_VIEW_NAME%%';
					EXIT;
				END LOOP;
			END;
			