
			BEGIN
				FOR I IN (SELECT 'X' FROM USER_SOURCE WHERE NAME = upper('INSERT_%%ACCOUNT_VIEW_NAME%%'))
				LOOP
					EXECUTE IMMEDIATE 'DROP PROCEDURE ' || 'INSERT_%%ACCOUNT_VIEW_NAME%%';
					EXIT;
				END LOOP;
			END;
				 