
          CREATE GLOBAL TEMPORARY TABLE TMP_AccountBatch
          (
            id_request NUMBER(10) NOT NULL,
            id_acc_ext RAW (16) NULL,
            acc_state varchar2 (2)  NOT NULL,
            acc_status_ext NUMBER(10) NULL,
            acc_vtstart DATE NULL,
            acc_vtend DATE NULL,
            nm_login nvarchar2 (255)  NOT NULL,
            nm_space nvarchar2 (40)  NOT NULL,
            tx_password nvarchar2 (1024)  NOT NULL,
            langcode varchar2 (10)  NOT NULL, /* 10 */
            profile_timezone NUMBER(10) NOT NULL,
            id_cycle_type NUMBER(10) NULL,
            day_of_month NUMBER(10) NULL,
            day_of_week NUMBER(10) NULL,
            first_day_of_month NUMBER(10) NULL,
            second_day_of_month NUMBER(10) NULL,
            start_day NUMBER(10) NULL,
            start_month NUMBER(10) NULL,
            start_year NUMBER(10) NULL,
            billable varchar2 (1)  NOT NULL, /* 20 */
            id_payer NUMBER(10) NULL,
            payer_startdate DATE NULL,
            payer_enddate DATE NULL,
            payer_login nvarchar2 (255)  NULL,
            payer_namespace nvarchar2 (40)  NULL,
            id_ancestor NUMBER(10) NULL,
            hierarchy_start DATE NULL,
            hierarchy_end DATE NULL,
            ancestor_name nvarchar2 (255)  NULL,
            ancestor_namespace nvarchar2 (40)  NULL, /* 30 */
            acc_type varchar2 (40)  NOT NULL,
            apply_default_policy varchar2 (1)  NOT NULL,
            account_currency nvarchar2 (5)  NULL,
            id_profile NUMBER(10) NOT NULL,
            login_app varchar2(10) NULL,
            id_site NUMBER(10) NULL,
            id_usage_cycle NUMBER(10) NULL,
            folder varchar2 (1)  NULL,
            account_id_as_string nvarchar2 (50)  NULL,
            auth_ancestor NUMBER(10) NULL, /* 40 */
            billable_payer varchar2 (1)  NULL,
            same_corporation varchar2 (1)  NULL,
            parent_login nvarchar2 (255) NULL,
            parent_policy NUMBER(10) NULL,
            child_policy NUMBER(10) NULL,
            id_account NUMBER(10) NULL,
            status NUMBER(10) NULL,
            hierarchy_path varchar2 (4000)  NULL,
            id_ancestor_out NUMBER(10) NULL,
            id_corporation NUMBER(10) NULL,
            ancestor_type varchar2(40) NULL
        ) on commit delete rows
        