
       insert into %%NETMETER%%..%%TARGET_TABLE%%
			(
				%%DESTCOLUMNLIST%%
			)
			select
			%%SRCCOLUMNLIST%%
			FROM %%STAGING%%..%%TEMP_TABLE%% src WITH(READCOMMITTED)
			%%FIXEDPARTWHERECLAUSE%%
			%%SKIPRECORDSPARTWHERECLAUSE%%
			AND NOT EXISTS (SELECT 1 FROM %%NETMETER%%..%%TARGET_TABLE%% 
			dest WITH(READCOMMITTED) WHERE (dest.id_acc=src.%%DEST_ACCT_ID_COL_NAME%%
			%%KEYPARTWHERECLAUSE%%))
			