
				update dest set %%UPDATECOLLIST%% from %%NETMETER%%..%%TARGET_TABLE%%
				dest WITH(READCOMMITTED) INNER JOIN %%STAGING%%..%%TEMP_TABLE%% 
				src WITH(READCOMMITTED) ON dest.id_acc = src.%%DEST_ACCT_ID_COL_NAME%%
				%%KEYPARTWHERECLAUSE%% %%FIXEDPARTWHERECLAUSE%% %%SKIPRECORDSPARTWHERECLAUSE%%
			