
SELECT 
/*  __GET_ADVANCE_RECUR_CHARGES__ */
tmp.c_RCActionType,
tmp.c__AccountID,
tmp.c__PayingAccount,
tmp.c_BillingIntervalStart, 
tmp.c_BillingIntervalEnd,
tmp.c_NextBillingIntervalStart,
tmp.c_NextBillingIntervalEnd,
tmp.c__PriceableItemInstanceID, 
tmp.c__PriceableItemTemplateID,
tmp.c__ProductOfferingID,
tmp.c_RCIntervalStart, 
tmp.c_RCIntervalEnd, 
tmp.c__SubscriptionID,
tmp.c_SubscriptionStart,
tmp.c_SubscriptionEnd,
tmp.c_RCIntervalSubscriptionStart,
tmp.c_RCIntervalSubscriptionEnd,
tmp.c_Advance,
tmp.c_ProrateOnSubscription,
tmp.c_ProrateInstantly,
tmp.c_ProrateOnUnsubscription,
tmp.c_ProrationCycleLength,
tmp.c_BilledRateDate,
  tmp.c_UnitValue,
  CASE WHEN tmp.c_UnitValueStart < {ts '1970-01-01 00:00:00'} THEN {ts '1970-01-01 00:00:00'} ELSE tmp.c_UnitValueStart END as c_UnitValueStart,
  tmp.c_UnitValueEnd,
	tmp.c_RatingType
FROM %%%TEMP_TABLE_PREFIX%%%tmp_recurring_charges tmp
