
    BEGIN
    /* indexes created in dbinstall/productcatalog */
    EXECUTE IMMEDIATE 'ANALYZE TABLE tmp_nrcs ESTIMATE STATISTICS SAMPLE 40 PERCENT';
    EXECUTE IMMEDIATE 'ANALYZE INDEX tmp_nrcs_idx_prop ESTIMATE STATISTICS SAMPLE 40 PERCENT';
    EXECUTE IMMEDIATE 'ANALYZE INDEX tmp_nrcs_idx_tt_vt_start ESTIMATE STATISTICS SAMPLE 40 PERCENT';
    END;
  		