#############################################################
#Generated on Thu Jul  1 15:55:33 1999
#############################################################


RELATIVEDIR := Shared\ConfigLoader\test

SRC := test.cpp

INCLUDEDIRS := $(OUTPUTROOT)\$(RELATIVEDIR)\.. $(OUTPUTROOT)\$(RELATIVEDIR)\..\..\include $(OUTPUTROOT)\$(RELATIVEDIR)\..\..\..\include

MIDL_INCLUDEDIRS := 

DEFINES := 

EXTRA_LIBS := 

EXTRA_SYS_LIBS := 

EXENAME := cltest

OVERRIDE_UNICODE_CPP_FLAGS := 1
TEST_UTILITY :=1