
		BEGIN
			if OBJECT_ID('%%DELTA_INSERT_TABLE_NAME%%') is null
			BEGIN
				CREATE TABLE %%DELTA_INSERT_TABLE_NAME%% %%DDL%%
			END
			if OBJECT_ID('%%DELTA_DELETE_TABLE_NAME%%') is null
			BEGIN
				CREATE TABLE %%DELTA_DELETE_TABLE_NAME%% %%DDL%%
			END
		END
		