//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetraTech.ExpressionEngine {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MetraTech.ExpressionEngine.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;All&gt;.
        /// </summary>
        internal static string AllChoice {
            get {
                return ResourceManager.GetString("AllChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The BaseType must be {0} for this action not {1}.
        /// </summary>
        internal static string BaseTypeIncorrect {
            get {
                return ResourceManager.GetString("BaseTypeIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Category.
        /// </summary>
        internal static string CurrencyCategory {
            get {
                return ResourceManager.GetString("CurrencyCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property{0}.
        /// </summary>
        internal static string DefaultNewPropertyName {
            get {
                return ResourceManager.GetString("DefaultNewPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Property Name: &apos;{0}&apos;.
        /// </summary>
        internal static string DuplicatePropertyName {
            get {
                return ResourceManager.GetString("DuplicatePropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration FixedCategory not specified.
        /// </summary>
        internal static string EnumCategoryNotSpecified {
            get {
                return ResourceManager.GetString("EnumCategoryNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration.
        /// </summary>
        internal static string Enumeration {
            get {
                return ResourceManager.GetString("Enumeration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration Category.
        /// </summary>
        internal static string EnumerationCategory {
            get {
                return ResourceManager.GetString("EnumerationCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration &apos;{0}&apos; is not a Unit of Measure.
        /// </summary>
        internal static string EnumerationIsNotUoM {
            get {
                return ResourceManager.GetString("EnumerationIsNotUoM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration NameSpace not specified.
        /// </summary>
        internal static string EnumNamespaceNotSpecified {
            get {
                return ResourceManager.GetString("EnumNamespaceNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0} [{1}]&quot;.
        /// </summary>
        internal static string ExceptionMessage {
            get {
                return ResourceManager.GetString("ExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression is valid..
        /// </summary>
        internal static string ExpressionIsValid {
            get {
                return ResourceManager.GetString("ExpressionIsValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading {0}.
        /// </summary>
        internal static string FileLoadError {
            get {
                return ResourceManager.GetString("FileLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Currency.
        /// </summary>
        internal static string FixedCurrency {
            get {
                return ResourceManager.GetString("FixedCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in Property  &apos;{0}&apos; in PropertyBag &apos;{1}&apos;.
        /// </summary>
        internal static string InPropertySuffix {
            get {
                return ResourceManager.GetString("InPropertySuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient description.
        /// </summary>
        internal static string InsufficientDescription {
            get {
                return ResourceManager.GetString("InsufficientDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid default value.
        /// </summary>
        internal static string InvalidDefaultValue {
            get {
                return ResourceManager.GetString("InvalidDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Name.
        /// </summary>
        internal static string InvalidName {
            get {
                return ResourceManager.GetString("InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name not specified.
        /// </summary>
        internal static string NameNotSpecified {
            get {
                return ResourceManager.GetString("NameNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No description.
        /// </summary>
        internal static string NoDescription {
            get {
                return ResourceManager.GetString("NoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PropertyBag.
        /// </summary>
        internal static string PropertyBag {
            get {
                return ResourceManager.GetString("PropertyBag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        internal static string PropertyBagProperty {
            get {
                return ResourceManager.GetString("PropertyBagProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos;: .
        /// </summary>
        internal static string PropertyMessagePrefix {
            get {
                return ResourceManager.GetString("PropertyMessagePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Property.
        /// </summary>
        internal static string QuantityProperty {
            get {
                return ResourceManager.GetString("QuantityProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return;.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the &apos;{0}&apos; Enumeration Category.
        /// </summary>
        internal static string UnableToFindEnumCategory {
            get {
                return ResourceManager.GetString("UnableToFindEnumCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unaable to find the &apos;{0}&apos; EnumNamespace.
        /// </summary>
        internal static string UnableToFindEnumNamespace {
            get {
                return ResourceManager.GetString("UnableToFindEnumNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find &apos;{0}&apos; property in the current context.
        /// </summary>
        internal static string UnableToFindProperty {
            get {
                return ResourceManager.GetString("UnableToFindProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find Unit of Measure item&apos;{0}&apos;.
        /// </summary>
        internal static string UnableToFindUnitOfMeasureItem {
            get {
                return ResourceManager.GetString("UnableToFindUnitOfMeasureItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find Unit of Measure category &apos;{0}&apos;.
        /// </summary>
        internal static string UnableToFinUnitOfMeasureCategory {
            get {
                return ResourceManager.GetString("UnableToFinUnitOfMeasureCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit of Measure.
        /// </summary>
        internal static string UnitOfMeasure {
            get {
                return ResourceManager.GetString("UnitOfMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit of Measure Category.
        /// </summary>
        internal static string UnitOfMeasureCategory {
            get {
                return ResourceManager.GetString("UnitOfMeasureCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit of Measure FixedCategory can not be a general enumeration, it must be a unit of measure.
        /// </summary>
        internal static string UnitOfMeasureCategoryMustBeUom {
            get {
                return ResourceManager.GetString("UnitOfMeasureCategoryMustBeUom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit of Measure FixedCategory not specified.
        /// </summary>
        internal static string UnitOfMeasureCategoryNotSpecified {
            get {
                return ResourceManager.GetString("UnitOfMeasureCategoryNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit of Measure &apos;{0}&apos; Namespace must be set to MetraTech.
        /// </summary>
        internal static string UnitOfMeasureNamespaceMustBeMetraTech {
            get {
                return ResourceManager.GetString("UnitOfMeasureNamespaceMustBeMetraTech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit of Measure not specified.
        /// </summary>
        internal static string UnitOfMeasureNotSpecified {
            get {
                return ResourceManager.GetString("UnitOfMeasureNotSpecified", resourceCulture);
            }
        }
    }
}
