/**************************************************************************
* Copyright 1997-2002 by MetraTech
* All rights reserved.
*
* THIS SOFTWARE IS PROVIDED "AS IS", AND MetraTech MAKES NO
* REPRESENTATIONS OR WARRANTIES, EXPRESS OR IMPLIED. By way of
* example, but not limitation, MetraTech MAKES NO REPRESENTATIONS OR
* WARRANTIES OF MERCHANTABILITY OR FITNESS FOR ANY PARTICULAR PURPOSE
* OR THAT THE USE OF THE LICENCED SOFTWARE OR DOCUMENTATION WILL NOT
* INFRINGE ANY THIRD PARTY PATENTS, COPYRIGHTS, TRADEMARKS OR OTHER
* RIGHTS.
*
* Title to copyright in this software and any associated
* documentation shall at all times remain with MetraTech, and USER
* agrees to preserve the same.
*
***************************************************************************/




typedef [uuid(19cb5982-2220-4201-9b46-f92e34acc0ab), version(1.0)]
enum {
  NO_CYCLE = 0,
  MONTHLY_CYCLE = 1,
  ONDEMAND_CYCLE = 2,
  DAILY_CYCLE = 3,
  WEEKLY_CYCLE = 4,
  BIWEEKLY_CYCLE = 5,
  SEMIMONTHLY_CYCLE = 6,
  QUARTERLY_CYCLE = 7,
  ANNUALLY_CYCLE = 8,
  SEMIANNUALLY_CYCLE = 9
} MTUsageCycleType;
