
import "oaidl.idl";
import "ocidl.idl";

import "MTConfig.idl";
import "MTConfigProp.idl";

[
	uuid(3B5873C0-AAFA-11D2-A1D5-006008C0E24A),
	version(1.0),
	helpstring("Configuration 1.0 Type Library")
]
library MTConfigLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	interface IMTConfig;
	interface IMTConfigProp;
	interface IMTConfigPropSet;
	interface IMTConfigAttribSet;
};
