/**************************************************************************
 * @doc MTPIPELINELIB
 *
 * Copyright 1998 by MetraTech Corporation
 * All rights reserved.
 *
 * THIS SOFTWARE IS PROVIDED "AS IS", AND MetraTech Corporation MAKES
 * NO REPRESENTATIONS OR WARRANTIES, EXPRESS OR IMPLIED. By way of
 * example, but not limitation, MetraTech Corporation MAKES NO
 * REPRESENTATIONS OR WARRANTIES OF MERCHANTABILITY OR FITNESS FOR ANY
 * PARTICULAR PURPOSE OR THAT THE USE OF THE LICENSED SOFTWARE OR
 * DOCUMENTATION WILL NOT INFRINGE ANY THIRD PARTY PATENTS,
 * COPYRIGHTS, TRADEMARKS OR OTHER RIGHTS.
 *
 * Title to copyright in this software and any associated
 * documentation shall at all times remain with MetraTech Corporation,
 * and USER agrees to preserve the same.
 *
 * Created by: Derek Young
 * $Header$
 ***************************************************************************/

import "MTNameID.idl";

[
	object,
	uuid(50abbfb0-2420-11d3-8db3-00c04f484788),
	dual,
	helpstring("IMTDummy Interface"),
	pointer_default(unique)
]
interface Dummy : IDispatch
{
};



[
	uuid(55f10a40-2420-11d3-8db3-00c04f484788),
	version(1.0),
	helpstring("MetraTech NameID 1.0 Type Library")
]
library MTNAMEIDLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	interface IMTNameID;
};
