/**************************************************************************
 * @doc MTNAMEID
 *
 * Copyright 1998 by MetraTech Corporation
 * All rights reserved.
 *
 * THIS SOFTWARE IS PROVIDED "AS IS", AND MetraTech Corporation MAKES
 * NO REPRESENTATIONS OR WARRANTIES, EXPRESS OR IMPLIED. By way of
 * example, but not limitation, MetraTech Corporation MAKES NO
 * REPRESENTATIONS OR WARRANTIES OF MERCHANTABILITY OR FITNESS FOR ANY
 * PARTICULAR PURPOSE OR THAT THE USE OF THE LICENSED SOFTWARE OR
 * DOCUMENTATION WILL NOT INFRINGE ANY THIRD PARTY PATENTS,
 * COPYRIGHTS, TRADEMARKS OR OTHER RIGHTS.
 *
 * Title to copyright in this software and any associated
 * documentation shall at all times remain with MetraTech Corporation,
 * and USER agrees to preserve the same.
 *
 * Created by: Derek Young
 * $Header$
 *
 * name ID lookup
 ***************************************************************************/

// MTNameID.idl : IDL source for MTNameID.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (MTNameID.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

// ----------------------------------------------------------------
// Object: MTNameID
// Prog ID: MetraPipeline.MTNameID.1
// Description: This interface allows plug-ins to retrieve the ID for
//              a property names or the property name for a given ID.
// ----------------------------------------------------------------
[
	object,
	uuid(49A30E80-3EAF-11D2-A1C5-006008C0E24A),
	dual,
	helpstring("IMTNameID Interface"),
	pointer_default(unique)
]
interface IMTNameID : IDispatch
{
  // Retrieve a property ID for a given property name.
  [id(1), helpstring("method GetNameID")] HRESULT GetNameID(BSTR name, [out,retval] long * id);

  // Retrieve a property name for a given property ID.
  // This method is inefficient and should be used sparingly.
  [id(2), helpstring("method GetName")] HRESULT GetName(long id, [out, retval] BSTR * name);
};
