/**************************************************************************
 * Copyright 2002 by MetraTech Corporation
 * All rights reserved.
 *
 * THIS SOFTWARE IS PROVIDED "AS IS", AND MetraTech Corporation MAKES
 * NO REPRESENTATIONS OR WARRANTIES, EXPRESS OR IMPLIED. By way of
 * example, but not limitation, MetraTech Corporation MAKES NO
 * REPRESENTATIONS OR WARRANTIES OF MERCHANTABILITY OR FITNESS FOR ANY
 * PARTICULAR PURPOSE OR THAT THE USE OF THE LICENSED SOFTWARE OR
 * DOCUMENTATION WILL NOT INFRINGE ANY THIRD PARTY PATENTS,
 * COPYRIGHTS, TRADEMARKS OR OTHER RIGHTS.
 *
 * Title to copyright in this software and any associated
 * documentation shall at all times remain with MetraTech Corporation,
 * and USER agrees to preserve the same.
 *
 * Created by: Ralf Boeck
 * $Header$
 *
 ***************************************************************************/

// include standard IDL files
import "oaidl.idl";
import "ocidl.idl";

import "MTSessionSet.idl";
import "MTConfig.idl";

// ----------------------------------------------------------------
// Interface: IMTPipelineExecutant
// Description: interface called by the ComPlusPlugin
// ----------------------------------------------------------------
[
  object,
  uuid(89D7F102-E222-4cc6-9EA7-014CCA9A14CD),
  dual,
  helpstring("IMTPipelineExecutant Interface"),
  pointer_default(unique)
]
interface IMTPipelineExecutant : IDispatch
{
  // Description: Configure the executant.
  //              Since the executant is stateless (meaning it will be destroyed
  //              after each method call), any configuration state that will be used
  //              in ProcessSessions must be returned in the configState variant.
  //              The configState will be stored externally and passed into every
  //              ProcessSessions call.
  //
  // Arguments: systemContext - interface used to retrieve many objects used by the
  //                            plug-in during processing.
  //            propSet - executant specific configuration, read from ComPlusPlugin
  //            configState - optional state, will be passed into ProcessSessions
  [id(1), helpstring("Configure executant")]
  HRESULT Configure(
    [in] IDispatch * systemContext,
    [in] IMTConfigPropSet * propSet,
    [out, retval] VARIANT * configState);

  // Description: The body of this method works with each of the sessions
  //              within the session set.
  //
  // Arguments: sessions - Set of sessions that the executant should process.
  //            systemContext - interface used to retrieve many objects
  //                            (passed-in for convenience)
  //            configState - state returned from Configure method
  [id(2), helpstring("Process a set of sessions")]
  HRESULT ProcessSessions(
    [in] IMTSessionSet * sessions,
    [in] IDispatch * systemContext,
    [in] VARIANT configState);
};
