SUBDIRS = meterapi \
	  msixapi \
	  localmode \
	  mtsdk \
	  autosdklib \
          autosdk

include $(BUILD_ROOT)/Build/unix/base.mak

default: subdirs_all

clean: subdirs_clean

include $(BUILD_ROOT)/Build/unix/subdirs.mak


