/* Generated with Author-it 5.5.264.13693  9/14/2012 4:07:55 PM */
Page=new Array();Page[0]=new Array("Quick Links...","Welcome to MetraView® Help. This information resource is designed to provide you with step-by-step instructions for using MetraView to manage all aspects of your account &#8211; including such tasks as viewing account balances, checking previous payments, seeing details about your charges, and changing account information.","Accessing MetraView Help","At the top-right of each MetraView application window, you'll see the Help and Logout buttons.","Click Help to receive context-sensitive help on the currently displayed MetraView application screen. If the topic does not contain exactly what you're looking for, try looking for related topics on the Help Index or Search tabs.","MetraView Common Tasks","Dashboard/Home","Bill &amp; Payments","My Reports","Account Info","My Subscriptions","Welcome to MetraView Help","mv-default.hlp.htm");
Page[1]=new Array("The MetraView Dashboard contains a high-level overview of the key account information and is usually the landing page when you log in to your account. The dashboard displays the following:  ","Your user profile information, including your account name and account number.","Payment information summary, including the last posted payment, adjustments and the amount due","Your default and favorite reports, including your personal saved searches. ","Account usage details by product and by department. ","Access to your account information. ","Subscriptions you are subscribed to as well as available product offerings. ","About the MetraView Dashboard","17897.htm");
Page[2]=new Array("<br />","Changing a Password","To change your MetraView password:","In MetraView, select Account Info » Change Password. ","Type your current password and your new password and click OK. ","Use this new password the next time you log on. ","Depending on your site's security, you may be required to change a temporary password when logging in.","Type your old password.","Type and retype a new password and click OK.","About Strong Passwords","A strong password is one that cannot be easily guessed. The strong password requirements can be changed by your administrator. By default the characteristics of a strong password are: ","must be at least 7 characters","must contain at least one lowercase letter, one uppercase letter and one digit ","special characters are optional","About Unique Passwords","If you are changing your password, you must choose a new unique password. A unique password is one that you have not used before. Typically, you must use a minimum number of passwords before you can repeat a password. The number of passwords that are unique setting is maintained by your administrator. By default, you must use 4 unique passwords before you can repeat a password. ","Logging in After Being Locked Out","You can be locked out of MetraNet for several different reasons:","forgotten password ","too many login attempts","account inactivity","expired password","If you have been locked out of MetraNet,  you must contact your administrator to reset your password. The administrator will give you a new password to use to log in. Once you have logged in, you need to change your password. ","Resetting and Changing a Password","MV-ChangePassword.hlp.htm");
Page[3]=new Array("MetraView provides you with a full range of tools to manage your account. ","Basics","Resetting and Changing a Password","Viewing Your Account Details","Editing Your Account","Changing Your Regional Settings","Subscriptions","Viewing Your Subscriptions","Reviewing Product Offering Details","Changing or Adding a Subscription","Unsubscribing","Bills","Viewing an Online Bill","Viewing Past Bills","Exporting Data ","Filtering and Sorting Data","Searching for Information","Saving a Search ","Making a Payment","Adding a Credit Card","Entering Bank Information","Viewing Payment History","MetraView Common Tasks","18380.htm");
Page[4]=new Array("You can change the display of the data that appears when you view Usage, Payment History, or Adjustments in MetraView. If the data appears in a grid layout, the Configure Filters window allows you to modify what properties appear in the search and filter on the page. ","To configure the search and filters: ","Select the Configure Filters icon in the top right of the search or filter section of the grid. ","The configuration options appear. ","Check the elements you want to include in your filter. If you cannot uncheck a property, it was configured to always appear in your search or filter. ","Click OK. ","After filtering, searching, and sorting, you can save this way of viewing data to use with other bill data and periods. Saving a Custom Search in MetraView","Filtering, Searching and Sorting Data on an Online Bill","18634.htm");
Page[5]=new Array("To export data: ","In MetraView or MetraCare, filter the data you want to export. ","At the bottom of the grid, select Export. ","Select one of the following: ","Export Current Page Only","Export All Records","Select Export. ","If you are exporting a set of data where there is child data, you need to select which children you want to include in the export. If you are exporting to Excel, the child data is included on separate tabs. If you are exporting to a flat file, a separate file is used for each child. ","Choose whether to open the resulting file, or save it. The data is saved in CSV format. ","Exporting Data to a CSV File","17914.htm");
Page[6]=new Array("The Bill &amp; Payments page allows you to view information about your current charges, past payments, credits and previous balance. Details about any other accounts for which you are the payer appear on this page also. ","Your bill may show charges in the current month that have not been finalized. Check at the bottom of the Bill &amp; Payments page for the status of your current charges. If there are estimated charges, you do not have to pay for them yet because they may still change.","If you are a subscriber, but someone else pays your bill, your usage details are not shown on this page. To see information about your usage, click My Reports. ","Payment information, including your current balance and due date appear at the top of the page. ","In addition to viewing the details of your bill, you can choose to do any of the following:","Make a payment ","View your billing history","View and change payment methods","View payment history","Download invoices and reports","About Your Bill","Details about your bill and account, as well as charges by current subscriptions, are found in the Payments, Credits &amp; Adjustments section. ","From the Select Interval list, you can select a previous billing period to view. ","There are usually two ways to view your bill:","The Charges view shows a summary of charges for the services you subscribe to.","Click the link for a charge item to see a detailed usage page.","The Detailed view shows information about other accounts you pay for, if applicable. It shows your account in the context of your department or other cost center in your organization.","Click the drill-down icons to your department. If you're the payer for other accounts you can also see their accounts in the context of your organization. ","Here is a simple example of an individual drilling down to her department in an organization. If Pam was responsible for other accounts, she would see their names and charges under the applicable departments.","Bills &amp; Payments","bill.hlp.htm");
Page[7]=new Array("To set up or edit your account information: ","In MetraView, select the Account Info tab. ","Or select Bill &amp; Payments » Edit Account. ","Edit the information you want to change. Bold fields are required. ","Click OK. ","Editing Your Account Information","18623.htm");
Page[8]=new Array("When you drill down to the individual subscriptions and adjustments, you will see details in a sortable, pageable, and exportable grid. You can use the search filters to narrow the data you see on this page, create a Saved Search to easily find this data again, and export data to a CSV file. For more information, see Filtering, Searching and Sorting Data on an Online Bill and Exporting Data to a CSV File. ","To see a bill from a different billing period: ","In the Select Interval section, click the dropdown and select the interval you want to use. ","About the Summary View of Your Payments, Credits and Adjustments","The Summary View displays the total cost of usage per subscription for which your logon ID is expected to pay. Select a subscription to see the cost and usage details for just that subscription. If you want to break down the usage by users on your account, select Detailed View. ","About the Detailed View of Your Payments, Credits and Adjustments","The Detailed View displays the total cost of usage per subscription per user. Select the subscription to see the cost and usage details for a user in your hierarchy. The charge details are divided by individual users associated with the account. Select the user you want to view to see a list of their subscriptions. Select the subscription to see that user's cost, usage, and adjustment details.  ","<br /><br />","Displaying Payments, Credits and Adjustments Details","18523.htm");
Page[9]=new Array("If your account has had adjustments made to it, you can view those details on the Adjustment Details page. ","To view adjustments: ","In MetraView, select Bill and Payments. ","Under Payments, Credits and Adjustments, select the adjustment you want to see. The Adjustment Details page appears. ","You can use the search filters to narrow the data you see on this page, create a Saved Search to easily find this data again, and export data to a CSV file. For more information, see Filtering, Searching and Sorting Data on an Online Bill and Exporting Data to a CSV File. ","Click Back to return to the Bill Summary page. ","Viewing Adjustment Details","adjustmentdetails.hlp.htm");
Page[10]=new Array("To make a payment using MetraView: ","In MetraView select the Bills &amp; Payments » Make a Payment. ","In Payment Amount, choose whether to pay the total amount due or a portion of the total. ","In Payment Method, choose whether to pay with your bank account or by credit card. If you have already added a payment method, choose it in the Existing Payment Method drop down. ","In Payment Date, choose whether to pay the bill immediately or on a future date. ","Click Next. A summary page appears.","Verify that the information is correct and click Next. The Confirmation page appears. ","Related Topics","Reviewing Payment Information","View Billing History","View, Add or Change Your Payment Method","View Your Payment History","Download an Invoice or a Report","Making a Payment in MetraView","MakePayment.hlp.htm");
Page[11]=new Array("The payment details page allows you to view the details of your payment before you confirm it. You can see the amount you chose to pay and the payment method you chose to use. Click Next to Confirm the payment. ","Reviewing Payment Information","ReviewPayment.hlp.htm");
Page[12]=new Array("The payment confirmation page allows you to view the details of your payment after it has been confirmed. You can see the amount you chose to pay and the payment method you chose to use. ","Payment Confirmation","PayFinal.hlp.htm");
Page[13]=new Array("The Billing History page displays a chart where the horizontal axis represents the different billing periods and the vertical axis represents the amount charged for a particular billing period. This graph is useful for seeing how usage and charges have increased or decreased over time. ","To view a graphical history of your bills: ","In MetraView, select Bills &amp; Payments » Billing History. ","Viewing Billing History","history.hlp.htm");
Page[14]=new Array("The Payment Methods page allows you to define how you want to pay your bill. You can choose to pay with a credit card or use ACH, an electronic funds transfer system using your bank account.","ACH stands for Account Clearing House and is used to process payments through your bank from your checking or savings account. To add a payment method using ACH, you need to know your bank's routing number and your checking or savings account number. ","Viewing a Payment Method","ViewPaymentMethods.hlp.htm");
Page[15]=new Array("To define ACH electronic funds transfer system as a payment method for your account: ","Select Bill &amp; Payments » Payment Methods. ","Click Add ACH. ","Enter your personal information. ","Select a Priority. Priority determines the order in which the payment method appears in your list of payment methods. If this is your first payment method, use 1. If you already have a payment method defined, change this number to reflect the position you want it to take in the list. Enter 2 for it to appear second, and so on. ","Enter information about the ACH: ","Enter the bank Account Number. ","Enter your bank's Routing Number. ","You can find your account and routing number on your bank statement or on your checks. Routing and Account Number Example ","Select the Account Type you are using: Savings or Checking. ","Click OK. The payment method is added to your account. ","You can add more than one ACH to your account and choose which one to use when you pay your bill. ","Adding an ACH","MV-ACHAdd.hlp.htm");
Page[16]=new Array("To update an ACH: ","Select Bill &amp; Payments » Payment Methods. ","Select the ACH you want to update and click the edit icon in the Actions column. ","Make your changes and click OK in the confirmation window. ","The changes you made to the ACH appear. ","Updating an ACH","ACHUpdate.hlp.htm");
Page[17]=new Array("To remove an ACH: ","Select Bill &amp; Payments » Payment Methods. ","Select the ACH you want to remove and click the red X in the Actions column. ","Click OK in the confirmation window. ","The ACH is removed from the list of payment methods. ","Removing an ACH","ACHRemove.hlp.htm");
Page[18]=new Array("To define a credit card as a payment method to your account: ","Select Bill &amp; Payments » Payment Methods. ","Click Add Credit Card. ","Enter your personal information. ","Select a Priority. Priority determines the order in which the payment method appears in your list of payment methods. If this is your first payment method, use 1. If you already have a payment method defined, change this number to reflect the position you want it to take in the list. Enter 2 for it to appear second, and so on. ","Enter the credit card information: ","Select the Credit Card Type","Enter the Card Number","Enter the CVN Number. ","Enter the card's Expiration Date ","Click OK. The payment method is added to your account. ","You can add more than one credit card to your account and choose which one to use when you pay your bill. ","Adding a Credit Card","MV-CreditCardAdd.hlp.htm");
Page[19]=new Array("To update a credit card in your account: ","Select Bill &amp; Payments » Payment Methods. ","Select the ACH you want to update and click the edit icon in the Actions column. ","Make your changes and click OK in the confirmation window. ","Updating a Credit Card","CreditCardUpdate.hlp.htm");
Page[20]=new Array("To remove a credit card: ","Select Bill &amp; Payments » Payment Methods. ","Select the credit card you want to remove and click the red X in the Actions column. ","Click OK in the confirmation window. ","The credit card is removed from the list of payment methods. ","Removing a Credit Card","creditcardremove.hlp.htm");
Page[21]=new Array("Routing and Account Number Example","18508.htm");
Page[22]=new Array("The Payment History page displays all the past payments you have made with this account. ","To view payment history: ","In MetraView, select Bill &amp; Payments » Payment History. A list of all your recent payments appears. ","You can use the search filters to narrow the data you see on this page, create a Saved Search to easily find this data again, and export data to a CSV file. For more information, see Filtering, Searching and Sorting Data on an Online Bill and Exporting Data to a CSV File. ","Viewing Payment History","ViewPaymentHistory.hlp.htm");
Page[23]=new Array("To download an invoice or a report: ","Select Bills &amp; Payments » Downloads. ","A list of available PDFs appears. ","Select the interval for the invoice or bill you want to download. .","The recommended maximum size for report files is less than 3 MB. Files exceeding this size may require excessive time to download.","Downloading Invoices and Reports","DownloadInvoices.hlp.htm");
Page[24]=new Array("The My Reports page shows a list of the product offerings you are subscribed to and your usage charges during a particular time span. If your bills are for a business, you may also see the usage for the individuals in the group you are responsible for. This is called a hierarchy view.","You can toggle between Summary and Detailed views of your subscription usage:","The summary view displays the total usage for each service you subscribe to. ","The detailed view displays the usage for any other accounts in your hierarchy for which you are the payer.","To see details about your usage: ","In MetraView, select the My Reports tab. The current Usage report appears. A list of other Usage reports appears in the Usage Report widget in the left column. ","If you want to see a different date span, select different start and end dates in View usage from and click Go. ","A summary of the usage between the dates you selected appears. ","Click Detailed View or Summary View to toggle between a detailed view or a summary view of the charges.","If you manage other subscribers - say, in a department or other cost center - the detailed view of charges breaks usage out by each paying account.","Select individual charges for each calculation in a product offering. You can see even more details about these charges by selecting the expander to the left of the charge. ","Select the My Reports tab to return to the usage report. ","When you view usage details, you can filter the results and then you can save the filter for the next time. Saving a Custom Search in MetraView","My Reports","usage.hlp.htm");
Page[25]=new Array("As a MetraView user, you may have a preferred way to view usage information about your charges or the charges of accounts you manage. When you save such a view it appears under My Reports.","A saved report remembers the search and filter values you previously set up to view information. It doesn't remember the time period for which you were viewing this information. When you open a saved report, you will often want to select a billing period previous to the current period. (There may not be any available usage data in the current period, depending on how your bills are set up).","Saving a report does not save its results. As your usage changes from billing period to billing period, you can compare your usage using the same viewing criteria.","Viewing a Saved Report","usage.hlp.htm#o17929");
Page[26]=new Array("As a subscriber, you can create a personal view of data and use it again. A saved report allows you to save search and filter values for reuse at a later time. These searches are called reports and are saved in the My Reports area on the MetraView dashboard and on the My Reports tab.","Saving a report does not save its results.","As your usage changes from billing period to billing period, you can compare your usage using the same search criteria.","To save a report: ","Set up your search and filtering options as you want to save them.","Select the Save Your Search icon in the top right of the search or filter section of the grid. ","If this icon is not on your grid, the grid does not have the ability to save a search. ","Type a name and description for your search. ","Click OK. ","The saved search is available from My Reports on your Home or My Reports Usage page (next time you go to the page).","Deleting Saved Searches","To delete a report: ","Select the Load Saved Search icon in the top right of the search or filter section of the grid. ","@ ","Click the red X next to the search you want to delete.","Confirm the deletion. ","Saving a Report","usage.hlp.htm#o17917");
Page[27]=new Array("You may have links to specialized reports that have been set up for you by your company or cost center. They appear in the section Shared Reports.","A shared report is one that you share with your colleagues in your cost center or company. It contains any kind of custom data. If there are no reports listed under the Shared Reports, none are currently available to view.","Viewing a Shared Report","usage.hlp.htm#o22953");
Page[28]=new Array("The detailed view displays the usage for any other accounts in your hierarchy for which you are the payer.","Viewing Details","details.hlp.htm");
Page[29]=new Array("The Account Info page lets you enter and update basic account information.","This page may not be visible in some cases.","To set up or edit your account information: ","In MetraView, select the Account Info tab. ","Or select Bill &amp; Payments » Edit Account. ","Edit the information you want to change. Bold fields are required. ","Click OK. ","Account Info","accountinfo.hlp.htm");
Page[30]=new Array("<br />","Changing a Password","To change your MetraView password:","In MetraView, select Account Info » Change Password. ","Type your current password and your new password and click OK. ","Use this new password the next time you log on. ","Depending on your site's security, you may be required to change a temporary password when logging in.","Type your old password.","Type and retype a new password and click OK.","About Strong Passwords","A strong password is one that cannot be easily guessed. The strong password requirements can be changed by your administrator. By default the characteristics of a strong password are: ","must be at least 7 characters","must contain at least one lowercase letter, one uppercase letter and one digit ","special characters are optional","About Unique Passwords","If you are changing your password, you must choose a new unique password. A unique password is one that you have not used before. Typically, you must use a minimum number of passwords before you can repeat a password. The number of passwords that are unique setting is maintained by your administrator. By default, you must use 4 unique passwords before you can repeat a password. ","Logging in After Being Locked Out","You can be locked out of MetraNet for several different reasons:","forgotten password ","too many login attempts","account inactivity","expired password","If you have been locked out of MetraNet,  you must contact your administrator to reset your password. The administrator will give you a new password to use to log in. Once you have logged in, you need to change your password. ","Resetting and Changing a Password","MV-ChangePassword.hlp_1.htm");
Page[31]=new Array("If you are a Bill Manager for other accounts, you may have permission to view their bills in MetraView. In this case, when you log in you will see a list of one or more managed bills account names.","To view your own account:","Select the Home tab or another tab.","To view a managed bill account:","Select the Home tab.","Choose an account from the Select Bill list.","Not sure which account you are viewing? ","Always check the displayed account name.","If you make changes to others accounts, your user information is saved in the audit logs. For example, if you are editing Karen's account, the audit information will record &quot;Admin Assistant logged in as Karen.&quot; ","To log in as yourself or to view another managed bill account, you must log out first.","Selecting a Managed Online Bill Account","23843.htm");
Page[32]=new Array("To set up or edit your account information: ","In MetraView, select the Account Info tab. ","Or select Bill &amp; Payments » Edit Account. ","Edit the information you want to change. Bold fields are required. ","Click OK. ","Editing Your Account Information","18623_1.htm");
Page[33]=new Array("The changes you made have been updated in your account. ","Account Info Update Successful","AccountInfoSuccess.hlp.htm");
Page[34]=new Array("Your password has been successfully changed. ","Change Password Successful","ChangePasswordSuccess.hlp.htm");
Page[35]=new Array("Use the Regional Settings page to define the time zone in which you are located. Defining your time zone ensures accurate start and end times and is especially important when your usage rates vary at different points during the day. ","To change your time zone:","In MetraView, select the Account Info » Regional Settings. ","Select the Time Zone you want to use. ","Click OK. ","Changing Regional Settings","RegionalSettings.hlp.htm");
Page[36]=new Array("There are three standard options for invoices: ","None: PDF invoices are not created for your account. ","Standard: A standard bill containing the summary of your charges is saved as a PDF and is available in the My Reports section of MetraView. ","Detailed: A detailed bill containing detailed information about your charges is saved as a PDF and is available in the My Reports section of MetraView. ","To change the type of bills and invoices that are prepared: ","In MetraView, select Account Info » Invoice Method. ","In Paper Invoice, choose the type of invoice you want to have appear in your My Reports widget and click OK. ","Choosing an Invoice Method","InvoiceMethod.hlp.htm");
Page[37]=new Array("On the My Subscriptions page, you can see the product offerings that are available to you.","This page may not be visible in some cases. Depending on how your account is set up, you may be able to see the services that you're already subscribed to and/or you may be able to subscribe to new ones.","Adding a Subscription","To add a subscription:  ","In MetraView, go to My Subscriptions. ","Select the subscription you want to add and click OK. ","Changing or Unsubscribing a Subscription","To make changes to your subscription or to unsubscribe call your Customer Service Representative. ","Viewing Product Offering Details","To see product offering details: ","In MetraView, go to Bills &amp; Payments. ","Under Charges, select Detailed View. ","My Subscriptions","MV-subscriptions.hlp.htm");
Page[38]=new Array("On the My Activity page, you can see a record of your activity in MetraView. This security feature gives you the assurance of being able to see the activity you have been responsible for in MetraView. This activity log shows your logins and logouts, payments, subscriptions, and account changes. You can filter the information by dates and other criteria. You can expand an entry to see its details.","Your account log can include the activity of a bill manager, if your account is configured to have a managed bill relationship.","A bill manager is a special category of subscriber account that is responsible for the bills of other subscribers. When bill managers log into MetraView, they see a list of the subscriber accounts they are responsible for.","My Activity","MyActivity.hlp.htm");
var PageCount=39;

function search(SearchWord){
var Result="";
var NrRes=0;
Result='<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">\n';
Result+="<html>\n";
Result+="<head>\n";
Result+="<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>\n";
Result+="<title>Search Results</title>\n";
Result+='<script language="javascript" type="text/javascript" charset="UTF-8" src="dhtml_search.js"></script>\n';
Result+='<link rel="stylesheet" type="text/css" href="stylesheet.css">\n';
Result+="<style type='text/css'>\n";
Result+=".searchDetails {font-family:verdana; font-size:8pt; font-weight:bold}\n";
Result+=".searchResults {font-family:verdana; font-size:8pt}\n";
Result+=".searchResults a{color:#555555; text-decoration:none;}\n";
Result+=".searchResults a:hover{color:#0000FF; text-decoration:underline;}\n";
Result+="</style>\n";
Result+="</head>\n";
Result+="<body onload='javascript:document.SearchForm.SearchText.focus()'>\n";
Result+='<table class="searchDetails" border="0" cellspacing="0" cellpadding="2" width="100%">\n';
Result+='<tr><td>Enter a keyword or <u>exact phrase</u></td></tr>';
Result+='<tr><td>';
Result+='<form name="SearchForm" action="javascript:search(document.SearchForm.SearchText.value)">';
if(SearchWord.length>=1){
   while(SearchWord.indexOf("<")>-1 || SearchWord.indexOf(">")>-1 || SearchWord.indexOf('"')>-1){
       SearchWord=SearchWord.replace("<","&lt;").replace(">","&gt;").replace('"',"&quot;");
   }
}
Result+='<input type="text" name="SearchText" size="25" value="' + SearchWord + '" />';
Result+='&nbsp;<input type="submit" value="&nbsp;Go&nbsp;"/></form>';
Result+='</td></tr></table>\n';

if(SearchWord.length>=1){
   SearchWord=SearchWord.toLowerCase();
   this.status="Searching, please wait...";
   Result+="<table border='0' cellpadding='5' class='searchResults' width='90%'>";
   for(j=0;j<PageCount;j++){
       k=Page[j].length-1;
       for(i=0;i<k;i++){
           WordPos=Page[j][i].toLowerCase().indexOf(SearchWord);
           if(WordPos>-1){
               FoundWord=Page[j][i].substr(WordPos,SearchWord.length);
               NrRes++;
               Result+="<tr><td>";
               Result+="<a target='BODY' href='"+Page[j][k]+"'>"+Page[j][k-1].replace(FoundWord,FoundWord.bold())+"</a><br/>\n";

               if(i<k-1){
                   if(Page[j][i].length>350){
                       Result+="..."+Page[j][i].substr(WordPos-100,200+FoundWord.length).replace(FoundWord,FoundWord.bold())+"...\n";
                   }
                   else{
                       Result+=Page[j][i].replace(FoundWord,FoundWord.bold())+"\n";
                   }
               }
               Result+="</td></tr>";
               break;
           }
       }
   }
   Result+="</table>";
   Result+="<p class='searchDetails'>&nbsp;" + NrRes + " result(s) found.</p>";
}

Result+="</body></html>";
this.status="";
this.document.open();
this.document.write(Result);
this.document.close();
}