#############################################################
#Generated on Thu Jul  1 11:24:28 1999
#############################################################


RELATIVEDIR := Shared\lrucachetest\rscachestats

SRC := lrustats.cpp

INCLUDEDIRS := 

MIDL_INCLUDEDIRS := 

DEFINES := 

EXTRA_LIBS := error.lib mtsl.lib configchange.lib mtobserver.lib namedpipe.lib

EXTRA_SYS_LIBS := 

EXENAME := rscachestats

OVERRIDE_UNICODE_CPP_FLAGS := 1
