#define MT_USERDEFINE_DESCRIPTION "pipelineinterop\0" 
#define MT_USERDEFINE_INTERNALNAME "pipelineinterop\0" 
#define MT_USERDEFINEORIGFILENAME MT_USERDEFINE_INTERNALNAME 
#define MT_USERDEFINEPRODUCTNAME MT_USERDEFINE_DESCRIPTION 
#define MT_USERDEF_PROJECTNAME MT_USERDEFINE_DESCRIPTION 
