using System;
using System.Runtime.InteropServices;
using MetraTech.Basic;
using MetraTech.Basic.Config;
using MetraTech.DataAccess;
using MetraTech.Interop.QueryAdapter;
using System.IO;

namespace MetraTech.ExpressionEngine.Metadata.Hook
{
  [Guid("706C1702-05C5-40CC-87E4-72CA5CC5D713")]
  public interface IMetadataHook : Interop.MTHooklib.IMTHook
  {
  }

  /// <summary>
  /// Hook that retrieves metadata from "%RMP%\Apps\Data\MetraTech\Extensions" folder 
  /// generated by Expression Engine export tool integrated in ICE prototype menu.
  /// After that hook inserts new record in "Metadata" table with serialized metadata.
  /// </summary>
  [Guid("0EE7CD28-E3D1-45A3-BDA0-48AA6571A9F5")]
  [ClassInterface(ClassInterfaceType.None)]
  public class MetadataHook : IMetadataHook
  {

    private readonly ILog _logger = LogManager.GetLogger("MetadataHook");

    public void Execute(object var, ref int pVal)
    {
      try
      {
        _logger.Debug("Retrieve extensions by expression engine");

		var metadataPath = Path.GetFullPath(Path.Combine(SystemConfig.GetRmpDir(), @"Apps\Data\MetraTech\Extensions"));
		
		if(!Directory.Exists(metadataPath)) {
		  _logger.Debug(String.Concat("Path for Metadata does not exists: ",  metadataPath));
		  return;
		}
		
        var context = Context.LoadExtensions(metadataPath);

        _logger.Debug("Retrieve metadata from Expression Engine context");

        var metadata = context.GetMetadata();

        _logger.Debug("Serialize metadata");

        var metadataSerialized = SerializationHelper.SerializeDataContractXml<ContextMetadata>(metadata);

        _logger.Debug("Get query for metadata insert");

        var queryAdapter = new MTQueryAdapter();
        queryAdapter.Init("Queries\\ExpressionEngine");
        queryAdapter.SetQueryTag("__INSERT_METADATA_RECORD__");
        var metadataInsertQuery = queryAdapter.GetQuery();

        _logger.Debug("Execute metadata insert query");

        using (var connection = ConnectionManager.CreateConnection("Queries\\ExpressionEngine"))
        {
          using (var metadataInsertStatement = connection.CreatePreparedStatement(metadataInsertQuery))
          {
            metadataInsertStatement.AddParam(MTParameterType.DateTime, MetraTime.Now);
            metadataInsertStatement.AddParam(MTParameterType.NText, metadataSerialized.ToString());
            metadataInsertStatement.ExecuteNonQuery();
            metadataInsertStatement.ClearParams();
          }
        }

        _logger.Debug("Metadata hook successfully finished");

      }
      catch (Exception e)
      {
        _logger.Error("MetraTech.ExpressionEngine.Metadata.Hook.MetadataHook failed with the exception: ", e);
        System.Threading.Thread.Sleep(1000); // sleep so that exception is written to the mtlog.
        throw;
      }
    }

  }
}
