#define MT_USERDEFINE_DESCRIPTION "Extended property table hook\0" 
#define MT_USERDEFINE_INTERNALNAME "ExTableHook\0" 
#define MT_USERDEFINEORIGFILENAME MT_USERDEFINE_INTERNALNAME 
#define MT_USERDEFINEPRODUCTNAME MT_USERDEFINE_DESCRIPTION 
#define MT_USERDEF_PROJECTNAME MT_USERDEFINE_DESCRIPTION 
#define IDS_PROJNAME 100 
