
	   CREATE TABLE dm_t_inv_summ_children (
		id_sess bigint NOT NULL,
		id_parent_sess bigint NULL,
		id_acc int NOT NULL,
		id_payee int NOT NULL,
 		top_lvl_1 int NULL, top_lvl_1_desc varchar(200) NULL, 
 		top_lvl_2 int NULL, top_lvl_2_desc varchar(200) NULL, 
 		top_lvl_3 int NULL, top_lvl_3_desc varchar(200) NULL, 
 		top_lvl_4 int NULL, top_lvl_4_desc varchar(200) NULL, 
 		top_lvl_5 int NULL, top_lvl_5_desc varchar(200) NULL, 
 		top_lvl_6 int NULL, top_lvl_6_desc varchar(200) NULL,
 		top_lvl_7 int NULL, top_lvl_7_desc varchar(200) NULL,
 		top_lvl_8 int NULL, top_lvl_8_desc varchar(200) NULL,
 		top_lvl_9 int NULL, top_lvl_9_desc varchar(200) NULL,
 		top_lvl_10 int NULL, top_lvl_10_desc varchar(200) NULL,
		id_view int NOT NULL,
		tx_view_name varchar (255) NOT NULL,
		tx_view_description nvarchar (255) NULL,
		id_usage_interval int NOT NULL,
		confconn_amount numeric(22,10) NOT NULL,
		confconn_tax_federal numeric(22,10) NULL,
		confconn_tax_state numeric(22,10) NULL,
		confconn_tax_county numeric(22,10) NULL,
		confconn_tax_local numeric(22,10) NULL,
		confconn_tax_other numeric(22,10) NULL,
		id_invoice int NULL,
		invoice_string varchar (50) NULL,
		c_ConferenceID nchar (30) NULL,
		c_ParticipantName nchar (60) NULL,
		c_ActualStartTime datetime NULL,
		c_ActualEndtime datetime NULL,
		c_UserRole nvarchar (255) NULL,
		c_CallType nvarchar (255) NULL,
		c_Transport nvarchar (255) NULL)

	  