
	   CREATE TABLE t_cc_failure (
		id_sess bigint NOT NULL,
		id_acc int NOT NULL,
		id_view int NOT NULL,
		tx_view_name varchar (255) NOT NULL,
	   	tx_view_description nvarchar (255) NULL,	
		id_usage_interval int NOT NULL,
		dt_session datetime NOT NULL,
		dt_crt datetime NOT NULL,
		amount numeric (22,10) NOT NULL,
		tax_federal numeric (22,10) NULL,
		tax_state numeric (22,10) NULL,
		tax_county numeric (22,10) NULL,
		tax_local numeric (22,10) NULL,
		tax_other numeric (22,10) NULL,
		c_originalaccountid int NOT NULL,
		c_creditcardtype int NOT NULL,
		tx_cc_name varchar (255) NOT NULL,
		tx_cc_description nvarchar (255) NOT NULL,
		c_lastfourdigits varchar (4) NOT NULL,
		c_reason varchar (256) NULL,
		c_retcode int NOT NULL,
		c_respstring varchar (128) NOT NULL,
		c_terminalid int NULL,
		c_csrid varchar (40) NULL,
		c_paymentservicetransactionid varchar (32) NULL,
		c_exported varchar (1) NOT NULL)
	     