
           CREATE TABLE t_inv_summ_Parent (
	   	id_sess bigint NOT NULL,
	   	id_parent_sess bigint NULL,
	   	id_acc int NOT NULL,
	   	id_view int NOT NULL,
	   	tx_view_name varchar (255) NOT NULL,
	   	tx_view_description nvarchar (255) NULL,
	   	id_usage_interval int NOT NULL,
	   	confcall_amount numeric(22,10) NOT NULL,
	   	confcall_tax_federal numeric(22,10) NULL,
	   	confcall_tax_state numeric(22,10) NULL,
	   	confcall_tax_county numeric(22,10) NULL,
	   	confcall_tax_local numeric(22,10) NULL,
	   	confcall_tax_other numeric(22,10) NULL,
	   	AccountCredit_amount numeric(22,10) NOT NULL,
	   	AccountCredit_tax_federal numeric(22,10) NULL,
	   	AccountCredit_tax_state numeric(22,10) NULL,
	   	AccountCredit_tax_county numeric(22,10) NULL,
	   	AccountCredit_tax_local numeric(22,10) NULL,
	   	AccountCredit_tax_other numeric(22,10) NULL,
	   	BundledDiscounts_name varchar (30) NULL,
	   	BundledDiscounts_amount numeric(22,10) NOT NULL,
	   	BundledDiscounts_tax_federal numeric(22,10) NULL,
	   	BundledDiscounts_tax_state numeric(22,10) NULL,
	   	BundledDiscounts_tax_county numeric(22,10) NULL,
	   	BundledDiscounts_tax_local numeric(22,10) NULL,
	   	BundledDiscounts_tax_other numeric(22,10) NULL,
	   	UnbundledDiscounts_name varchar (80) NULL,
	   	UnbundledDiscounts_amount numeric(22,10) NOT NULL,
	   	UnbundledDiscounts_tax_federal numeric(22,10) NULL,
	   	UnbundledDiscounts_tax_state numeric(22,10) NULL,
	   	UnbundledDiscounts_tax_county numeric(22,10) NULL,
	   	UnbundledDiscounts_tax_local numeric(22,10) NULL,
	   	UnbundledDiscounts_tax_other numeric(22,10) NULL,
	   	MiscCharges_amount numeric(22,10) NOT NULL,
	   	MiscCharges_tax_federal numeric(22,10) NULL,
	   	MiscCharges_tax_state numeric(22,10) NULL,
	   	MiscCharges_tax_county numeric(22,10) NULL,
	   	MiscCharges_tax_local numeric(22,10) NULL,
	   	MiscCharges_tax_other numeric(22,10) NULL,
	   	id_invoice int NULL,
	   	invoice_string varchar (50) NULL,
	   	nm_space varchar (100) NULL,
	   	invoice_date datetime NULL,
	   	invoice_due_date datetime NULL,
	   	c_recurringchargename varchar (40) NULL,
	   	c_dailyrate numeric(22,10) NULL,
	   	c_recurringchargestartdate datetime NULL,
	   	c_recurringchargeenddate datetime NULL,
	   	c_recurringcharge numeric(22,10) NULL,
	   	c_activedays int NULL,
	   	c_proratedcharge numeric(22,10) NULL,
	   	c_Issuer varchar (80) NULL,
	   	c_MiscCharges_Inv_Comment varchar (255) NULL,
	   	c_CreditTime datetime NULL,
	   	c_Reason varchar (255) NULL,
	   	c_InvoiceComment varchar (255) NULL,
	   	c_ConferenceID nchar (30) NULL,
	   	c_ConferenceName nchar (60) NULL,
	   	c_LeaderName nchar (60) NULL,
	   	c_ActualStartTime datetime NULL,
	   	c_ActualDuration numeric(22,10) NULL,
	   	c_ActualNumConnections int NULL,
	   	c_BalanceForwardCalculatedDate datetime NULL,
	   	c_PreviousBalance numeric (22,10) NULL,
	   	c_BalanceAdjustmentsTotal numeric (22,10) NULL,
	   	c_BalanceForward numeric (22,10) NULL,
	   	c_Description varchar(255) NULL,
	   	c_EventDate datetime NULL,
	   	AccountStatus nvarchar (510) NULL,
	   	c_ReservationCharges numeric (22,10) NULL,
	   	c_UnusedPortCharges numeric (22,10) NULL,
	   	c_ConnectionTotalAmount numeric (22,10) NULL,
	   	c_AdjustmentAmount numeric (22,10) NULL,
	   	c_OverusedPortCharges numeric (22,10) NULL
	   	CONSTRAINT PK_t_inv_summ_Parent PRIMARY KEY NONCLUSTERED 
	   	(id_sess) )
	  