
	  INSERT INTO t_enterprise (
	        nm_space, 
		c_name, 
	  	c_company, 
	  	c_address1, 
	  	c_address2, 
	 	c_address3, 
	  	c_city, 
	  	c_state, 
	  	c_zip,
	  	c_country, 
	  	c_phonenumber, 
	  	c_fax, 
	  	c_website, 
	  	c_billQues_phone, 
	  	c_remit_name, 
	  	c_remit_company,
	  	c_remit_address1, 
	  	c_remit_address2, 
	  	c_remit_address3, 
	  	c_remit_city, 
	  	c_remit_state, 
	  	c_remit_zip,
	  	c_remit_country) 
	  VALUES (
	  	'mt', 
	  	'John', 
	  	'Metratech', 
	  	'330 Bear Hill Road', 
	  	'3rd floor', NULL, 
	  	'Waltham', 
	  	'MA', 
	  	'02451', 
	  	'USA',
	  	'781-839-8423', 
	  	'781-839-8301', 
	  	'www.metratech.com', 
	  	'781-839-8300', 
	  	'P.O.Box 23', 
	  	'MetraTech',
	  	'330 Bear Hill Road', 
	  	'3rd Floor', 
	  	NULL, 
	  	'Waltham', 
	  	'MA', 
	  	'02451', 
	  	'USA')
	  