
      BEGIN
         EXECUTE IMMEDIATE 'TRUNCATE TABLE tmp_discount_1';
	 EXECUTE IMMEDIATE 'TRUNCATE TABLE tmp_discount_2';
	 EXECUTE IMMEDIATE 'TRUNCATE TABLE tmp_discount_3';
	 EXECUTE IMMEDIATE 'TRUNCATE TABLE tmp_discount_4';
	 EXECUTE IMMEDIATE 'TRUNCATE TABLE tmp_discount_5';
	 EXECUTE IMMEDIATE 'TRUNCATE TABLE t_pv_groupdiscount_temp';
      END;
   