
		BEGIN
			DELETE FROM %%PART_TABLE%%  
			WHERE id_sess IN (SELECT id_sess FROM %%TABLE_WITH_TEST_IDSESS%%)			
			
			IF OBJECT_ID('tempdb..%%TABLE_WITH_TEST_IDSESS%%') IS NOT NULL			
				DROP TABLE %%TABLE_WITH_TEST_IDSESS%%			
		END
		