
				  CREATE GLOBAL TEMPORARY TABLE TMP_ACC_PERMISSION_GROUPED 
					(	ACCOUNTID NUMBER NOT NULL, 
					WRITEPERMISSION NUMBER(3,0), 
					CONSTRAINT TMP_ACC_PERMISSION_PK PRIMARY KEY (ACCOUNTID)
					) ON COMMIT PRESERVE ROWS 
				