#############################################################
#Generated on Thu Jul  1 11:24:40 1999
#############################################################


RELATIVEDIR := Core\Notification\MTNotificationTest

SRC := mtnotificationtest.cpp

INCLUDEDIRS := 

MIDL_INCLUDEDIRS := 

DEFINES := NOMINMAX

EXTRA_LIBS := error.lib mtnotification.lib

EXTRA_SYS_LIBS := 

EXENAME := MTNotificationTest

#OVERRIDE_UNICODE_CPP_FLAGS := 1

TEST_UTILITY := 1
