#############################################################
#Generated on Thu Jul  1 11:24:31 1999
#############################################################


RELATIVEDIR := Core\Configuration\SchemaReader

SRC := SchemaReader.cpp MTXmlSchemaReader.cpp SchemaObjects.cpp MTXmlElement.cpp MTXmlType.cpp MTRequiredAttrs.cpp
INCLUDEDIRS := 

MIDL_INCLUDEDIRS := 

DEFINES := 
EXTRA_CPP_FLAGS = 

EXTRA_LIBS :=  ntlogger.lib error.lib configreaders.lib mtcomerr.lib

EXTRA_SYS_LIBS := 

COMNAME := SchemaReader

OVERRIDE_UNICODE_CPP_FLAGS := 

TEST_UTILITY := 1
