// SchemaReader.idl : IDL source for SchemaReader.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (SchemaReader.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

interface IMTXmlElement;
interface IMTXmlType;
interface IMTRequiredAttrs;

	[
		object,
		uuid(60C215F3-D25D-11D3-A60F-00C04F579C39),
		dual,
		helpstring("IMTXmlSchemaReader Interface"),
		pointer_default(unique)
	]
	interface IMTXmlSchemaReader : IDispatch
	{
		[id(1), helpstring("method Initialize")] HRESULT Initialize([in] BSTR aFileName,[in] BSTR aNamespacePrefix);
		[propget, id(2), helpstring("property Count")] HRESULT Count([out, retval] long *pVal);
		[propget, id(3), helpstring("property Element")] HRESULT Element([in] BSTR aElementName, [out, retval] IMTXmlElement* *pVal);
		[propget, id(4), helpstring("property Type")] HRESULT Type([in] BSTR aTypeName, [out, retval] IMTXmlType* *pVal);
		[propget, id(DISPID_NEWENUM), helpstring("property _NewEnum")] HRESULT _NewEnum([out, retval] LPUNKNOWN *pVal);
		[propget, id(DISPID_VALUE), helpstring("property Item")] HRESULT Item([in] long aIndex, [out, retval] VARIANT *pVal);
	};
	[
		object,
		uuid(B5ACB2D8-D8C7-11D3-A610-00C04F579C39),
		dual,
		helpstring("IMTXmlElement Interface"),
		pointer_default(unique)
	]
	interface IMTXmlElement : IDispatch
	{
		[propget, id(1), helpstring("property Name")] HRESULT Name([out, retval] BSTR *pVal);
		[propget, id(2), helpstring("property Type")] HRESULT Type([out, retval] BSTR *pVal);
		[propget, id(3), helpstring("property IsSet")] HRESULT IsSet([out, retval] VARIANT_BOOL *pVal);
		[propget, id(4), helpstring("property MinOccurs")] HRESULT MinOccurs([out, retval] long *pVal);
		[propget, id(5), helpstring("property MaxOccurs")] HRESULT MaxOccurs([out, retval] long *pVal);
		[propget, id(6), helpstring("property InlineType")] HRESULT InlineType([out, retval] IMTXmlType* *pVal);
		[propget, id(7), helpstring("property Fixed")] HRESULT Fixed([out, retval] VARIANT_BOOL *pVal);
		[propget, id(8), helpstring("property FixedValue")] HRESULT FixedValue([out, retval] BSTR *pVal);
	};
	[
		object,
		uuid(B5ACB2DA-D8C7-11D3-A610-00C04F579C39),
		dual,
		helpstring("IMTXmlType Interface"),
		pointer_default(unique)
	]
	interface IMTXmlType : IDispatch
	{
		[propget, id(1), helpstring("property Name")] HRESULT Name([out, retval] BSTR *pVal);
		[propget, id(2), helpstring("property Count")] HRESULT Count([out, retval] long *pVal);
		[propget, id(3), helpstring("property Element")] HRESULT Element([in] BSTR aElementName, [out, retval] IMTXmlElement* *pVal);
		[propget, id(4), helpstring("property RequiredAttrs")] HRESULT RequiredAttrs([out, retval] IMTRequiredAttrs* *pVal);
		[propget, id(DISPID_NEWENUM), helpstring("property _NewEnum")] HRESULT _NewEnum([out, retval] LPUNKNOWN *pVal);
		[propget, id(DISPID_VALUE), helpstring("property Item")] HRESULT Item([in] long aIndex, [out, retval] VARIANT *pVal);
	};
	[
		object,
		uuid(AE00E293-E2DA-11D3-A616-00C04F579C39),
		dual,
		helpstring("IMTRequiredAttrs Interface"),
		pointer_default(unique)
	]
	interface IMTRequiredAttrs : IDispatch
	{
		[propget, id(1), helpstring("property Count")] HRESULT Count([out, retval] long *pVal);
		[propget, id(2), helpstring("property AttrValue")] HRESULT AttrValue([in] long aIndex, [out, retval] BSTR *pVal);
		[propget, id(3), helpstring("property AttrType")] HRESULT AttrType([in] long aIndex, [out, retval] BSTR *pVal);
		[propget, id(DISPID_NEWENUM), helpstring("property _NewEnum")] HRESULT _NewEnum([out, retval] LPUNKNOWN *pVal);
	};

[
	uuid(60C215E7-D25D-11D3-A60F-00C04F579C39),
	version(1.0),
	helpstring("SchemaReader 1.0 Type Library")
]
library SCHEMAREADERLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(60C215F4-D25D-11D3-A60F-00C04F579C39),
		helpstring("MTXmlSchemaReader Class")
	]
	coclass MTXmlSchemaReader
	{
		[default] interface IMTXmlSchemaReader;
	};
	[
		uuid(B5ACB2D9-D8C7-11D3-A610-00C04F579C39),
		helpstring("MTXmlElement Class")
	]
	coclass MTXmlElement
	{
		[default] interface IMTXmlElement;
	};
	[
		uuid(B5ACB2DB-D8C7-11D3-A610-00C04F579C39),
		helpstring("MTXmlType Class")
	]
	coclass MTXmlType
	{
		[default] interface IMTXmlType;
	};
	[
		uuid(AE00E294-E2DA-11D3-A616-00C04F579C39),
		helpstring("MTRequiredAttrs Class")
	]
	coclass MTRequiredAttrs
	{
		[default] interface IMTRequiredAttrs;
	};
};
