
        create tablespace %%DATABASE_NAME%% datafile '%%DATA_DEVICE_LOCATION%%'
        size %%DATA_DEVICE_SIZE%%M REUSE AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED
        LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO
				